apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lldap
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/lldap/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  # dependsOn:
  #   - name: longhorn
  #   - name: cloudnative-pg
  #   - name: cert-manager
  #   - name: volsync