apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  dependsOn:
    - name: authelia
    - name: cloudnative-pg
    - name: cert-manager
    - name: volsync