apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GOkAuBNyW9bZTDCi4jtpusLv3DZfinjIVpmeirJeaoWqwDv4g5gSCQbfiWzEwqwqBZ1ysektpshm9V1DEWyLFkvLMEGNw9A+6RcsmVYBxr8TWBXTk+2qdWbdZB2LCMfCzeRgtHm0AGdvKruYca3UnQtNFllfP0Fot7Bd6Nt7u8iRUVpmtrWUKeIs3T2kCnXd1FOGKHYQ92ae9uKpFuwo3k0GM8Gw4cqQhLGDeIKEumr6V7xfAtmFOkPMMVWE5amCRyWKUZ+9OxosUJGWYC8SkpC9TE8sT6WjcioFzXQeUK3HmkPi3qh6i5nmaJEFJEiIamf22V0nzgIhFGDP4c/1HfigR77fn2uKAKy0s92Ue4mEjEHXoddNHCoSMVFcMWQK,iv:b7/VHmrwHvJp5qGVKy7mKJOMdQAKBOK4IX9tXPprSWM=,tag:0tgPPPW1SbBEcidgROw59w==,type:str]
    identity.pub: ENC[AES256_GCM,data:pWgRVuUHfNxOjAAgxqT3kbe1S4eqo7TUrX62TUY2ctIgcDF8UXKXnFHCXI1KY+OEYPVESJJJyq1LtS6grKesDyrY2Y20urcTJeuIihfWlCaitejX/PiaVifSh5G+TMTsg4E3xiWG/jybYhIK965zCHRlYa39wtus/Nq3AkDIJqlNmOzn+7bnyv8+Ii0wreUcIEDMJFAdThTEuulDw2r6ndKmDsUpmatp0qhqMqTsZ0ml/b8hYw1FXi0luvJJ9Os/qTkM3gYl9e2FeAuC6g==,iv:wyDEXC61iYdipdgBot1492aSDjb5D3EVQePvZmp4AxQ=,tag:M3WATr+mY9QjIKXuUuHV1g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Xx0CRKHyyaUBwErmdwBGniriFdCy2nBYg8tnqVmluhBQ0bJE+IZ86hKdkxM9bXJLcvTGq6H70wHPUOLZBpgVc/1zJQe1fj8wprczzOSdLSMoITX0MIwNWQrxqYtMw5SO432+v+Byd5j1MGL1PUOlt+wArEL+yveeyrZ7/G8v6UgbD0+PXRM6wRnPdCnr489ZR/oKrB+Dir8zuq7+j4tsBxOgf8f7fvTaccnk,iv:i0/774fBzg+nxKDz8dprUv636n08LNJGbk5aUU1P/FU=,tag:MKWUBQZ5HFxShxz3kOakAg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZThkVFVtOHZJb0w2eUp1
            dE1zRXhwelFEK3E2NFFQK2ZodWg5K01PMUhJCklMT0o5SmF4Q2o5ZS83MEp6blhu
            NFVNcEljYmhpK0ZpNDJhb0dISkhjL3MKLS0tIGtxOUxHa0tkL254SnpBMTMzRmI0
            eTg4VW9xVXByREZ4UGdmMXJBdXU1VTgKy4nMv0OIOhUsGXsfo4rMwcFUpwuGY6kj
            qWTTWKxXoZLD725vx1soddoaWJmJ/wArnf04wh4pi1qrzZ7c5FKpVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T10:02:13Z"
    mac: ENC[AES256_GCM,data:7sxSvctsf18LCTlYZekp1LAb07suBlUbsofHfMOQRCOg1KtffD61aKhM2azf8OrpNruLpgSZDJX5Izcu9TjK5PjANgPuN1ccPtqwknKkLh37CLn4W0nWRymIDBKGOazdH1EC4TkLYzSRB0PnPCAmCbzw0Fb3ex1RkfTU267YEn8=,iv:z7SSiV7ntHkn+ym6zcfbNV2u1Z8h5Efzj1BI6CwyCRM=,tag:PPiFNRQLdkJjP1FVBOzCjg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
