apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uVn+W47vR/ZW5vQ844sphllH1+wmfefWJL7xpFZjv2X2L3sOf0TJYPZ9WjKV6WIYGGjtsN0eUml8YBek2M97LaGCVMhVzdRpID4BbjaHUOFaqubJXWO6FQRLSOwRD7l9tQkxwPpl5EPBJ8w8eY8ZxFJzSYRpkP1/sfApNO9EBJXg92Kc5pPZPbhLYRqME9/CuDlKXIWsIrz6E5OryGt17uz25SRlpIz0rAy/4qqstktXTteltt2MoJRcPYNhk53cDClghYa7+LTWNQOUDBq3xbwCUq1Qc4Dg+ne3BPLFIgHttX/LTFj7U5pi6EftaJWdqSioIdfGavdT8sXxeAFjYUHXPSBGDwmEYYWzFYEgD+Kyzo5Os2YlpSrF0NGqgV5q,iv:YyyiLJinJW4EgtH4JQVuF/GX0mf12LIII9WkdgsNuoE=,tag:l1AwSNsk3dlwrggxpHV4Zg==,type:str]
    identity.pub: ENC[AES256_GCM,data:fK7cuOr3LPAQj0XeiPqI1Cw+JdFSHp+Nu0wGKC2pyMgFh7gYP5Aav+l4CZiXNeKi9IHDK4Uho3+7JD/UUM+TxYaZ0nV+6i204VO7/ZJu7LzCtLIvWDnBM1xelrxcsJRKOEUvpYmrEEfC47uYloPD+mL/jbCS2jgfnMBadzsSbzlJ3qAUUGwh0ukZCimULq0HGS0dZYBjdJEc2A3a5y7o1Zt0iaXExaRtTggRNeOSk+Ekmg9ePCRIm1UG/9LiGEaDEVewP4VvtD8Oa4yg6w==,iv:wSGW9yAxdMn/Psoz//E7lYK2pvbLooKL0Sz4txtBeao=,tag:cMZhJT9wR00whv2hyPQh6Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:9GreVTB6nugNdh4oC0UZNiYIBJSvt9/o+u6W7OfPt5OoRSz5sjvmDokrGEk5pA9ACJ8K+S1HFfYlXpkyGeVO+KiQgKQ2OhFZbaKi2sxFFYyp1uLIz+6PhYc2IsrhIo1kgnMOWftBCn4wSjLZ2y9BQ+v5KisNtmJ43f4vjnjOnLvabfLjvq/2zGiMS+AchuILsafqXfva7x4WDW+rY76MwLRTeD3LRL8zz851,iv:mWUW1I89zMVTAaI/DPtk//03oTely+q+XaO753bH1nM=,tag:svUjKNoc6DIpXMDmvXlaYw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTFl3elNWa0xDQmFtY2Nj
            VWJHUGpQakh1dzN0RHg5cEVsSUlROUNBeVhBCkdPWjgvZnhIUFRrV3grOGRFdERt
            TERBRWRBRklveUFad2RHTGQwaFhPKzQKLS0tIDBiRGtjQUV1eFF5bUlHeGJwNnJI
            Z0FocUlKUTkyWUw2TWVUcFJSeU9rczAKFwBKRKlvUGp8uXaoLuhll1AUbXxB80jZ
            T9g8IMJr1TM4baHpYbunhArLkBrbNUyfoF8WStUIOM0WWexpwKIRXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T11:54:38Z"
    mac: ENC[AES256_GCM,data:nCbvqDaRh5wV3qBbS0nH+IWAFeGFT5zH4q0WH9qOz55OI2aO41u9AzFku44CqfpXKf/pK7b09IhzWZx5jiu1v9MBGUdKhw6Hr164p7zxhKJgzIrt8o76yrO/QNrjVFqVNXxd5Gw2sbQLDBTvU+OhXy0Iyk0a3/9QduMrBsnGt1A=,iv:iHMtLZR04x03K4hIsXCV06lbgJofIN1yGQunXznj7ug=,tag:t86d/FLkYQryfABGcUH8OA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
