apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rzSt6H0Z4nf8fqEXwltXPUFGieNuCazt7g6AfjHt9zdXfzwjwRs1r5nLQ9ZLuZxjO8bAY9f5BVIchIMGu3zoOckmOyiI5f7vCV7qgfdXZJn50VmDc3su79TkagUhX1QPKF63BelQqu/QdXRPnjg3BKN5L9TxTNVn3YPXhM0I0T6O6c5pEZpLMTPnL1ifURiZW3ZlT0IwxZDFVJKz04DWlvm+64Fgbn1DCmyg6g2yS8XQAiTi7FBKI1Nsn4qXm0rk4Nrd+ylju9sB0hW7KWv5sfJYwMrpZBebzB7//hgbBembojSjijLwaUL1/GEraVHfHMJCDf4xWRNAM0bP6DgBq8f0NaoJUFahsmLdceZ+BB6ymFEJmJavoqjeGkE0o7ZA,iv:k4wMKJ1SAWlbHqeaEcjEgQ0n3A9w/Qhmd174iGZ6RtI=,tag:kZ0emnsoiIkvh6RxFxDizw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yJnXKoPFLUiHQFuUd5MZHxa98yBrmnCfv0t2i8aDehc3Q5ezRigTygeIX1lX9N9BN6JE0srUx99wJuAimvdeQ8UllDJ5YEYdcHxqaScxzIbHJeV0w7FsiuuJUXKHUXwyJTKsCtiXHbdLSkRTC26VR1/O+vgwJKqkpFbsT3EIKUl3joob2Qo+1CeOmB1GtU2zt1w5kIa/1LKkofLt7nDQETNlG26Xp3yk0/IkrDSI0cTEkKMvN1XezlOit9pU8ehAAWrzSW1qUa3akHIuVg==,iv:VQkNy5ScNyMfd8rqrnhP5h8sSm+msHlUMY3BtMbbjbo=,tag:xu3IxvpdgsZ/0jHgPiuHtQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:9ptmVRa41VjbLjXISGJYtcmnBWWaa7IZ7sXFk4sE/Gf+Ht7eWzlg3z5+hxBW+gvdXDfVLtsOAYbux0qrK+wjPP0YbUGsgjNU6CWPaR3QoiBDnZOzlHzqFcBnITf4QZhoUsVVDjUvgkDkgmgiiGcEGEQs5Y6tQlUOLbbhQDiu6fGVAhACXbVo39UkGVnxtI70zR4WOo9b/QpDBaJK47o59KapKD1N0dlZAsbw,iv:fXFiUQIJ2ZdmQG2cJI2nIzwxgO/Wb0NWwyuFHR9k4Qo=,tag:iJ0LrVVF1SqbN78WUwVLnw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQVllY1NaREhzaGhMYWNk
            YU9JV1cwdzVBRlowb2xOYmdYRjIrdTZaK2o0CjZybFBhbHd4YWpudmJZMER3OUlt
            cGt5Y0d3RUpIT2lYem00aGFWQmc0QzAKLS0tIEo0UWlPSlRFcnNzTzhSclM2aWpo
            cSswSEo4cndzT01lcUhMaWYrSVd6TWcK4A5f8TdOBFrQJtABjdI1AO8TlKDh/7Jl
            krRBUlqq0rsDcGpNyHZYKARUTE+e818DBTgufTYbwS0bv2CgmkNK0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T04:39:40Z"
    mac: ENC[AES256_GCM,data:TbbONvPWSVxFlphDK1miBZkNxw9AtIIX7YK0Rct98Hss4rZkARZ6RZlobJRvGMpvMQNWwtpaB1PD5MlIUYZFwNIeF52bF0VK/WpmoUwOQSQO+QLFwGcHyKRPzXdo4NRRZ8LnKG/kQPggNCfqNafR6eYh7kS7BWRRBWZuUiYYH/k=,iv:n3VQ1Thpao/ryJFdAtMefp4pedYtqLaX6kADKFCSMNU=,tag:Z/NXIF6TkNqozKqNMV1ixg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
