apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+l4gQ6VyZuBTXNc078Tf86+7GAAGDXwkBJd57pk8OhqPL6sHS0+6PuEUgvjwj6074afojLQ5glhUw0w4yaLPISRGdJJ14/TrdakXRFaA/umAqPr8Zbl0DFMZBeH6R6CHiHDoWDCGuVSlhhtIoirlrdOz2xCXvcxC7auX5jfHJxAvluO1zY1LAKTEaved5zU9gCPWF389BuewRmsn4gTxq+4QjzFrGAraii7fSxy/ZXPiKCYx+WDJwQ+G6cP3vmxTLKililbdeddGrtnkQPTZxauBHAQY80Ry5bDaS7TlaW6Rare3TTVgwP3sPGZWQfImQxmX2cmzeMaj8Z+g/w7SYyFr+DfbXC2u4u1TQaoh/C2IosSpwVxCQhztCVQLjCNr,iv:nBGTQ6AUelzCfPvexpYJePBhb6yKKOtsFh7zrZeqs3U=,tag:QNbf3ZArSU4mWwuus2u7lQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZgCNB9EVyItqj0Eyio7/Dn/KjQ/UoPY5VA0242o+3ApXy3FT5VAkmips+pMGXhHBThZ8TFhwyfNqh3E+9dEIBotl2Qu2XMQdfJ0asdVQgld3NQYdYTVd2GskkuErvR6Mt2axAxHi2uUHsIgXlnSE2tBIsZSWC55yAKTXohKbE/EETVnJV2pWy6/2WHdnJ65FjZ40njlzEQX3OEmCASfgSHURv00O2e9ivVl+BfEIU6lbW2MvuMMMFwacH027qG6EZEqzCpAye+GDEBH/EA==,iv:lWfPpbpi15dq0+RsWBXGLe/C5y3kRZzm/KeaBrY/QCA=,tag:CWPX3tWsgrf9nNFnv5KDAw==,type:str]
    known_hosts: ENC[AES256_GCM,data:FM9JIrFeTcMoeDaxu+87HvHRMy3C1G0jzijg+qL6PExaDmdg+6D1Vl1AsAx3V5Jon2BmbOP7ZoDJdNPKYzlv9D8Hnq8aPsVkBcguUYm0fH/gLBG1J+gyVQA9zhfnTBVaINn9GZc1Srzmg/+yVg6vKbJmtd70vsLalWBRq8iOx155jams0oWnMQjo1Z2YXcIicJ+TQo67l1yFrbWVgaBXEvf8VH9wSePF/539,iv:OEB1znu+C8AnoBYithuMQNuqRbevJeRsfRKnviwFyqo=,tag:4gceHm3yhC0V4Q2yKnVJgw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVVk4eC9KYTRkaUVVUzJZ
            UExSVW8wUkFYODZickNmSjVxWGU3aUJrV2hVCmFpMTgvZWxSK1JrUUZ6YTdqZHY3
            RCtMendJK1lTRWVJNWlqY0ZTVDBkSVkKLS0tIHZ1dE5nUnRDR0VCdjZWWFRrMUor
            bEpBdnJFZ3VqbDhWaTY4VjV3S0NGT0UKkS2Lj6y+R5650ZpELqyTMTovQKh9RS+n
            Yjd2Y3hdkkLo8iWfcv0CGtKXfCQBgSK5N2E5cvLaON5D96w0cTZXpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T06:01:51Z"
    mac: ENC[AES256_GCM,data:e51+jgnERZznrRBU5oc/0rzAVtsKd8GmK27i3BCHz+GFS8ivot2zwbsWMsmvbopT+sgrLFmj9M+RYPM+z0Xx2YthzdcO58ek8UTbYtja4fsiDaOrsdTXGve9MwHIgvN1xxCVuj0Nz3o9utPhTFxVJZIP1sF5Vb2PhJhUZQDZJC0=,iv:0gxZ18jI9OqmCtZxxeiKSJE8Hq6av7Dt1GgC9AquxBc=,tag:O9kLVECV8uGWN6cZzpPYEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
