apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7b/1Ww7slcn7l4UtQz+9TdneRbSVJkLMeDa/NvEopmkdWJ5G5cME3ay9vUAmTy0dhjhLOQ6q8G8nrG6FnW2pARVl4YQxF/anxGmsRMFYnS22diW9h4uV6FUidnGdwo+YwbP+NVNQR51C143tM426t/lmwviEqHfSKSzCC6CQ+JCgTbJ2oPNLutCbwPirDnFT56LGukhni5yYebZ+qrflHbmGxoT7poDRFGDNjJPn7L06lJBN9ddDNQm9/fpwOXl8UgDgIgVyYEzucP8vkZqdWj6TnO48jK9iRVRj501PNZmg9/1bsZPRD4iCM2W5FO7+qAVk54CyBDvfjVAk0m3aPiPVS/6jCuYpCXe2mE2SmtDNxv1MIGVzvWDKMJj+jTV/,iv:3zJ0KR3D6mtoTpu1uiJqtamHVcRogwWVaNnOsy1v+4E=,tag:UBeOCV71KhvOrN4lwqzBsg==,type:str]
    identity.pub: ENC[AES256_GCM,data:gjCa1GdASLX5OLWpNuqpBgTM+z84e2Vc36nVZNzxTy+3BmcyUUo5s76iWSLKZZ77hltP8rk6PnozLrjC4Y6Hpp7VdlXVRUayyD8y5BE1FXR7tACg8KBM3nXBD8nuKQUak0v04CRpajudazrk31+fakFjm4SocPvuEw6W3K+ZXLLDj9XnY3HHeP3781hOxTk0Tr2z2FuzctkjXdzNDexYrpndHVSpTEoaKIXbp/24vukf6nc1E7fOlM8g8KcBE8GPAFG6j11UmeE4N8466w==,iv:H8mg8prMNqwD9pyQuVWzFHhjqajcFDNg5J4Js7h+l7w=,tag:WgimySIpkadJp5zKmjKYcg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Zk6eJRWkIqQZgZL/0xC5aewuSxHiFUUrzMqX5YmrC0HmTKytuREN1DIvqVtFMyD5ETktCbv3IvbIlN5TUaoXcZoFwKRSxqkC8K5qRrZBon9XARKQ4j3Va+XeHMzarNKaGDS0R402SGsRb8dvbU7KR5TGJS+OHoFJJb1DbopcRKoNuw+mZN4GHTnd1GLPSda25Lt7w7TkTqptjL9MP3O3zcf3DR19jt5Kgz/b,iv:WEu/Iv7b7WeZeTGUpqui8kZZmTDYZFYU2ZMsJWivGL0=,tag:n+V1cHTKgkpeoYoIPH+o2w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeldWT1hzNU4xMXBlOWxC
            Mlozay9yYjByYy9GTDRpOUNyV2Z6L2hhclE4ClVPbjF5Z0t2bXdweVRuaFIzWEpM
            Sk1HcWhSbkp4N0NwUDduZ2wreS9Ba0kKLS0tIHdQRlErazZpaFZrYTd1QXFRbTRh
            Zi9ZSWxLd3Y1bzNjYjJnYmFTaVlDZmsKLyKTESFF3ccQ6kera3cPr1M707cOxiyK
            H4WgvH/VY4nkZ0MGeVawIBYJvzNjFvvoJFasO66QlxZKPq4gbLTL1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T02:21:15Z"
    mac: ENC[AES256_GCM,data:9TUyOwSth288JAE9yc/FO+FCqiXGUjt+7N3DrAyMf5j52Tk0o3r+PvIMZXAEnIPZ6VpvhNJfi4zBX+fTUYRA5lZzfsmS8V3mQuQnZFBIUX8E2xv7ingBgHsxHYttdrKZ/UzGkrOpU0lHj9/MhgJjq8iG+5IMQmZsbYVaLgUhUYU=,iv:bXUEdYQ3LykaH8PMsbYECBOGr4B1+OiOWNO/yKbWZrU=,tag:7utPKjNrp3cePhIm+TS1FA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
