apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tNk1uEOr+56lBQVYs0R5pbl1Y7DYzZxlaoiXVyDEdBBUqJifDxb1OAK5OTT6pTBanOTOhukMCuRTwhHR7zwL0fPr2NeN6jgCgoSrIxupTnroZDUZX4S4XuJaagM/7/vtQuDI0uiWD5C0c0IKwx+n4lv7Tt8Vwpra0Jei+0D4rCHGrKGeRb6vsK1ZpOJP9bqKa/5gw+YjxSyW0pku0vECkv1ZtXu+s/eEy0DkIB841X5eFdxM/GR4bxxpaucM+CWjw2OskCN+81CYf9tTdA/oqT9dc9J8XwCb/+dR2A9DAT0ODy5Jd4DOL/mQKuX2O2ULXhzU8gisDA4nZEh1YOtJdJqWkByxVpnUAapMjeGtLBA0ud9dcSxLa9m6v/2Ig6U1,iv:D7tvI2PTYEOISlHH23CqdOtcAasDV6TTkQ3XqziTeIM=,tag:AAHnR2Kr7M98rTY0+u3/qg==,type:str]
    identity.pub: ENC[AES256_GCM,data:I1EL/idQrII4q/eNGtBgFCXAU/fXj05qOtaFRX/oLOMAWUN2ADe3H/kYnTcwAvUzdsRpxo3XC7EVIL59fdiox87H+dKYyynvF5X61uVB2OqWQa99WQc5kGc9bqWwlLmk8MbutfMKcJJ0d3r5ODJwCAlyEZeTtd5iVZYalDgPAgNMWvRfQ5+0D/Pz3A0hZCYs2KHqAcws12scTYtZD4rtDWsYVE0QygQKJPcEp/3B3ys7AYv50F0t0n2uawi0hfgWP5ZMr29yftVtcl250Q==,iv:1AirG2L/Mj6HfEVJXYXqwaJ+Hyl3O7vKzv8mIW2UJSE=,tag:+csnMHIYedq1MjZWrTcASQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:T4Fny4YZQ/WSvtt7CP1rGOiIVc2R6mx7A2oafPJ0340/Ua4hyvQ1NdfeC/wMc1L92XRrLG9Rp6Q4KiYuZdeOzTdtPzWXI+oBssxuRMdRmMxKJZAGpiOA0+LS2TSpq5GGnDZXVrsSJlmmF3eXNRT8YkmWmCmQ2qQ2PcuHx6YrIHd/XP5fqT4M72bPWrym/mHw+M/Rk+5ngSQmXC+LBM4BYq0eFDZG9JdbLkCv,iv:Z1owJhB5oZN5Qvf8jqaHpAlizBUVPoZhQTSkkw4JZPQ=,tag:eFJ08/V2pHkahwnHmS80mA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxc2FEM1hqZG43K1ZkUlhE
            c1QweTBnRkxSUkNUYTgyWFV3eE9vZXdaRld3CjBJUkp6S1o1Mi8yUVlxZklyWDlm
            WmFmTWw1L040SzhmSXNwdEJJTHNrbUUKLS0tIDlKSVloNHh0TCsyRHQzaGpLamIx
            eXVSN0FsM0RvNmJSNTdmUmN0Vis1K1UKFN9+lexEjwaV397sLcEoSWWYWARndECD
            98q+Y+GnMhJd1j/qmTdHPxySjtaDi9RMboUtntCjwKJWbf+dFbFfjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T04:45:06Z"
    mac: ENC[AES256_GCM,data:t7TJOLgXW1KpmtI8mTRpoiQylTz6K7zCoL22r537JzesSHQRLCbftzb1kodXKewMxNMF8urKU4QiUilI6Sg9zAJ2hfuyreg0CqYpd362d4eYBbDeWh5F+c235EqizNDz4FelxRtVNzjPQ3yP9OVOkkXz5crjgCYRmIgtG9JP/oQ=,iv:OpCwwR6/AuZR+SfXDCh0+EQjLG6auPIJsBp0nLLq9Zc=,tag:zUWGLp5rHoQ7fRep9DepXQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
