apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:29SzzKao8a/Nl9BPzpcglT9TShYQxIysS3rtDPp+n89wUDYyHm0PFjckBD9tE3H4lk3jc07+lknvcaRXDU2niajA2odHezq4Gw1mWyIkofBcw+9F/+32JhBIsjNCOHN+oTXpEKY4YlszGRFVotQlV1XV/QBKimWnxpjElo90k55h3E0iqYqiOg6euCfLhQs/6V+ogIb02QDp3sA3D2kQVXID/zODmoTTScIXJ7U43dxN6yFDg+NNilhj5tsNChkQ119AIZeg+XAetSmtG8e2vdUdWgIlDf0U0opD98iGLMWrhH/VLBNym2Pf0kXkYNMFJmSElakSXI4II4sKuD8HdiKGj53254NnEtB+Swc2VQIVBMg1KsTc6DHjTmS7reZF,iv:X10BNbKv/BMUMV07+qQJO2QEiU/nepR5H7VmTWw7LiU=,tag:HXJrQA4XEZ+jM4bwpyJpFg==,type:str]
    identity.pub: ENC[AES256_GCM,data:gxKCvBfWQVfqSqLFaCX4QNhe7YAQIdy1OzKRxO3odir6G0XkfWeojKjysedU+bnNSgCD/RHhOFeTCkF9aQZXFfnt2zT87vfjE+17DoZk4aaDKljg4c8Pk9d376ilSOrU0sCz94K6KbznNpE8svI4wFcw/VBf9921e1eT5W0vAGt8+Mov0/vQQbGVUvh2eySLiP+uE6B9HgXvrpdac96FWSGLK6xANLPUSWr15fmJpkbN0+Ic+y6cTpKoijWeMkNmU1GPo/tksETdt3L5KQ==,iv:6a0XsYCTUbnCXpIgnWYoPbNRxaWI8dvNXRZNb5RFJ+I=,tag:2Ui9d3o7+x98y9f6VUguUA==,type:str]
    known_hosts: ENC[AES256_GCM,data:wcrBuSa/ckfNXvFgi+bggzxeOf7I3yNN3RhoRA+YhdegKMd682VwcKyPtcBQGWo8h1Amwm6atxaRqMvWFoqT1MDs3EazYf5WEGLtZz4kq93HaC6XqSXK4IGesbmRm9bhVaYDb+R26uUG6MOUWPxpkAifiaM2b64OU/LsQv/lR1yi0HZGO/aFDCLtSvb7zWEVtvvHIDExHN3NX5yR09mAXD3ZFSCCHUXrTWzk,iv:W8qvWA460pXzS6oTHY/FSAvBKJ7zUklUAQScjMcpzvs=,tag:3H5ok9kUJ/FMCpBu5jR5OQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY2NLYXQ2dDVINk9FT0Jo
            Z2g1d2NaTGY0LzZUbXVSaGpLZWs0Uys4R1h3Ci9BZ2pNckV3WFZXZW9rc0lZcGNw
            eUFZN1JWTTdxVm1md3c3MjEzd1ZOeFUKLS0tIGJmVmhmdXlnRWRPZjc2aGxKU0Fv
            SDJReGZLamIyWTF5ajFTVmxKWVE4d2sKVOKptKfIHLN4EvVZcro6rK2AMBzZ+5Fp
            MWfMFTt1WVA/G1OtmrvBQJ3Vj5aCgWWRZc1OTHN97zA13nOH7MtCAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T01:21:33Z"
    mac: ENC[AES256_GCM,data:UNace77bT6q8XVLzIQz5ibf/jfp5i7LKyAJdiuhoBDCUaX4zy1QFL1BWCIpxgH9VRWiATFnNeH3n7nc0sc1RWSgE+RB2xbeE0mYgudXi+KMLC7JjUuPQmElRHZqd49FsiiQlaX8VRFMDhhHhMWyrEfwMYMyPH5688XDXqg05eIc=,iv:fWqEGXB27yor7I24K03nrZStIzUXw083c+jZpozzD24=,tag:AUaauqMgJgCbK0sJKNMHTw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
