apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pAvauD0p48f9fJjdvnHUkHw4y+01YcqKFOE6I8qd3ZQnRXSt9hTo+JA1Eu2iOU1gwa+YjhnnHdKc+D2SQfrtMIRtAdNKa5H2a9lzCrTGhN6rJ0RIJB7fTpSil/87wb7/biQJEqkuO8MXKOG+mpbD3B4CC1Jx8rhZsflmHMCWvDITyrmWzeoB5dud9Y9a8d3NZNQKCZWL4L7A2M+7L1q+cl99G33x8g+XCei/K0xcJFbh8UtirwFXuKcDxPGjdamHy8vdYbIRqiJ8bUgWaZ1XE6iWn3OFYLdov7knS+6aCrIAa0cFh2L7A3TfJfXonSBAVijy2PrtJR+d0o0En8VeoFp6DhOC+OyLq6RBJ5K1+7ySKWq+bhLjJa7UAwKSx95Z,iv:spHkYfT/m2P2SaYrM3f/mT3oK2cn4590GBjUJiGAfTs=,tag:MqCIfbHvFlI+PIN/A396yw==,type:str]
    identity.pub: ENC[AES256_GCM,data:RXqd7unlb6cSKE+zkrg04DTtU4pXAzGAzcsh88rtmkODF2YEGqC2eT6EKLvy9j69dW+EHxGbQgsqUBTVUMInSwkZE5GcXcFUcNKNq/5LJNvZP9AOjhAvENmkEnDA/TUfzL2guKYhJqfRll5YHs/BQUtJuFkNh9FzBGbawLjgGXP4AbLTsG5UT2ccA7oh6/SR6WlkfAEsTissyXGWo7/cUfyahWMLjYnmFzmi6VfohDJRhPRgK79VciWsOsAJeYJ884TE9Sk3cw8z01/wrQ==,iv:+1bJn95f5Avv/enOS7zYSd5EfketlOAKUGCvPGv4n3U=,tag:3V5BluVcCKKQqJkVKTplJA==,type:str]
    known_hosts: ENC[AES256_GCM,data:JYoltLURC7M6bIipi2UXK8xCxWmhzv0bM1j9xL4ppjwqn49oxWbudJ1OV4qtt03UO32FOq0M+EDkL524RbBlado7jew1OcFd09A/ZeDyDae2ainwTVPA58/ZTkUshfS1EOLurZ6ms/pc+JtCpJfojLhyVoyvQQWx1gEZVs9AVvLevwU6ofWSTVCcwpWB2ffDs0SR+nlarawGmvDKiCvoO8wEvw2C/TeAyM6H,iv:mneStVei3F+AkvdAJ3ZPQkVErOUYVuLVysuCUxGuUoE=,tag:KYArbSvSgwLUClGOQpoUng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUlZCa2ptKzRydThURWc2
            aWNWc1RLcE9BRGtDMVk3bDFwRGQreEVQOW5vCjFBNVBCQ1NXSDBtNkUvTlNYTGVr
            TmVUSnNaK1lQYTVBMlhxN2phM1NqZGMKLS0tIC9IY1IvakpLY3hnazJnWkxLZmd4
            Qk4wUFBOWmpoZ3VvQkhCUnFIQjQzSkkKuH6aC1KfW16JSuWdz+oeATRVUEf0bQRN
            Cpayc1NLtXnldID3jYnjvxO9ol+xoJxRxnyJc/LceuT4GLlg+1Os6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T22:07:51Z"
    mac: ENC[AES256_GCM,data:IMR+qbFZM6QI0nvvH9x2RuBfnPN5iA+QTefEysRMnI525xwZqlAbeMaHVJ9z3M0hxHptllhkeDqWtgJ/s7AyDbMRJamZAz4sIPpwpFpYFh1AiZzy6fyUppVoYKCgXi0JDF3KUzud7l98MCzZPC8sClJ0BtUFD4e9UiTfWGGTAAQ=,iv:HxriX7OHPc4p5DqWzDY6lFTCUB6CXK/EuHbH3+y+474=,tag:09nvauICL6ar9TcrvQ1h6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
