apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Zq6haAEcO/mz95XYRJcFwyzdI0H0mkjkj5TLRk68jpzIBZSSLmVzNEG6GOpXhhno+PcCNOl76sBCvIvBCzEJTmRTPtLIpp/reTZRg+0Gws1RhmPTG/Cv5caEnqyPXNv/28sH5OBMZDseW4KAtVHh5byDej/te09m7/waL0L8JIhtfto+SbhKEGHFz/+s6XaAR41E+ZzpoQzpKlhuZodH8hNMwKdXjO3ByJ1hsZ6aBtDaVz4zYPyGLXwzkkzR/s0xNDJb2d6lSJsiVyKQ9NPVeTcwyYplJUT2czcLxP0206FaN2JdhGO00qEA4if/2I6JOB59xJi9SOryMc/s59n4OoCOAB5MP80a8DcPwzQlXKxe/sqBXKnFwSMz27CjajKl,iv:Oy+tx1db7tEBTZi43oMcDY5q2EssTv0SARFzdvDUTq4=,tag:VwVbl7oDsN0vfdOrq2GqEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:7k/BEWHpG2WIJQCNrW6FepjldoOP0I0dU2vDzA8S5C5SpVM3yOLRIx7QBm6cvhBivu5ujYU+/7IAnBL4NtLVzvsPvqHHQRxyGJsxUXiLTFzAazTU/N0qzFi/4mEFQJJrtezY9fDCaYFCSsWdeuhRHu3AzgaMS4FqSo1mJSTNb8wkXvh2Tq+UhmsTuPrb0svl9LCGUq9IN9zrW5qcmCg04Pnq2rWFWIcppPZKUL9nNaSPIhBgoWry+XGRbSNZwv6yGOkQmGeKDO/klWi1yQ==,iv:tbv29QgTdUNXPUKPG09EsYT4VqvPtuXqINDuqy1ycdw=,tag:iagRs43x0gSGq+3htNnCvg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xhDswEgXwSNRgSSrh/7LmNSuGWkEj/xdv3AR66nXr0EF8sOOxjb3S3JAMFUdbsgwzB7LluGkej3jr2opPhTnP51O366PioImoaOSV+1BfM6sswaN74rS3hg3CuL7eyv9clYLdkQuhfusMFgzV6OVVkkEjONQGOz0vSfqZ6I2buOgrBLSZHp2ytWSWr7jJwe+TZzNBU2Mu+uUbcC1IS+1+Y2T6Lp9AwIfvsSJ,iv:RjaDDGualM4PtDL28ifzzLXxhLLvqilOFm0N7M0sG60=,tag:PIHatDF5qowR39c9fESThA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaWpFYkttY1NPaXNHQlla
            QmxFaS92L0RDNndKRFpXanNEYmg0dHhQTkJVCnNueWhSYm5OTlN6bVh4QmcwYm9P
            K1p4ZlphUGNFN3huTy84V3VrUHFYd2cKLS0tIHBneFBJUmk1OVNGK3V3NzcvWkhD
            QjhhUDE4UVhwWnJGNml6VnoxTnpMTnMKjgcWLGmCrsW4K7tssngUvnGStPkwcqIW
            iph20yeLPTKao9rzVYmMszSwWdKCVHep0AJ+YAHW+QcTI0S633MV0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T11:13:46Z"
    mac: ENC[AES256_GCM,data:aQfsYsbkHu9GX7Q0dLp/61vI0R455a6UKgUqdYxDu7ZrXUfWC0RfHtIt7zhh9w2ZYF3y/msfIFC/FXR06g8hPWR2fsyvEZBK4oQyTtuWaaNmn0ZOp7XKXPWsd0WAAyzijeqiqOXzp+ujwAo8UASiTF085g2lH+VX0c0g4oSs4PU=,iv:UEQfqn/BTs2zB16CeBaLyDs+8c2O0XyP0/AewzzHqEI=,tag:t/skQy+mDEFmGDzrwu8HDw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
