apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yoKa/ZMAR2/+i5sd3eY5PIGoG5YM8iJ4akcFgU4/Cf4FZOwi5OvR38v6QOT1WJOGw9PkiIXoukjfD4RpPg9YxTUXpp8JMTKf/K7Q+BjVIyy/PCrprHZ6mdv78ZEXMaUvHWXb0y1onXla948IEtcmFQcz4ZyZnZA0lwcN64T36Q91XwYVN7CrMFovgxVyhQgmA2//9EYkYjsd1y/aGg6AARxJMvCdHa/VTsdMJUBJc0tlVPtdP1HHNi1zSxv7ZWv1NUB1/RaawIFU3ZFs7isw0VP9F55QjFrIFUexf+RhCTsTZqVnNnclWg4h3LjUW9wuGJtaw3YTLCVJ66gtxJpzeNgTWhsZvznu9x7a1td4N0odNiTrFyCO/yv2PikP/D+Z,iv:OoJwVVXDX3fE70iC3HVD+B40GW/zY6xhcn/2SwW2Mjw=,tag:xrJH9InqFigP7P4Y2bXssw==,type:str]
    identity.pub: ENC[AES256_GCM,data:+GwmLBWYStdQCo0DwjQVNR+l+SOtlK4FfxBlYWYOi/kHV3Zw8taUs8igWE7P/Hdda6pKwiB2srnqVPh4gWhfdwDpB4TfCoh6i6LnG9fZmgHJgXaGgUPqMTJm9nxituDrjBjYxRH0kz3kPZ/1rtx4DWKhYJNcE4Q36iRj69G+n20rrL8FBt6e1TdZGBnCOeuB+OjbpbWITQKUJRpolIjx3Kshhr1Bm3/MaISOcvWHAu1I1cKMpjcXgOsRtlBpgfZ4ffvw2BERwQ43AqPllQ==,iv:xmZ+F9vRjyHsrzhfiEe/6BSFRDGWEWvoGuRWdy6JZDI=,tag:aYYBDCB09sjKyb86F65/xg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6MXt6566a8hY2m9+c20wZD5jo0Ym5GnpG0hEzG4JzvTakz6VERrnJZFWTmoxuGCX4rGlxGIZQjRpSgG2R74ypNORU4imhzp+XJj7H5I6/PLH4spdO0ZDzvN6UKnYLjcJV7MGX3aEFJG/qTaceRPBY7nylVnRQTUD3AeytwN/1dDvO03Xjf3q6MIf8piVm9b3lAjMzEcnOjNvZkmXNXfuhrMatIvLlhXp1+Gi,iv:5ExKUP1K2Vh8oiUZ/bTAHIQFNNudl3eh+xGMVcIqObo=,tag:/yVdERdELIQ0pa1Glkx6aA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTWRla2kvbXFaZktpOTJn
            cndIakkvb1hSbVFkRm5ndnNIUzBGejV6Q2tZCmtxOFRzbXcyOW8ySXA0Y3hUTkVJ
            R0xWeFpOOWlRMU9wakpJd08wcWRHb28KLS0tIFNxL0dEbDM3RWU2M3VYR3JkSU85
            MVhCNHZLejAzbDhZVXpZSEZ6dTJML2sKqARcaERcfgvl4pbH4rYK47YWq05fNmEc
            bs0yIgi97RjOBJ3qgrOQHiiAVjOx0sLJhN5bUw89n4a3VGZfPANWDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T21:20:09Z"
    mac: ENC[AES256_GCM,data:5DT3IgrwKFJjBiwD0SjW5pXOMalCOpJxZvSLX40pqpd2V/LkXruKD0jwJ8I3QtasNIdX8RBPI3AYfE0d/Uk41aZx0XDRePmSPiE4uBaDqj1HbZpfBhR7Juq3aCFcFyWHB8srgAYk58daej4AaCaCbl+WUAHl6nkhpQETyW8Tfeg=,iv:jjfOCbmEDA1CZVHo2v+AZ0YlcVgSFvOXpBstD9MmOSY=,tag:bFycXmExBw4xzZkC2hG8rw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
