apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:s0U/DwpZAZ1Fe+KlQmq9g97rJuAdmry1CeY10jGJFoLZV9rNlGubnZMjsT0d9vjbjIOZ+qn2HtgNT73GF6YQqJmqhPxnKCBtW/l9cCLfxKV3YvjispD8SiGjHTZ++dabe/c/0e2lsUk3kSoij+BB1f9HtBBaLcApYr0L9UmfhpktW930ouqQphRtyk5u/zIJYqiW1M/MRovaJ53lePLD2Y50BzLtWNkM97niwS7h6YVN1OGAcbBNa+pUgslJ196NMN/LpnbGjZ8EMD7shhZlccj6nS5IdeCzpfVbnvLos6GpC221YQL4PNZ3Cu+B50/I/SNdNCqUb56krco4k+Bx/esAMqzsBF+YcT4jH7MVipgwIPnkkWZ1YEDWnWiWtlnO,iv:ki4g9HSuvc7Ck37UYkiTml70q1d585e198cXsOIHTOY=,tag:zwf9l7vxOkkJInI0oA8NPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:2mJPOZk63dkuVAGCW0LqqZVAJJdlD023+C5FGpOz2+1BQVpZLeX1ZazSMuDsaYxn3ohFWc6/omoRtSiecE4e8Qk2BkD/ou5xG6TxdEBKcQKi+PMXFoF48qB8xWGkeCDpa8C38uzluIj1EmUpNE3R6gjUu0G9SmksKXbRA9jrO/5WqFXXu7egPuvDZuGJ68iKVHGjSb3CFlIDWzakFfHWHqu6CB73P5WK8yG/8fDbHjVjXp2c5yNMNgmw66ZrQqr3AH017ovO+vpNWAnhnQ==,iv:Bq2Un8vTHFUbKzpXSiZ4Ia4S/W6WalhxyvY6IgWr+2g=,tag:TufxVYWR19NC4emP4q+rWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lQM95Wmvr8i6A5yMM3M3jp3cxQR+2hxHTYBg615wuB4OX+0/+0FMHJUU8UeTYBkA4iBKHAwruUgbaVKGgYeo/x+EU/8buT5OQGOqa0gJAc9sasChiPppttyZqDQE1DluC8j3R29EfbQk8jOibCzINvG/6WWgHksIrV9IL13hUqzymRR4rrN7fRzD/YNJjomHRAF7PfvKG23HdJS+38ReyjQufcGJ4KOHGdpD,iv:mn/kjcEoBuFHtX3/94LUyQP4UMLuuEZ1C5so4pUDOgE=,tag:KXcw+JolxKyvvgWtFiS1Vw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbkNLYno4c21jUGEwRWtL
            TVRZYS9Cb2EwTC9jSGx1SVp5aVRtcHRKSGdZCnJzVzQ3Q0hVVndKSnJNRHJsM0Yx
            ZUM1bCtLK2xweFc0VWphQTYzNUFmQXcKLS0tIFM2WE45OE9XM2tFTHJSbzNJOVVK
            YkZQMWZGbEc3Tm4vbGN5VUVJbzErUFUK7DqUwlQYpPXYw4kcF/MzaHG7MlnfFpJV
            1l5xuRqbakAgILNdv0h0mR3iN1fq7YfYpPB5hUifzw2Ti5ztx6lAyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T06:11:19Z"
    mac: ENC[AES256_GCM,data:TidTyP9BLLDDYUIeD8ulFYjBj3KtU8pO85HTI8QJeFVS1R3NV7jZOhPf9BUgLBJQmbRF8pVX3QVzX93D28/pagxO93bStlTsl9qKjFyYbp/e4Z8Ri7Fyo0djf2krCYQ7UwcMul9pFh2QeptR1E/5tZeuo5eAUOU3soYDDN3V+7o=,iv:jsvcPKSdDZJj14HbGYFirvFIkGczOc2QW+LDehpwGFQ=,tag:BWVjnD23Q+4zsWR0mmsaDg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
