apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/QFT8onpsP7r80X8ZEEEMK0YC7Ub67jApp/8Wacd0vtky0xdloT7cnsDhMpUPr9GYJKA4GsbrK0mzfM26F9MehgjDzIcspLjv+WMe5GHQteK70c0I8S57mbbQEs+2ZQyoCbaIgcr5wrqZsX0IKNR0IwbpchghaakQIhuYupGpttx/DsiqRS0vic7zsX2uHs5kZOzSY1SrZkl4D+aqx1qzsWUbq08DkUqOMgzYLVul9qNff7gcg7EA2JkXgdm5M0n4/a8t48GN/kTAZXUE+T9Y12HyhuHID7kAYW4VpzhoDxvd2WMtSEFfCvAFZMZbjUEtjxePz2k/khUVk67j3zUR8hj1YroGlxqfKWfM/5LWXv2W68BJd9D753vjwEp4Dh6,iv:0NWbrgCG+4NXe66E4LodbdR1s+XfUTBR76HepOZUGys=,tag:5GUoYZgc/dx0jQhN7waUKQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:zA7myfh8IRUIebK7wP1jqhvA+Zf/wyZ805Uus7TlpIKmUNhfftoQirtgXUzZs3iOSDIQ/hbqbup6oBntFE5amEUCpxJbFuYxfZSmrmm6zL5FgffsXnnvALOvSb12wHOp15F4IXKzRsbMLDgRnCkspe1Wcw9aKG/cIVJPQuH9uJb6DR56LYHsMsgHJkyluA/ehZI+1yP+Lrrdz9icuc2t6ZkB077dRux/cbG9xj8HmJwoxxJMm2F08jECslG2Bp8yyzFL7GpbyEt6tP9cbg==,iv:IriYSqTHlGhYl+fxQhukqaiVpbgIXrIWKb/okwp3G2E=,tag:P66KZw/sfEQo+JeYx8hnQg==,type:str]
    known_hosts: ENC[AES256_GCM,data:pJEH71sCocWtmLEy2UDuDuAzz+hG3pypUkYjTi3kuRVQ5CeD4coNkvAON0Il0Dt4SDS9I/UtVvsrA/2i6cnZfrrFV+hijveZWcehz3O45yrFnH0Z6NNLH4U+Pp3pM+/xihCRjM08ZLEXoh+KrVtP0avLr2qkhsSU33/M7YeKAzZFQ1/prtDveWJ/D+D84bMkzoBZjsizjARfYkPKlJdVxYCjeeAmWhxKAp5n,iv:ZbEVyvgTrikv6J1C1sbaE7uUtxeesORqXvySa73ffCw=,tag:4PPWb3u9DvJzwXjv92Tw+g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNnR3NkRET1NiRHlOc2dS
            NHVWQW1lL1NJd2QrTFp1Ym1YS2dVVkRBTm1JCm5GS1hpdkFRMkErTldPYm40dGFB
            aDFVT3BtMTVSMVdwUGo3RVVrb1BZNE0KLS0tIHd4SUY5VW0yUU96RCtEdFdsaWlp
            Z2NYcVkzblhLbG0vbldYb0REMHVkYW8KIccuX9C/IAZWjLVvrs3dAdfeVap26tZg
            AOj8OO6PmLI4sj/vyctd1qeEFhJcmFuDBMyHYIuyP7uMqtnRUMiXGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T05:50:14Z"
    mac: ENC[AES256_GCM,data:pQHcP6Ftu5lhm2xHL1aAzCO0YxY1isuJTqFnQI03O6TEdS/btRtl5NQ6BKNtKI20viuQm47mUVqEeG0rHG7WBNHWIy8Ikg1RrdfNrcXOx95Kv7sYSzmzz1hHDoZbOYlTly7fUWK8m4JYixZMcMBhRMecVAapoVm0VSZ2tNi87VQ=,iv:THgeGWm96VYlkvrxdwtIAQrKuBnnl368wrStbwpCH5s=,tag:+3kh/k5/icZgJ1VKfbgJkw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
