apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+UyodIlhkobVNW65RwhC+RN8lIrAN6+kyGzd9VcIOyJ0jKAizjVrwW3SkYNA39ZXRBBn1naq5Tj354icC/DDn/VNXtrMyEro9RUA8wwP+OcF0+5EWIDz7kqLTAn4Efh1eHls01yDA2ZKMaNQGNu7UUi+z3V1AXGVyAJqcdZpY9IGiW8DovvRTw7I3dT8gutJEX87bK4ELPMKuaQg3LmLDxQszkHUDbvDcVmq11r6TPYbTC8MzQMz/DoJYsksJQr40HFrRVIoQmb8scbVNaDOdfbQrhwjZdc03Std2pTljLqG2L8FAchrE6fHZlK/ZqJw5IX7n387oNlBTQhY4gcypZLB5UfGKDmkQQ85bb3lENcRgfhSg7KROpzxAjMMshLN,iv:6qCcQWwEMSepe9RyoDEtIGxLfhhKxhtsDH/6fJDtPRw=,tag:ksu70g2+0LA2STSggGP2gA==,type:str]
    identity.pub: ENC[AES256_GCM,data:i/ix83MjG77wGH4j45T89XchCv/Al7Xq6pFN8gdEJH/fpTWPX5DCPpx8Qb1UAmI84pBsEF8VtCXVbAcxoMdQo2bpUx55hE+Wx7bEkCF1LGBpwCn0x8h8PTbSG0KHhpNfDSbunCi+oR3+UOXx0a2yifnm4WkgYTAP8C2N9pZ0M1NCjX6dZGB7fcm+jZw1F7bhUFpJL3wB1yN0l0NRy6OuOaRJIl7p8NLF5EXJeOGMRPwcNjnhfjjBbyyXbK1e0WinFZ+uAXb9xN2RjhgtVQ==,iv:6Ta4e7A6MZcpjBIjH+Z00j55QPyuk3cVSm8v1Xklbd0=,tag:hp05jnzutklg8+5P8BX0Kw==,type:str]
    known_hosts: ENC[AES256_GCM,data:vGttEMSbfAOlQzHnB96b8pf6DZQPeTzxli8vJeU+IzqBxivsiiwHKQHMUFNuHnYMuID9wsq8jJdIv7vpzsT73ejyHVvoDUImD/HZ5wPasKdxKZlme6yy9GEQop42Hkuw2b4EypWZTDye9fwm9ctp79z9EGpRDWPb++zHmv8/9klseeCvLq6KPPy5VrZ39EIKhWS62b3Cw2WjWBUCe/hXgtLS62jrU0YdXdKD,iv:y79hOXdz3gvhhFh4FcYFA4JFTnUjNN5eVFaKe97KkLk=,tag:eDVsZye86B8T/enQoqE9Mg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZFdOMDJnZzlEdVhYY1lQ
            VFF3QnlQcXdUMVRyTU4xN0t6YTk2aWRBNTJVCnB6UXlnTGtZbUNMYjU5bUZhbm9I
            UHhMY0p1ejEzS0JKcm1DYzc1bldJS2MKLS0tIGpWSjlaSTFadEowUllMN3BSdHEx
            dTVON1hhSTd1K0FwZXIxclNGR0Z6MFEKyjt0SfKyMhRG/XunwCkR5K4IUxm6R45s
            0IqLFsSN8nZvFEupSV3xNkWwowmcZZm3CsYUQS20DyNMDyyuDxbl4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T03:41:11Z"
    mac: ENC[AES256_GCM,data:Z/P1sV+1jvBvb3/xl7Ch3P6CIPmB7YvIK9O/WuhJ1sBsQd0oueBEtjTWWYh+vZdPUtL+ufeyKjTgqqEbs6QszwFianYPvYpWXaocEf3HsiK5F+N6LqQoXzKMyHW0PvqJwmjFZZv3l3ZSI5YzXbQvQ+pavxWvTkk/2pifieB+/CM=,iv:heGCc6FsDljmiaEAQTr9ESPqIE+YzsqWaxAoyjL/2Yk=,tag:RNdos+k3Hm/Lj6ni0kt12w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
