apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rtN9j6QjkZSnTzN+OH3gSNc2A32uAPlxLuZJYtSlwLyk2tq7jJBZ+1DlaPsiuLnikJTQJYEoPMBFBJ4P7ZPBjOAPnU3eRVDZiom21pUOuB7j1mImA9y16MqryS4xSlv/z5lGEWY1F/qRqMl8Z+6d2XILxMi5AZIOCF33pGAA3fkghEZSjmG2iJBm5hkeX1Zj4mmRvvQMiYvgq88E9l1IrkhxIWLRnG64Fk9DQ8g6P67UyQHtdFjxxqVJ0N47ooxNJYoqDLM6sEY1W4KrNhpC4Pi6Vm6moJ9Iktn/VdCWP5q0W8baB3SqexZr326IVyJNVMkZFUGaNgdAb1KrIY7xHuxe6qY29SFtwTk6w1M6ez4cmS9S5vk3jPzM7loDP4mu,iv:JZDrSnH3WNP+qiL76/INg7v/nxIPJiIToRlI/C6vl9s=,tag:cihFDtlKcpNbANRT415Jzg==,type:str]
    identity.pub: ENC[AES256_GCM,data:K/2ICVURAUdTjbrBNpJit9jQJ03Bv+r1jisfDPaL15oymwSuk+//Vmooi6lFs4dLW0M35gg15SggkxyYeWiJ1oIhVX7J1X7vsbzGO1zCQskvPrmQGyph6KgNGHoj2oIr5Py/B3lRRu8qKa/GJ+VmVnfUsWcNWvW3QqVqPKaPVaNF4fDza2h2GhLftwpf2/7HQw1gL650HZ9LgWGVta2reZvBtDhpEymDjn5CCXs0SnztvKyj8k36GL4ADPTqZFsYmjz/0TWNqNLrI6D/0g==,iv:pqCZNS8P9dAo+2yS8pvONYwN/7oOJLVOyznLJhTy/hc=,tag:ngqkXZ67OmfeKEy90fsoGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Q3mCct9TrUcEePvWsIxFJqL/mfZy4mL2RjBy8+TO+eNDyLZeRvQ8crPOwIhn5DBeaCnBvAD0v/7LE5xFGS1sWEwKYKb9S9bcraumljg24rKkwecpMDw89DECNfVcqKX00palmzY1l4dvxGhl2QlJy9R0H40YH5l7B//s3QVb7pPNRTxkmfEY+jo1ytZZRFZMBt5oLuo3wFoP4YcCcz4+2Pk8U0pch7AZ3F32,iv:q8z7uB+WJHxnElnVu6yfqqSIbjeZmxSBtchy0RHFSzg=,tag:Y8mMrFRbsHlXOFawfq7V3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbTNNMS9DYzdFMEpuUWto
            eVRpeHorNmxmMXUra0pBM01HVVFjemo4NDJjCjQ1eklLdlJVQ0d3VzlKWGpPMzlS
            Mm8zYVpDblhHUXMwSWJDOXNNRUxlblUKLS0tIFE3WG00Njc0cDNYSkxkMUhKdzdZ
            NS9rUHVEUmd6SjluV3c5dE1rQld0MzAK740molKW/JF7osiHcqj9VBwSFbKA2q8f
            xOJYmCAKHWu9IdEpD9wff1xgY+a9mpLWZqrVTQEhh8fdGrrt2z6N4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T06:09:25Z"
    mac: ENC[AES256_GCM,data:l/IUqUx8aKjjqCCQTDNWK7oRnks7ftGdoFwbPPjujJyZqIY7p0l1pzIfFD2OGVU2nAA4HoCC4IPrTgkZI6/FtLNDD54IIraMBUUrte3JR9+j45xJNgst+sTR5SJ2MxFlmvcXoXCAXsJ+scrc8HA87KWfbSA7IIC51nWz5/ypxMk=,iv:D3oPhr53kWzRx+mZOdMMoSs/dsKRdMyIKk1zeuxmhnA=,tag:UsKuoCVa3SMsSLsfTJvLRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
