apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tpr0ypBkhBUfGbHNG7nXm+hDEyZKxnbCZXHSRpVZ+DEiH/QHUjwCgcZDJfHXBg/rAoPIKonz0oe4NBs8CtEypTNJFeWiwlpwD8v3MUYSZ2YmoP6uI3mFDkfVV2lq8uR0aABeHXD5wVDW9VNuqarZrKqZJuc8WKTaEPV8szv2/PdEtcxCLlAWa+YUrxDpwEA9BgY19MHiz4IdMAqADFei9/e00qg/+TW9mBoUpJRmhRPHpHKdmQbiPmvTMRBX+7SCEe8snQ8yavDcrbFwKAuju8z7QSsY+Sl0oFZm2aJuP1C91J1I6oV20DgavIQjJmyZ+KxI0e3E5EYwJXIXuY7dMXJujOJ15bquzeCOEYT0Bjx8kDV41Z/Uz/SA2ekPMg5v,iv:SUSwmXilwDwm9kZEFsrIp6P7XG1nrdIRDmvKInwbxuk=,tag:P79j1vB01RC8k+SCKq9oQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:DTZjqUjSpMbzIiS7zJMis24cMXaTRs19oiAL9w4qV9ShjmM9YXa9R4qYUNyJ4ymUv7jBuFIDorKwo7bjgMX1SUI7m1TH9nahSyi6NfaOqnKHTTdX7INne97OK2heGbQwV4E9qvH4sbmeESlrgnMNNPnru9J07KmmW7xqEFDy06MXn6JvPtqdWqm8uZmkJSX6zAzKJ8jS5XdW7ISbqR+PFD/ruMqN68xiQkNYFkdk96IeyichEs7g4AfGT30TyUwcq21yerntu6HvTpUBDQ==,iv:LlMZdDi9z6vrkZr+bK77bTADXqDPL0oyQYx2a3uE2C8=,tag:2RhonA/O5WspkLTg1Mj5qA==,type:str]
    known_hosts: ENC[AES256_GCM,data:/4eixCiHSwB1CXWEGd3KEqN+CgI+qYBrUlj0mQPCV45vT5V5CCT7iWai6Q1JlaymyeAI2u3jy5v5B9WAWvDg9AH6g2I3OPih1cqKJlEsGscwhDZdbHaUSrUGk2B5gXD7ncC0gBnm25kb2sEXcRVv44rwNJqeGP6/wbSDzmUcRqbAb59N7jZsQ1M/k2dPLU3QsNObXEsPE6xfL0b4lGueUsZzKlJ5OQKKxs5B,iv:sd7SPGQvU5GGzIwcI+Z0MZTnDIh8/O3QBawhVw+SXY0=,tag:67jGM1ggk6CGUnd0sCVIHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ck85L1lnQzdIcG1FSHFu
            Ukc3OEd0bzdJR2xuMGJiNVNuQzlscTBaTUJrCjdJZ3NFdXh0MS82RUpJOVFzOXBs
            M0JucXZWcDVxdEF6R3Q1SVJUNEFGV1kKLS0tIHZnVHUrYXh4Z0lqcVg5SGxyRlBn
            UDBMWDlpVURMdnd6WmViMmNtNjJtbFkKwEjQIo9NKE6gYQIbetpwxaUcnCRlpld9
            ln1vjtXW5or9OH2xhPGI4sJMD4yidjAS1p7bCwE/40YqqvkkjHwmfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T03:26:57Z"
    mac: ENC[AES256_GCM,data:04/Hs+xaeQptc/Ai5l2NWH9WzVibTm3t5cGtWKnKHCCIQ2XaKafBtFpCWWNv2Nxy3nNuoZOsaPHMTGFiCFsNZOKWb1pNeG75wJA6RV+HwAfd+h3sD0tWdOz+99hTqBZFBrHYzdge/Go06AnPKHrvCiUmSwKwsl4EScHrTmvJDRk=,iv:rabeedNLqyNsi6Hg/OrSzObacrwiLn7C0JKAipCr4Is=,tag:Epk2NiIGzaN4jSIl0BpqdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
