apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nNqeTY4MGGM2zUONECizy6yvjn5CFgAc8IjHkO3oEi/c67a2vUrLJwFj4zVQmvWvfbzXd2h0AmAxaybVJoJ5uq+Lq0483wo2uEu4lfxr6uuZB2wdvwORGZt/lWFjdGiuApywkC0Irh3mtrYlPFCQoOHZG7N5+TAUs6io4V5WgflyNqoTfV4iYEavd1gBeYZ6nf8YeIO/nrPc+cZUMhUrM6QKJ1aT50nhUe8BUwIv6sXh10e1ZJgXRBCkDUzIbzD94y+wtLzedk6SRBAUQUH2I8xKaT3dvX//ASir7CHXBTIuJQib5f5TkLVDP0xXCNkyoMS/+eUEhCKwWWS36kI70Ox13WmGF/ljP49Ls2IKRx0gBPUiKD+iQoRmFig9lxeu,iv:VLBBSiwTy6BTkk3pukX2MHyIQCGiD8AgYYjKaF/YYSc=,tag:lqlTz1qYGUUwiqeyf4goJg==,type:str]
    identity.pub: ENC[AES256_GCM,data:w5dzBDy6EmWl4UIUu1MIhuMIDqg/WlbmHJjMb1TQ3jOpOZaKUOo51Hjv93Gt3mCPTF32PbRwR6m8Ty5Dpa3NKhAliKkKziV0AFGbatrOF108OYdQn52jp5NxT2QG2rYRLZ/ZpIgbb/lXeAe9cNcv5JkFZWA2qTlFehc387ItxecM6nhz5Sk/vIURXOU74F0QUzwES0DNaW7wZYD18/3iW19UcVAafBcNZ92UlqDV3/TObxlelc5shw12hhoaU/WQwfsgDgwsh+GECHvwEQ==,iv:0iZDkbYxG1b194Z2gBEBfsGO9/bMki8ETC2AGaQvAnk=,tag:zbyLf0TatJj1K4A2rKqgkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:NxCASQOMlfIDdX/qWeKN6O7zzYsr4umAtKJHpRkfS4RGEMlLjlxV0ne9h50NBDtti6Yl52qTGzmEnvz8/ju08gMpkKZqH8nqV0Obs+I75qdlcv7faBUe2VNVtSqu/L/7uctIuus61isO2JNmEs3gDQZM5utq7gZSDcrOEGjaKD9rSxR9upAWidndZ1Lc5gbqb+85/CyHwvugmkiALKohE1dnHVQ/vJ2/LHh0,iv:4qTQJ4fX+HMXJlsoEI+RReAtbk7sIGdUlyrxMMU6Nbw=,tag:wJ4BnoSu0x6/PNRBLaQUbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV1FiV3A3UWlIWGoxNkhD
            cTNtTGNHZHU1OWltZkdGRCtoY0lTV2pIZG0wClVubzYwc1IycHJmeFdGTTYzTE1z
            ei9ZbkR5K2tpYlJOMGp4akxISWpudTAKLS0tIEQvQ0pPbjZ0YmFvYzYyL1BwVVhy
            Qk0wZmNMT25WTm5Ta0t6YlJQcmcwMU0KXIt/ReE7Ju3yWfiH8iOl2w6T0NvyVI8X
            ZFZ301C9wRXyCcuZ3nDB274uJHwyqisMwqq0yBpSiUIz3nK5pm31Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T08:08:19Z"
    mac: ENC[AES256_GCM,data:aweO9ubfsn4Ho9U2afAa72Z1uY3GwmPMqD22evgriMOZvDe8pXaL0NGCeOEAmJGNuLSSmqKpLAbt36/AGZd0rsnkFz+G+zKf1NeyrP5IEqs4NL70FTFK6YgqkgGGC3t0yRrmVTCj/xxxVnwilZBZd3VpmMwXpPwMYGzYVyZeZr0=,iv:fgwPDVshH4TMR0EX2fn+wDOa6JmjXKYcEuynm+HSqe4=,tag:KBHOztLDXmUAd8QaxqYSow==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
