apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5WK3AjAjMcYDit7yG8eMg4fnFKz8znne3ZDKtxbbZ8pJuxdzpO5cwr4MeIS01KFTdbVG9/9Zgf4Ybsq6CgIAnt09hyM+SVPvnZJ+yzgK1TWYwLROGMFoPHf1B5UDe3qn7Mkz1bRWNLxo8n+N5IIIdHMazS4ZSsfyssq2sqY1n9aXGnZ++CNkYg7535n2EZVka4MHDHYSmHo87ww+82OdDYDH+vEkcQNbhVskNHwdNlOgJqZU05UA1xwtxh37ts4T8Bh9KXmeez1P+oos8E1cKqpJXgH3ZMUhM0pHNHKK+hHKkqIjgsdT56nX8EKtnfChE3pQ1NUSjMQ6m38g1/ImTnj4eTt2Fl0nSbg4NEQt/pI4G93WTeAGDMdOOXza/wlN,iv:VxKSOH6mG1sX+AAsSmQ5UfpUA/eiYd1FWDqgMW8VbQc=,tag:darCyPtfYic8Zt09eEo8vg==,type:str]
    identity.pub: ENC[AES256_GCM,data:2qPijKpj0NZt8hOtdcYe35WwYGAsGfzNx5RQI4IeIFnu/Rr7kbKPpsCeG38tbPUhZIFVTBThYIjIQI1YrQdcHXkIsXW7OsQJ4y5Qp0FLgmUTXa/ErIEyfCXuNJFdkV7YZdjgSIKPW+SdE8vzxPbV+ecUXIrtqQHmKKRCO4DrIs5om6v2756DNEUUdfaGmnXefMNprVYlJIqLGg29z0navPoeO1P6buzhryLQYmi7sWdSXjy86z8BaW1/11b7v5Akzvcs6dV7f7CNO2mlkg==,iv:cUU4iRZs1jZEl1IHRzbC1AnVVXjcWQNcwhqnVZsdwTQ=,tag:P6TmxGcBPHL0HpU4/FBShA==,type:str]
    known_hosts: ENC[AES256_GCM,data:CzdRBrWuGCtXIh1L+5b1p6q9Iuekz0AQUvbqyJp7+FQyfQao3DOZbO9OcbOKyBrXDEy3ugIzutH/Qlrad62AglxYeBA7DTiI5WrbldYPrrLB5WUqZ8u5KoPUe8SsLXA0FfKMeXF8VF51M4SaL5I9tgjzDDwNiJGJm/mQQpIw/DnHpTAp2EpngtqYqrypWKIeEVWr+4VxcyI4QaKnAVzUqpNaRlSq0GCu2slH,iv:3Sm0Dduag8WZz0I2QWzDvsz7pn9UaDxT9kJ9Oas9QdQ=,tag:zNmgZ85fjce0be0a2zGIuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTkl5QWk1RmwyaVowZTg0
            TXhhWUhtcFA0UTJLanoxVitVU2dpTDAwNkJ3CkYvN2swZWh3cUxzYkVYZDA0bE1m
            cHowbjRPWlJRZGc2aXZ2TzBEY3RpUk0KLS0tIHZrUnNzcG5ka2RNTU5Sdk5HRjU3
            WWFQWGZ0aWx1OE0zUE1SY3VydFd3WGsKAEnSKN3f8UvvjPJzJrYN3h6bpyW7Hgut
            gHoiKWx0B1LJZ/9fSFLsdQxKBl2fi/QufzrMYNcKkDX0dn8l3rAEUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T02:14:52Z"
    mac: ENC[AES256_GCM,data:c9Rm2lmY3P5pGiqFoS0grD7M9qjD7+h7TU70HSujKUItMyHJQejjh7vjAf6/xBmmJzAnXtOZO87DdqzvKgOu/1Hpkh0bXnvyUsLaPc0c8BLryzWMOSWdddKths8eSprm+tNgIXgxQKZsNyxCOAhIbWAV4KiikQZDpjdAWIklYSs=,iv:FBExoMlklj71c7+5buWZ2cuHNwbx3D9q1aQxNVAqQhE=,tag:+0jOWCh/asZka6/UzRkPLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
