apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4zo68BEbT6e22bDTSWERkWyAQNEhd8OnhYJUdUNXV3e5R4V3asr1RitABTmo4Wo0WQlawnWctufwXfQd0w6obJHf8aMKRl+WpltcKwUbAlYOxdl8kVzW6+tTHyL54SfdXHRxB/QIqVjXHck2nNuCaXxgcB1dU7zS4zZXOca6Gmdx6+Az7rTlLS9DPVM8negDcyzbJ0C5w2tB8s1/xj/V6cjJ4CwAXNAGCNTZQGQC6ALdg02pX8jh1uLD6oeUj4ZkCEPq3rfryQulQ06qQeQ9KTwTSi6/z/6TtNrghYoPXJAGtb021UmFENNm+ZJxvHaxsPPyt6NV9c0ecPK5sClzi+vm3HxG0/O5whroFxD5qdC7Zu1qkVcwKjw8GBwZYpPM,iv:v1zQ7AcDkNwwkWvNFyAajCOWszH+BiwFo/zXGlFrOiQ=,tag:4JdY1pk5CzVA16vxi3Gjxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:34yUMKYZz0lxWK9cUf8Lkv0MVgW5s0CjRE5baZbXFvTmi9ynNa5CDtlipIoyxUbk2iqxtgX4KGYE95WPz0ZxQhdhcruK4ijMClqbQVfNo6JvzMC9ZyYaNvny7YxQZ2hw4QwfC7dymL0VmVYkQCMd2ejmwrbLGRYnPi9UrNe3l+sWvdD3sbCapwspu2rO8r8m/2R5Ibw8b5Rv9ngipapSANw0qmpVC/orxRwUITyjf22itQnIxyzkkVicIJOVLDyhLOEvXfT0mQ/kQXmIXw==,iv:MiIm08HgjVLi6BSOqqYO6f+iq8ThJG1MAra5QJ1ij90=,tag:5iZY1xWTcnRNWPTc5scqNw==,type:str]
    known_hosts: ENC[AES256_GCM,data:djuZYkcv/+f9VnoyrrZG9n5qsq+vVrFyIswSRlH1G7Fut3yVtWxQNh2MQaRehQZ+kW88BwDFd0ayC524yVwih6WGUquJzh7Tm5PFPSFTzDtpZdrlk0L5eSi4damm3FfbWvueXP5DOO95JOzDIufthYSRmgdD6HqutNuL3Ny5p7x6o3pvnffvepqsRsWWrgewRcwqr8bg/GEGlfZKPaZ4zuWCq5XZH+3kLYRN,iv:etES6lWPAhPsr+lPpNcvgmmiY6MSIgnKMXLPJOw/tRw=,tag:RW3agCCMrpTU8ZcU0h3b+A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaWs4d2ZSdGkyT09ZeTRi
            UGg5YXR0dWYwbjk1aFQvQnIzcHNyOE1wU3lRCkZTeUhKSHNHQi9DYm1hNzk0OW44
            UFp6WTI4SG1wdWNyMlY5SC9mMTVTejAKLS0tIFVwdFQxVEFtaEJYZDUyVXVweWE3
            MlpRSkcySnEzSVhnYmRyODVDY1dwQjQKhwL6C7K4fQG7OGEXJnGWMyIJAdspsElH
            MWz/QZxNNiKBiHTt/W1c1HKiTj8QuUpg/xs9t9vrWw3MGUqrUcPPwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T03:24:44Z"
    mac: ENC[AES256_GCM,data:CYESRZxWGplHNWSQpm4utksLhoGD9ZqSbf19BI1/cXainkO0LlwEjnE4kBMJw8/diX9XM+YKr2QwKLIXcabh443zXd12EQHJcBvMFQyz14hVm5rRO5geyFUea/kAbjgNtkpNibSNPgGYUIJjOz2YNeNvn85kJEaRsOEN+lM8jSU=,iv:HKalIRtnXE9SiBDo3rpCP2NfI/OxH5hkDwRn4M0prRk=,tag:c8U9E2DKxF64MruBaE93Iw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
