apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ut5uJsFLdhbHD/saPHn9vN8AgzaEAvWxhHvJ0VDp6967hACMRajsIk5FUHp99a96zumWLwKmnTdKbS/9evYfYfm8axHstUFylCyi091liCtMPGkL85VAmc+e9sHgy+zzI0baz3/6ozDtNBlXrD/YmS5VelcmDZ6Y1aPepLRpP5+Q01GRqQuTw4f8oaD0GTXKSlJzax5+CPiIoRi8gtX+Mr3vFmgrLjsM9wevSuvgw5yWD2RudZ5MtQHA9YadWuXkDy7cgBEJCoimV8ZxciJzBktrfikXA9NvDwctgNwt1v0ZtPs9qbYVSNFOy0GltoDvWJCUYdtleJ9Sp8PG0Y08UUTLEI6g+54CaFOCGesqiaAfTVemR/R7o2TI2CYOOiNc,iv:jHNtFcOa7R/ZLyXdXZ9gKjS2vCOcR88d1E57eospVrU=,tag:SnpLQM5RHno6MThCzoBrVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:71ejT8srWwjUyECIxu8nwk+sLH/sQ8FPUnE+dhUFzhHN4Fn3PQ3nw90/yvl0ocXYihXcQjS4yBT0LO4ZGB6xgA72+A+fO6Pj1I19Gh5BqD0Xp28zQm5Gx26nI53Cn5hzSYso1q/0H2OBuMSdxPxJifihtaaSIbf3LveX1fT+ypEioK/9jgX6k4ztox4IezG/jfWP/PZewS4XuZWJ5hU6etO/mQ5Ry9acsCnddR35XsmvxxF9mgXFGoG8R1YwY9notLvYtIClYH+GdLWwhA==,iv:IGN5q2GvlCmcIf6en/vImvWL0m3Rvnck6rxaIh4jPGI=,tag:MiT1fzARHdgu1H0jjeVpGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:DZD26F9ZEyHs4L5V1NipTXDjleV0DUhHhTzZD5Nmko7LHyVLhbU5cPATIVf3iFf56AaoYar+PupIS3pHyV7vXPkZmeLuq9LPN56XYiZpRHaUwiMyuut5fRu7gd0VRLQ/zwpJ/k/6ArmC16JYE9pbaZpW8zufEi3bqSlhgN/GFCWXMDkZFk8V4TX81vDdQZWOuspHIHzf5YXi6ntrxz7pzG5Mf6TAZUcjJRz3,iv:rc3nMzidagnWt2XZW52DIjGKtCL5uZ4ZA5p6gQDSKJ4=,tag:xcbXxagn0EPWcOh2LNOugQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERmdIRWFYQ0ZMSVBKNzVa
            TmZIZnhPRFBuL0V4RHlDeWUya0oxYWZHZzBrClNNZVh3S2VlOXpQcjNsaHd1OG1D
            ejUwNzd1L2NOVTRFalBhZWt1L0gxdG8KLS0tIGljcUJXckZHOWU5L3Y2czlSUXpt
            WVlUWDR1UlpsVzF5Y2JEWHRrT0t5SmMKkE/siZWS/lFdA0kZdivso3piM5bmoVOK
            vWSFEoQAtYxdn4ylHJn27L+W14lVXwLsqWaUA1pRW+HS0sy+KUpzTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T10:33:57Z"
    mac: ENC[AES256_GCM,data:x2BMNb98mqhdXZQFh6nB5TZ4dz/C9dgsW8HpWjiiEH6TH0IcjkQMXQcnh7pIqhWa4vieZzlORLmV4E3e0w/izKYs2zAyBlw/jEB1MMs4lij6Hgmz/5zCRQVyxJiT9oEFA+nBQFzhDOP5n+beXawEfbC9p3SiOhYsKjXYnr0VLn4=,iv:w68dQP0E6Tjfl+/MOJEKYAhVvBbaJYuurhvz0jVe7ZQ=,tag:liPNFKicBPjNZiCq7IAdFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
