apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZEavdlGucplst69ALxrHBINPtLgCzWyae+Mwi20hOsLjv1ZKIt3ny6ym2FxV0cEnZ1r7NzX/sHOAW2aitWTIgKnhqHe4FBDtV7rkivBdoUxlcp9/9ia48rHtJnUSTCoPJNkubU91wJwH1Vg0wUaqdwBot4YY49ysUsPJyN8Hdd5hDticmxmcQlTchwVX3KTl7bhHRpkNhP+Kv8HS0G2E9F5Ok/Wj3RCgwm8mhQBvcFaqN2kegEOlUZ517oNseRmleswsRLZKF57P4Zu8JwE/xClemW3t7jn/068+zBmSykiFivhAjt67i66AGgYsNoBD3NY+OwRNBYO3OGRc9RmdGTOmVlPpjvV6DtRcDlX1xUfOraWpgpIrcIgZ7K6V3QwU,iv:gQ8odHpln6CK3iMnnOvXUlCoDLROVDUfbchq0ierccA=,tag:ggCJtxfGkrNsfalg3lWFOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:M8XCfCfucqukjM6N7gBNzpsZ8G2B+y7DI1GnAcEpJphs5tDe+gIenrfebrZpPFlPrVLb0Cxgl3FVPO7ir7G52G8M+ihypccOe4ReiiYIqV1fuh4FPz2XXSSWqkYCd5pSd05/Ha+hHucZ6iQMD1EqrtyL0IMyknJa52HPTDpvVxW1LXxnd1l/m/w9UonRIpiO7gMMQCaWWMlzySnkp3G5XYOKIVRN/lxxqRBkkjnc54egkzPaZfGQ2+94cuSTy4ba/k+nS1b/GEV6Clfdlw==,iv:g1/gkJ/7IAVjV6xJbkBqIFQrWmtXX7w8bXsN8XBhKEg=,tag:TmOkMGp42eTOzbaKwyvC7w==,type:str]
    known_hosts: ENC[AES256_GCM,data:yzTAtnZ8iQT1MIzqetOR7ajsJTTyHNifzNOb7Zve54TGU6rOHOQ6a7Mx0A4YgwW0sjT/7Xvxxi/T26R4xI2enKUwhCroc8vdmvXjO5SCBm2HjnQ0bzvHKqq6TlOMO3f5QKSq3tXqQ5Q1JCQGnv/QnoA+HsuTcBg8oFegkL7BAcVhs56h8EmVm8DPCxp1ZRD2QpwI0yYnkNwXTSIWXDDE9jwLBFAa6PXcbd9N,iv:AFegLq9QGlxWd3lYPDXfLIgG126ZpwSbdCuh9dMtx9M=,tag:Fbg8JAyJ0KLyYwenEUWBPQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SFVyK2lsRm1EQitNeEIx
            RUJZQ1NVZmF4Z0dLNTkrUHE2WlNFVTFxdEc0CjNOd1ZhdE1IWkVYMHI0SVVyc3dp
            ZWN4NUZLMHR5d1k0YitQclJpZlVNQzAKLS0tIFI3em92bXFaWWR6aW9jRUZYUnNG
            ai84SWhCem1vMnlCZ1IwdldkWXFnVFkKs1htk1hZ1YkbIlEod3TKKrAvyc4/Z19U
            tVGlwMKk5P66tx5v5ifzJ46idSHNCoMESFSCqUls31oxDR+U8wGeSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T04:28:12Z"
    mac: ENC[AES256_GCM,data:pkvcuxQEltpkvy7BhbrvAGmujTUdWua2t78AI8oexjtDDzjv0jJA8l+m6vHxdSfqZ4IFkjy67Kw+8iTbuR4KYZQsHuBBKgTO64CJnivUJhly2ox2LePSp8VJfPEmWFs9E8OYgsZIVml2b5GpB39uy5SdHMIciYEfvypnNaqz/Io=,iv:1AM9AxgTJ6QSNIycMAfHdPi21l5d92BpN8rpruiAEqo=,tag:VZWJ5UYY0KhW2yn/plw9cA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
