apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hlA8CuqWX7YfR99nnD6Pn3w5P4TwPRdiOYh2OjaqUhimSFgCt0+cTuJvQTaXLOFTgR3wCw6X9JMcd1ndghNdOTKgkHcTOBCsWerNSq2fKVLEKSQUlR1aSV81RPCM02ZpVMuGmqy0To5647ghJo3yhv0HMPuC2igDp17DGjSuL4lRFFkFaf/q/AMXMPRWCbUP8m2BwUZ/EvdsRhlfml2ZliXv7CAt4s7ys0M9Uy7W4YR0xhPRwt1+n/ClZMUsxOeuYiA+a3vJxU8SuWsLkNdzY4eCjVS7Hs9Zce09QZpvXTlMbyGzIGQLNlVLzcaO1auPGF0wffOFiUgLSXzOfsYgwt6c2PkU2B9ypVqmBn8z4W4QsM+PvVZjtIBiPIEJ1syj,iv:LOHCsbUaxPqJYw6qNZlzfLXQt16TdUDPQQ2ZY7l3HHk=,tag:tv/BHRx6t1jO4iBGiJnYcA==,type:str]
    identity.pub: ENC[AES256_GCM,data:SKJEz2L04KhDZJynRsAf4lafqef8DMb28F+J3dXG3ANwLY3U9jCTpszyfU35HZEv3mbwERMTS/g9sxn1XjyYTpXdFSz5v3QVx+QAp2jFtXnkmU+YdYM1euFr4Ie9hq++V+x2T32x1S+togTMVUkDQTQ7/FL14JSGIDtVmGI/SaVpveocqKSyt+7t9DYrQ4qeCCwA7Iy+I4f5Up+ZHiRdqmy2HlF2x2w5UdhTw/Ti0CpLsVwR+t9AdnotFf6tFwH9SIQgkxjvThPIsayPNA==,iv:cGowBOjHP1B9HoHiyQCzXj2MoH8aLBeg9fTICRcTVKg=,tag:72rtDn6Nna4kZ/AOyZcLig==,type:str]
    known_hosts: ENC[AES256_GCM,data:8/iL38Dtxxx3XXSxxFAwD+9rfmC343c0Mo1hp38TeJFMkWCnrTgswrJNV8U+ztHGW1DfxCfXisO6l9R+pumgLx1J2q9xlPwrDpscYtOeUcHbmKXRApsiYzBSMAsk+ML5qbqGpB/+qr3T6RK353CS1IlgxIJ1akDxVwxHFq/YHHXu95oeyi/TRTLWNUfp9DtFift06tBjL6KFY/s6ya0H7MLqf87igkctHqSR,iv:K8qNH9/ZWXaQ9bOjf9suYUdFTzzIymqgFYmAWTVOCCQ=,tag:TJYbCPGJNfE8egdSpXWomw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMkk4OGJTQW9XcmMzRUFR
            dU5UYnpNQ0pMWE9salBsZ0pIcnBJYjdDRlU0CkhBaGxCc2tIVEYxTkNZZUU4WVh3
            NGM0TVJjMEx1dk0zMFdyZ0Zib3hOWmcKLS0tIFZZK3dNaUtTL2VKazdlQnlQNkxO
            eThOY2M4TXBjNjYwMGZ4dExFa1ZpZG8K7CvyOfeGZ4ar92IwOzqcsOus+7ry56ib
            kX/t+Qo1jnr8FOJ5mO9V85PSK9sdpjjcaftRwyspRpTEqTX+KO4iUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T23:13:34Z"
    mac: ENC[AES256_GCM,data:UQODARcs1BUgDST9qoB8ut+4/7rQf9eEldeeajK0Bd6sBsjKWPBuS/3besg44dZTIkX4igqxHKiZGS0jFesozZLUdKQrtIHIRrZtK+bB2wSlILx18AEgvy9f9Z0/jhZtir5jhT1YHRaBdPuc+etna3cIC8WLwg1DdC4vMXYZ9mM=,iv:jca3YEOYR6UJNTqnl+v2bjBPZQwNCCu6cymI9EXRjAY=,tag:5sYn5DrOdEO2PFJk3/VExA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
