apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oe625HrgsXL4DOwnQPD1XGo3rYr0J7ha6O0o43VvGW5AessZ9Wy+tn191lQd8mNOj5R3XdmdxGYz8dSYqkKJZN2qWEvN9h31g5d53FJ0kz6oTBUrKoybXgbxnwHj84R/hB7ZnHet4ReiiSHqScREd9/IlTLx2clC44PywkXL6h6H+Kt3x3nKFI6c9BIzRZMjLMF3RghveY8hsA8NHF2f262cA3Fgfsp5DuE9rqyC9xo8HwgFf0oxHO67fMoGVoe8O2mJiYBsgr3xaQ/CvtYwXCDO7wCNydZmGBXBmVgxWsNcAoj86vFOLfJquJVJ1Fn6kROpzkS3/Gp5HVSIwiGhOCE9eaW9gDI+APL/WVP9ovACm/rkXptp1D1chP4Aql3M,iv:B9r3jv5RNwsjALP9ecYyh4/qs1H1NPEfzmxvS4YLRWA=,tag:XzDOrQ4WZXqdKPzJ53kzVg==,type:str]
    identity.pub: ENC[AES256_GCM,data:T3kmqGl4CB8515Pa2NkI1uiiWXr89HpuaZQC4PpB6PqetZsX2hMkMA+d3+3RyTrf/RdCVwURkOxju0ko5iR6yPop8C9qLntUX3QwtiqibWXJli3XAi5eBQjlvjcVzFnuO5wna64Y/saCDnHLxv8/WjCXHRzq049YBp6MLtrUFKjpzDRjDcwC6GoZCuV7ItKGjFFsu/YbaXc/WtifYxJPDzEQdIZHpiThSYvI1qbp5pWn+qlRuoAW0u1sIN1TZQ812wSI7le2EKSDPAMSPQ==,iv:T5foDRiOCz4vgQxxUOuBcqdXjC45k8yGwe3CeImiIb4=,tag:aQVTMygp39sIa/9kRijpwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yxvSoBM6adMRqBMKsZoNkwOKj2WYrefoH8xh+COkmnnXEJGvTGWA/LRUyN4351RTlojiFWuUZJ2e4pjHDBujv1z2+pGXi88ZXgjvUpkisyBlgKDepSOEfc+ji42LaZ5z6QwqnWoalZtZlwFNqqxBzenKd0aHIv4RiI+QoJlj9Q1D3v1DEiSNoqEQIb1SAagdCkluy4MB9gNQQ6lKL8uh9wKVqzGxYBAV9thd,iv:QYp6lNuAp56XIvHMJL1n4YNiSSz5PbxNExKNodzJimw=,tag:YD6+BRVQTPVvx6AnlRdKZg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Ti9yRFBnem5VYXhHSjJi
            OWl1WTNlcGlIUStyZDZkWVNXM0tLazlrT2tJCm94UnF3WDVQbEFWUVNucGZLdWNB
            R2QrNWpUMGU4SERvdDhTcDQ2bTVZNmcKLS0tIHhIVU1xMVdJd0FDaE9xaWFKMFIr
            RHA5WXd5VmFieHNUNU9EWllHaTdzQTgKTnDnyiogq6ZmY1rqDp32bwP/g9F47TLg
            x6ZdHptgDhkKjStl82BDn7+eQMYJrbbty/Q3QcZjUm0vQRV+jvzxrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T00:18:29Z"
    mac: ENC[AES256_GCM,data:E2Z8tXskpUuvx81mTmJGCDrz1R770EJEmhWGn+cUmuk0m1AAroRgr9m8v5+m1a6e0kJ8e3UDiM23BRWNk214HPeZRERowDqeO1xG4DQRkMmd0d0gnwrq/ef7Opn/6rX5BGWEOojX/G7T6SgKkns5VbuostT/VOtOptJKOkPaVnE=,iv:6YXXjCLUIfc6i4SDmlH6SRsNtKqNDRSyfNSevWBy/nQ=,tag:qtSKw85c5Wm2+lji1XhDtQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
