apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WrxG0UwAB/+JH2eYFwONfcF1hHwAxBYLCSo1BzEz34fv1jL66aGCWH+aWu0mgP8TZ85lRAzXRNvK43Q/Fyx5/hT8ZhLiABTNIX0ZLo4BTHNEsodMfYQMCxKrbZLuSls3hi1Dnj7l738IlJYiNenffJ01lSrDku9r3t1C/d+KXw9Hd9fdWU674e+RtiCvoez0KbnYpQ6mrErtrfrCeiXzJT5O1ca8kt7Zmb5jukK3eAuaOKQ3Nu0678a1TksYz4d9ElDUtnZA07U6Bb1e87JYflg6Ddi4MOSMxwn1RcjEVFRHWpVixfcmcmJKrEgsrjVwCri2to3zQuigmZJGJF7asISOzlerPYW7NiQfBDpz+mRLmIrIDEKL8Jk8o+c+ZHmc,iv:yL4dN93SyVCGR0rEsuaTxTQijxjVxBxBF3XeIwfCDCg=,tag:BAxTvefZkV53sWYo83t7bQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:VxgE+afJU03LYcnYrQ0iaj377veSBp5dxvg9NmmVKTNdoq2Tahtk7kcpt5LTvpNUS/gvAQ4epzO4A0mKR77O5iyUEiLMjKq8ZHn9V5OyJy+62Y9pdOW/sqXk019p8Sxns72ilPFFxeX9f82cSBPCYIww5Lg8na+abewOK4U8daXfDMy/UPUTRZVfcSojqoLfr/ausgMXxQ1R4GK6INzI/5rtoavKLxYN/1kdgqGEeVHBqcm5be0H2ocg6niLFZHIYHmJyua1qDftsBEBHA==,iv:dLcU/JuHqKnhHvN/RF6p0p+TN0I9uTrp1eKYQmLDNrs=,tag:T/b/f8DX6zZyy4tfpWiQkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:udd1VBjEarGYPTEFtHGwhnRQsj3MOHYdfkWtdNpXuUEcOiFn4OxV6iWtT8m6qaoWIGyWTmwzPaWU5S+yNGqMxxPd5O/P8wP4bjiKvicCVZYPMxNs5T+M1R3+lpSOakQldMjUF29fSSnVfoQUs/n3QPm91WvJ380iknZFZ3WOasVcLELK6HWw2kpOMFbaVhP1GWzFQjOZgYfcxCfUhqQmqN31s3m3h4W+6WAV,iv:Ya9AMQd7KNxEZgZmuMyFmvSTL+USphnbtU+5pehJq2U=,tag:OBrtk4Z3ScD5FMdJhiY5YQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvY1Z1bGlCWXVaQklHSlBj
            MDF1SzAzQytvVEpkQUZmNllaZElTRTdNU1V3CnZzWTNJQWxFYnZTN01QMkhubGZV
            MjUvUEJ0bUFVamFZSmo2dnhxdXFJcUEKLS0tIFU2K0w1RUZrTGtJcXM2bzY5YUgw
            OSszRlFJRzh3SktwZDlIWFBYZVZsUm8KcLk3JTlHmRmamu2ffr3G0mnPrKCZPCR3
            czhr6E9qfKT+lLkfQzGj4a+GttwNZDGJRRbDvvbdboAotL8oPiVrXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T21:29:07Z"
    mac: ENC[AES256_GCM,data:LsEgdtnuQvF9vB2UtyQMOIDZD3N+kY/lggt3jUKF4zn2pqP/zOoqS/SV32GQ90X0g8OVs/PI0JMKAeim7Tr1Dnv8+aA17/4SI87XhWeiMGF9KX2anUP6LYSAtFKmRDd39PeHvkFERj9fI3BaWx8Hyv7VaLDtTm2YQIERduvMqd0=,iv:JA8cQ0+SVTS2Ytghg8Xu7EoV3A8u9hWr9y7FDIDMKQw=,tag:rLRTWEzbTYbv7rSSzJgkpQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
