apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oTrhWxadiLc1lbSrhnF+Yxev98p/uk6zgm6xmozBYyMrjzApKDjrL8omkabDZI3e2618Bvhu1mocYToNEVd/VaVVc5XFUe/jNPtZtOIAlVpzJS/W+OsAQ8m7WEEcd8A0q6dBLEq6SWKdlIoFYFCEPYfiilpjDLPhH6sYTBU6o/USvkYLVb2rXkIoCA5i001RuzonTbDXDLk4Dg4bVS4LSekjjgI9nW1e9w0oTMtAjMbfB4Dph4b9ZY/PdbBShyBs+Lw4oCgnhIdw4kkTKtBuNajfXQc3Hb/yHJBNkzV4rMwJX6ypLdUmfccf8NsbG9KZ7Jj0xn05jnsIgJY2tIJBlnitq9p8xpTqiRYWZBI5Ft8h7BkII2NFet+diPDg6qKM,iv:NCxmpo/fwrKz05f7NGv4ySy66PtPtyxToS0my4lZMvY=,tag:NIwQUOioNEpj8tHOO4RgHQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:fued4N9u+UuWXMz40LIUdMCAxs4R7lKtk96mhCyRMQE1GXACBYyoHlZVgkNKSjsbDM9DDbtpbISudgtbp6c9gSF2J6HUk3gGsvgHH2lj+fikTympyNWntvzut7Xb+/wxSbr4DHgZmm5DhOnIQXqjGF7AECgTN5IEu5D6kO/NwrL2q5QFB4IpNE4RZ+RyAwLPk2A5aOr+j726aBjewStO0rVvVZOshWtjwlUMPHqKy+NzteAV6Vs83PhiVctmA+mivqHP19l3C9ae/p2Igg==,iv:T8lGcvExw4X25KUQhCBppDY3zQs5dIHBTzV5rXiqxlU=,tag:7hXjfemXyqL5T426LWi0Ew==,type:str]
    known_hosts: ENC[AES256_GCM,data:9RqRuqMD+vX7ArHFk9yIS6Jf8Hu46oGvPEv0iuRRZ/189AMdQVvAuXItUaTBPqRWm4mrvYwIhZRnnbpegS23doiLl9YWURMRJ+a5JZcTzCOzLJnFFbshrgdEqSwmZ+EsKka74obvwZ9lYwUTiU6xAkJPNaPDy2WR8t48squy362iE97mkVwPqUUFeD/i6rUmrvaETZrjX33jPcNUw3WS3DanLF7Yy5otxL8N,iv:PBSXEoeVDu9srTQFf1LsRfE3k+fM8/kGNz3Wan6+IQQ=,tag:w+2Jzg6oHkoLXE4MFnacTA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZ2JQMzFXelMvRk5PaUdL
            cUtvbDJFNHRmakpKeVdzUmM0WUlNZ1NFWUZvClQ3N2RBa1FrQVBEb29QMW0yZnlv
            d05QTjNpVURnemtDdEdXTitZT2NmcUkKLS0tIHNlWTY0TXdCWUtJUmxySTgwdjhS
            VmJVU1ZreGMwazYrWEF5bmNXaXNNR00KkJE1En2J2RWhrxYv4+EbAsrYQPcqd8QP
            Z6YGNU+CYSeHMDZUxgjeY7F5RDMr4FqKhVyYaVBhvqFEGirvN0E8KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T04:27:55Z"
    mac: ENC[AES256_GCM,data:ld4juN5p5OLYjr7ZYCNdX9peXXnEGOrQD53+uApxX9VnU904yzZcQdjAJ25ORjd9HUfUiFnsKvvXBuLCMinJHSyjgbs1JEGIucTyH9YfNAEMFrQbusb/i+dKJ4hj3Rsl5k1V+FGTcED48ZS2rViPH8gifJcmQSIv8rDbuYDJSLc=,iv:daphkMH0ov/O4sdL8+s/Nywar3L/MOBai91WQ7gH/p4=,tag:sCHw9q3o+4VeRHV4hposPQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
