apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uXEvE4CqWwGz/3vB7jK8AtTri3GhIRwUOtOAfUEu3MqWCx9Z/QKOsPZR0zLT8K3ZWWX5Rgp5ykoHoaXjlaJRo6ds8nAKEmRjR+Jx1LpeHydDMnVddPXd3B5Dx2lyNIxIpOK4aI0Sn8RE35hjXNvg38PJH8Km+LrEP859NjiD/EesiAXYH5g25eIoBkC+eOC6EUqRqS5c7lT9lNCyJEs/SWAbwtxTv7p2tBRsU6Cg1gv89OF5UWj/o0t12+bglcNwFeXMBDOHpvLRnuGcyCCyj/YM3TvBazJJgfno58vq8I/Xe8Sjhlt8nYwV7PfTFFLc2tulySbqGqNMlGLrYNytKrfpXTv9GFBFZ5aB1/gtptfnQ7rm9nx8X8NrXuDSs21V,iv:xSJhci2S3QKGl8DgiCM4O/LUNYvlq4lq+6bOiofqRaE=,tag:q3CnZMsGfRrljy32G53P/Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:KTGoNwMXIQqPGds9P/VjoQrHwH4s1+nSMo66Jjga6oSLP/4BfCPiAPEjO0g3Gs6wJIQ5j59p051LWYHfIKJoqyEZfWamvAo5m1ahv79+mwS1Fz31F0zweYzVG0sOMFUuH6Upkz7yMIKvAe5lS4fjHcSGdT+dmrtg8Xn+kaZh0//fl9bCDQqV2fNHOKGwH4F/7E9Lvw6SNT+zRhoyVP5Owfx13mv6zLXw1Ef27Ru4fKUuqASknXEoYHch665eJ42WQHbwJ3qOYFX1SaxjRg==,iv:quNb4FBQL56k6pbfo78hjJZAAhi89Dih6ggjK7DGZF4=,tag:TIbEX69IR5AsQ6eRRjMQ1Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:XVjr2dh43bGWvSr1/zxtCGGiHYhsgmiWp2sNToYWBI4HoQaHzWlnOD7mx7T0mT9vHPAgnDiIKQeB7O6RXwuDHoWPSiKnqOMXxTzgxDKu4tKNV7SaNKyzcjspoZst6TsZuTyZCgaJVyg4UKeWx1725CKRcm0z0nA4YezleYUtJtFwc8zJN/FGJAyEjpZbwumBehOdEZ7Ayo6xKmNkkqb72rzhjvC8MCqxrIzR,iv:RgvCF2LUZa/lzK9n0v7v6GunIZkWNXJXgaEwtp9uAUo=,tag:loggYzH/gp7IKI5+AtH1dA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON0hLLzhYaERYeUt6VUNW
            aDB3TjcxQWo0d0pIcjFlN1ZDSzlibVluOGlZCkdEb2lrNUUvMVhtc1ZtVm40Q0Fa
            U0daUzkxZ2tIcTFCbytaY21KZ2R2WFUKLS0tIGtlTWJmTndyOUxobi93Q1lVWkpu
            UUwyMW05bVVaQ3hrbjVqQ0dWZE1sK0EKa/+9fWcEzkp0pE0Gf+4liqcqNhutcQmh
            CcjZMCoXtUGM3SA+KB7RyWuR5+gnlyQGlw6hGRbcYnkQA3bzgKC3kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T04:41:59Z"
    mac: ENC[AES256_GCM,data:vZ5GTPWkDXRGW75jRvslQDjuaods4ck9lUVK32YRbE3EdezzK71eUVPUa6W/7HpH6kK8b6JUs+wPaBVx/eMLZxYOzrGd+oWd9wReqvH2vqiSDteHH64L/5L8+806Irc/vDvHhMSddOnJz2C4qDiXjv2fwpe2yq1sIB2IR61/khE=,iv:LsjElPWzio2lmmjv+GRGfezWSazB7r4LiWIVJZWjwqM=,tag:4sfnET+7YONvyROzlK1tgg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
