apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DwBtABRE9JEkYqR18IiFoAABqAi425rAB5WEnRRYaxi1pxNr74HtiRdjO/YLKQyF3KfmYuflZRhvKRSvTktPZ6LkMZBiLWmXdAaEnTvDUrn8hASE/+RQOtxCkXWAehH/xXzXU1C0kAsBtDM6mUO+UjM96gpH1kydXRjuTPQDnfmOlAZ+q7sFF8yaPY8LDiDa8UW7uRxKjMlILOcrkNrRq9z1+Lzn3vTlGRVOypmhlznkQyFH18ueMamVSqmVxgCi1yCAWx8hReEXxGBKZBp+GTPLXm1VUjDaLTG3uRakTriqCt4TZS/zOV9+dQ7U9Xrf2SxPTiiv7w5+Ig5yVDDjeT73xfQimCA2lXv1XTJXSRX87CcpXSvxXrA/fnw5prd2,iv:7rJgjw7c69RQb9a+1jPn8fcFGYborZJFRSLxXdn/rGo=,tag:3CrbE/Fdlwujk1+54OBVQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:j5OOV+TDcDLOMkvu1GVHNM8LsPrZ6+yPxkWwzmqAPWdObTxApHi9mewAY8TgD2g7ARDT4ImONC9xkC3QCG2CyS3L57VFpMEYWk8NKO7qPHMhWF3q2bmBs56MdBlZzBCJ9w3ZWGNRoBv42sA2CH1l5CHTYSbpyBe9E+mo89xId7SEg+5WB8MJUGUgi9F/NlO4U4AWIKKQWXmW5O9TWgmM2OWjl/AVFh4mA4LaEWwpYtwwBrk7Qr2PyM+kjQLRLt37RPxDWgHsOiB5VEDJdw==,iv:OtU31+QLpTDYEzjYimgpIcDVQhWRLv0iu2TbegMEurw=,tag:Nl2lYT9qzfCK0KAharnsXQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:8HLqc3xmjClDTnxRl2P9nfJ30SOA67zVcXBBGLl1njYGRcDUS16sOh4VFREPAKGvwM2ssbRRy+gVSGnAZ0d+WvKATX7DsOZz937aqjn5x3H/Bi0G1IyyYXKUXkrQNAfKL/YdLxdZDTX3D2tleN+v/UZDUHyFOjDccnK0DCfJHq8gRsErucvU/SmgfKYCprAoVTfmWeRPmakzRWQSqC8Ha3ymGLG7Aag7cKL4,iv:YekWPkdW/qOHwt3M/xVJTM1pAEzY5Oo1KFcjGkaVK8Q=,tag:Plw9piCLBgu3n6H354IExQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MUtFWDFxVWhPZWxSK2pa
            bkozUVlaT0I3ZCtuRG5HeFAwS0g3WGZJWlVNCndsQldjUEZNa2FRUzdMN2p6SC9C
            V2g2TXltTERjdkdEYkF6R3BDWEl4WUUKLS0tIDl6MnR2elF1ZUtmd2JSMTRKb2FL
            T0xBN2tQQmErZWMxdkdxdzlqT01iRjQKFy7qnAF1kfks8D6y01qavvIC2qCFGm8H
            2ORu/8uAxjXoUBlvCbmVw6zIU/6xQSyQGwj5RLPhWACIrr7OcX9rlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T08:17:54Z"
    mac: ENC[AES256_GCM,data:NMGRldFWZcKk2YQDoObURW26UBLW1i6q79/Dd3DiyJPtLlo94hc474s1/roxoFcbxcQblK16rYexv6vEXtrFk0+20lzeMccIF9hmVMgriFgGwF//bVuZcut7E2RG0pLTl6tSiDUOXLzKiwB+UhtCqH8By6zP8TAydVOMeS/HyCk=,iv:qrOwSQWO4c5NaK+VTj2HlnKbYUqcqcXjipENV5r3wTM=,tag:rVKdBoFPfIszatEA8iF7UA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
