apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OyzUzBrNfx6if+nrv0f4joRNvv35W14G4TY550KZxv0hcUfM7nUd2vmA851UU74NrdGIypjPXIUVmI+pLLOMDbRGv/wBqqTqdlbu6q0sATCgwk8GplH7GmXxEAB481Wqp45UQ2S3cPDBjNkNxvDSybcOBcVXPOtvp6h5cd25T+3mKmoEKhznYflIuDkKVUgpkfc8eJnT19pkIB1Ye4TsOEg27sJBAWWPkyHv1OIoGR/CePETy5BPP6IOPkwgf6R3+ixPFU48y7IMItNo3gca31gPVWq6dKeOX1lyzpjAjjcci/XZmc/3Iv83XYWsKKREe6OcJGsYSXPShQdh4MnKjTzGBi1lp9OpHVn9GCS1LEp1uQrJkGkKKWriGlISdf/D,iv:0tyLydYCGBHH6CmV5LwDg3pI/hjvGX3nB0T8bUQ+rOQ=,tag:Q/fjPMgJIeDKzepaCB+OpA==,type:str]
    identity.pub: ENC[AES256_GCM,data:fx8kIQW7jf5mjazGJuAlLJWYy2/07bEhkjcQ38nWIxk4taBBYRseAyO/u0R1PGOADn+ps/X+KIpJQa4Dh//b6ObnhmO00Lx01dHmyhAVXavUxsVDOUZfibN1YwXqITu/Nr/LMd24o8lqC9UgIQCGRLZXD/KmFqKgQmUt9yVMRSoixuju6PO+v5NNwlvphV8zcKqpKMiNDLDkdiivFYyTDGtxarWVgnuZG76WVTqMs5txJ6PfA0zGPo3KGP5/1pxeN1m0F0y1iQzu/CTJOg==,iv:1vfEY/3syGhqU22VfQ3u3Bpouwgj4xtq13qxmloM1uA=,tag:wuhZEZTZCvGrks8uoTTtjg==,type:str]
    known_hosts: ENC[AES256_GCM,data:T4Oio3oXaMUdBFHsPCykYPtiFxJK5JytX5b4px9ymd6DiUB5KgZ1wEYtJlkpN5cF2FJsIfJA4Qj9+azgKGklWi+5sbWI+YGIM1EoIFeX9ZfRB4iqnlr4conXjiZfqxfnxeUXOJg0nUY7DU8ZcB8tcjX2ws+FC0RK8VXOu12gXvZpKYazRwQ8mpR7awW99eWe7zjh3/2pHa6pm1luBByJXprVtPedhVZ6+Oc3,iv:APjMKwr9hLUcYowfKaaTcJj4NLYjf3n5oFN1KL/8e1Q=,tag:yZ7qjg1rw0nWgTqhJnUnHw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZUZYU3kwc3lPODYwV0ZK
            TFRLMzJSS2s1Z2d6UmtMN1gvRXVlOWQwa21NCnlUL2cwcmlyK1VEQlBIZnJFWmx4
            NWY0YmdneUJQSDJNQnBSZUZUSEJueW8KLS0tIG5uS1k2OWxhQnBhTEZvYjZmcm44
            SnVrd3FSSFY3Mk9JUGFLTmJFemYreW8K4WaX22QDgua362TBhtODfUQWsIC8FcBG
            Ti5GyODtBOu1uDEJcT8e3uBcZZZludZd+moFUmS2T8AGMQUHI1H5AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T21:48:13Z"
    mac: ENC[AES256_GCM,data:rPP4pgQ+pRCvvFzZS+y0Rjf167GQiJZLdp3gF6mu4jZis3cTXwx4nYUN6KwsBrVKuZcnWUZDEaSTlrLWlFr6rBhJGIJIGf1JkrgkbyRJc/IHRKdnpWRkM3QzdwI82yl52DHKgA+0+moJhJhHiXznZXFBRQj7788Yy1yaIHh7Bt8=,iv:u4uZb6K3dj4Qmmymx+1uouqfIDM+/SXmaN7q4JqNNY4=,tag:Xh7Lny64ZhT8baqbYiKHlg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
