apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cSVqApXN26vZO2JArrNEvYn04Kwrp+bnyGvk5wmS6KKmNPh9/Mf8I5GjEZwRynxPtDuBy8FlAabEG3pAoQLMtWOmh4P7dNNzeBCB28ptcwtsbCBQATSDkdXfcpjyhmx9SHURR5B1yRtbsTaYaz4Rq6Xk0ceE/Y7VPQV02ZzkXkwZ3Al6CCoxCGZ42lsAlSBCoLv9e+Om/SEjcY6YH0+JcljPVnxRp5k5RbnDQBn1//uXvAuFYCFSwTngkauaU1r9emDV+dTKGFFdzm24Jw7v6WhT9uXxlUaWtpzsHHjUmSODbZ2sl9QEw7g0ZB9OovOEYmGE21Z1yVB/RipyfTq3aykWoL9HOz1Bx41X8gwC3JFqSO7nBbHNiviJKo0wsc0A,iv:+4FGw6q9jz2d8oI86ixGgFB0/5Lu9QvkpnJU9NQnd0s=,tag:KD1I/1xvIPl0jVTOIfxwmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:MEgjDwl5VqVAZyrbF7ZV7AkDxSxHjmx+P6ajpXEQZigulJmdZkWR/ycDFxvIoTMIyXdR9I9mmXmAxnF2uKnAvfsPVwOWKQSYoZMP6mf0OLoya+iU4Gydh1IJtN3aXiDA+rMWdpMilYs7uN/7RTfXvmpbwhsyIyIu7tLhZ3SFSUGcP6ZwYGhDHwy8p6JfqPhp8rI07iaGszN8bLeULw32zeMvS3ApFKSQQUoBveOTFMTuPwymrCX9x0i/v8azm/fZ0Ycq/PTebdMnxgUwiQ==,iv:plZ3VcpqH2/Lab7jvASOfiybbH2QsoWA2YfTe2AUbps=,tag:fdSK8unBtX1+ZO5rM+geTQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:fILMcqJFpr+bQA9Er0YMe+2xVig9ysWQFQ8oiZQe3WRq//ybXtbp3/swbJtj/lfkKRKm5kti1NEARDdkSrcktzw8jOoJkp7spr2W2I7vL4e4LQsRw6E5TzNiaVtH/AWJoKhuUTWsi/ku5Pnr3i3voJIKZTRubTTIxOTnFlen3H2DIAEQbMc8AdjMXrNd+Fq7+ma1+t2540R40+daaECo1tUZ2YaWaawlv8H0,iv:Kab4wLiY4JmCqolHyywQvFniUQHTD9it7pZsbHzrUJo=,tag:sp1OyscHMAnO2+lVrgSaoA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFam14bjNlRHJneUlLc0VG
            SFpiMkxMSVJOZWNlU1dXcng2akhEYis0ZHpJCnVLME9yVHJpVmQxS01tMHJxdHdY
            UWJuWG53dk84ZEZnOWltMFdQaXhIU28KLS0tIDlkZG5WYVp5QWZkd21ZVTI2MlZa
            VjNMbzVqdkFFSkJUTWZqdENSdjVic3MKVfIyQEiWRe2Pkzb4DS7T9ozLfksBsQFp
            G1a6pynsKv5ILHj9HRDU3TNiwBO3cTxRjbvfdT4bC1qcIUyyV7z3wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T23:11:05Z"
    mac: ENC[AES256_GCM,data:muUAbwq1USTdABcuDSJ9n/6rhvvIHrLWOEMcCMHEl3df2K8zi9DLMeL6Z6JpncbqOYhk2sj6TxCu5SZBIuezh4sfJgkT7B19Xs9GwTE5WX7DQXu79NoZaYq6Lnkqi+QqyV2OnSPDoC10zQvrbHNyfrBbliT7AUSgG1sCttiVxbY=,iv:kBbe8kx6yo2ZjdLzsPsXbX7LurmmU8b4Fo3LgU/6Rn4=,tag:SryEVgIBwzlWDEm1eLfclA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
