apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EACW5sdRsicPRLa+sSBA5tjBu+HtLoAJMXnEE9raqFZJ4UCAACuQTIUoYtwHTpnKlRHDhPLkuG81A02mTaAaPtU6c+L0+x7EyXoqKP5WAV+Q1HOP6xBoXYDlLf+p0J844P2fW6xivOQ2/JaGZjupOQEXTdKXcPDG17w2Dm7nfz6iPCFcnvYXDRGx98E5PXPBVDQa5BGgL0/7jpbBmzm2oEs2s+ggJy4uvej4REDCTeMh3t06NmSFZZwfMV+0giAvIKO6wmh1QP0j/VRCCHubn7vK/fhpNSL/Oa4W5aFwmeGvG8NTasRcc82P0o+aj1ON7lqmo6OT/1re+DXVpjz7Prc622IOzUuYR3JlOCNaPY5xLguBniLdtk1jHUnPZ++h,iv:qnwfmaM0I5LHUSWEjeNoNaarKxuYrktT/JZuOALOLGM=,tag:buwMu+N3LxupYoWc6Zfqjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:R+qitkMhjV2ztPmt+DQ33ChownmgusX2LnHqnitwXR0b7rDHyS8azjhSBFlPGX4/AvzQBVPiKR9Ba/3TbEPCZZ9l6VrILEm3PVvVNZaE/7djUH4N1C6m6rQkUgwu0k8KNd8yR17bH6OQ5gv5lZayXJAmU9ud3Iab9EIDzd2ZFEaEjzobjyNZ/BpuH7bgto9REGqWEQbYw5/g3a/txREl01g0NbM58lI8X7nnxiqoMZXIUbeN+QX2a1YQJDrsbYxS1/DPy1w3N92+mb3WJQ==,iv:eEYCxUmNMHSpqCWTbz9k9wgXhmXiVSo9P+2ZDNVblCE=,tag:iHfg6VcN8piYlaZ+43F0Pg==,type:str]
    known_hosts: ENC[AES256_GCM,data:+Wof2Xn3J2BaPc2VKIk9Sg7lPFQ5DIXK9+oyQLNv3JDOc8UqRfQrOIQ1+y6Ko89Tvh/KfsaOU5RZg8LMegGGEJsjBruXmI6XvbRf7ss91sVe0JtaQHoj+EskJnjvlBOJMxI8Iinv8WaXJnZKx0b/Je0CiunQkxsSKqZGR5EeDZAxr6pZHzRtF0gAedBMbssjfDm5zC35KQhnmCHY966DK0WgjpfFQrm2Y7uW,iv:sG5o76bDmqdUn2S2R8FJyBp3zAeRu6NwqpuIV8NnqjM=,tag:l1YjHxTccX0iSgLADIPjGA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU05zcVRkT3lsbitMQWpy
            TVRMUHFSQkl3SmQ2OGZmbUd2NlRKSFBxRUhJCnF3N3BsOUUvVitWWm5vL1J6V09q
            dXh0QVZmN0VQSWVnZ1RseTgvam9nYUUKLS0tIHNaSVpGcEEyaElyUkxKa2RQMjgr
            aUpOZzk5bDZFMmp6amhyM2RCaHI2aFEKbkQp3DuupTi0OV9f+v6IQ0u8Eu8flUCE
            JjIebe5IOwau+Q1ii1wO4EmZ3u4ZDf/c/CaeJykJmiNnjERQUOiF6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T00:30:45Z"
    mac: ENC[AES256_GCM,data:+kvs0YULRqz2NCuj0RYvtD/v+A8VXzVMF6wP3PP3WKQh2KW5YNGlc/puSuHxjWzith5Uel7umPd1XI5Yc5EQ3xBkNnnVQftvY+j5exheFKUIQYSxqo1vUML+PcGHVD+AeLuE73BhKfrCSE9nIM6z1IT7hCzdkOYPV8QD77Wj+Bg=,iv:CUYLuhPthmLLsRtWaHNPNvQ28oBGwA94QdQhkyWjcao=,tag:yLahhkzy7CnHy8u5tRAWcw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
