apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lfKmrof63kSUqCnloGhaXR/lpQaDCxSsO7k8qlu5sil9s0Z2Z/bsMMI61GZ57QxhNB2Ct/IYv+lRhOowiUvJI6QUlaPJlz318YSP+b0WrOLy8m39oLLfFYRtdVqYVo/UdLTkEapJYXPZfgoNG/qm8WsyHrAEgYORGcM8NlNi8h1TvwDdIo3eeNIjr1A1LAlTztn1Fv5hcf23QQd8SjIgBSZGYnwhRSeVdDcyD7IirA+ZkotFqywUjSN3lU3KrmCAAJKu5dMFXuShzUGSX/wOycEr+WGxhL/JOlIyX59n3QQGmkpP6CM9KRsPWl29XN7qVWmiRrhShL9qXJ2NlpPPh4Grc7HxwCkx80ZzJwr2nO0FlrXGuidDNu5vG07UfeDG,iv:o7BH28Ii095XB9GnLnUlJfge/0RCnnFeKLLx0vPhCV8=,tag:Fifo8ZiJO/JjT0F1XB28iw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Eb9nXCo92uvPIk/hEn0Jssp3ZPQMPIxllmw/MySSZ3iyGcHsu9S/lcG/EU2OU4anu4P0/z7KyZjvUm+8pYir6l75k3xM+pU6Vj1my7gP/jQMZHDss2vHMZoEu/wOCRjyayxlYG3cW3s2EOJgq7WJEXCg3O94lwxyc7cjg7w7OpLwM9UqPdL9yfsome6woR5JZXB4rTZ+nI6H4dE9NhZROYqOp76bG5l7sG2X1Q2M2a+V/gHnqnZWd3TEgYzqIDSOfuTTuOjZl7D/6tXLeA==,iv:IUTeVarZyFmmJOSt330ncTDFpq6RgllJqNNmuCZnnOU=,tag:IlPMSAZTx9LlFW1OJJjK3g==,type:str]
    known_hosts: ENC[AES256_GCM,data:+BGV8HMPU/ljh53JRB/tvQWpdkpGWIVGGrPebAkjieSm6KXGZ96ehO/f7SaM/tajqvySro9ptV36iL84ofIreYr9VgisEoXZEI2VMTb9XOA127IOGVUqhkikUhuFYaLTby5LbuOiOBFM2PdTRttaAVyuQ8j/MGAVS6T5UOSZOyqNP/DpMpyaht5sAcpLjZ3kUwxixJy8yT/PEyTM++1W0STAF8bSgVWNqLMB,iv:V1V4yN1T6DgaYKMU2pP+L8bqgPBKrNLjA21ajYxgNlI=,tag:YAi7IBA2APmdR2AE6hZIBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WkRRK1FKdDBITWdFekUr
            c0pCWW1NdjRhT3BpT0grT2xHT2xHNWx0MVNrCmd5NkpTaHJMdXZBNE5mbWFhNVMw
            SnozYy9ET1REcGpibk9RMzd2M0M5VWsKLS0tIEJuU1RIbjE5MzdMQzNiRmFrQTdq
            YWh3TXFYei9zMVluK3RsN0FHYXN5SmMKPoM1o9dz7YX/JbDnPD5amGvzMJfHpMjm
            TJScOOx7MEYUdLdOmgzG36k00OWslEXTkdbbmpeQ/lIWP6WPjDOAqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T20:37:19Z"
    mac: ENC[AES256_GCM,data:LGoMTdQ8niRMdp/RiOOTzfyV+yNGkCm1hnDBt1UKVsbVUQIBc02Wv2D4P/9ZarWwV4e5664Mum5mYTNL3+RIucw2gTWEfT5u6RsMUDRGO/LkiU80iQG0Zrmb/p2oSl3OpflgHm+hvihTpOK3+eHScQDf1nXcXALpav6x/VwPWtk=,iv:6tA8XuAMMSVyyQ3WDBDU+dp3/qpDjBUEPPr/2Gs/jWo=,tag:ZsoIJuVYLl/6OhL0OF7yRw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
