apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:M5yQIDZLyTJqroHn5pCoRo4scUFk+xjdStZC/vvB9B8+RYZ6NPTc/Sj46Ni6tfSpbJpy57Q9OC9fftcPaxieGob3MLGDJKqSwWR7wngU2HlZC8rNegTGS9BvZqlenWvWKiY8lumZZSCnEWvqO0tEkpTKBaPlRsGgh2m3S8Vl5ce9aWS6HHshvGOXfgvZr8IghvyKQX41nlhiUfm4aWfhznvNTcdvg0aQEXwxCUy5X7wP+zQsQ5vpma7tTzLpsn2lzb48FWAy0D/TDW5cCp0aJtSp+r/Xfgfeu95G6/P8UbguOdK9U1ugSwyaE0fAS/CHqVVPhUqg34XcyTGwM+N45T709D+VhE0qMlegsRRIiZ4yNHLdIevVuGeFzjRLC/xo,iv:aBd/JJgSeTiuPLYzozbf3k+Ik12ZNcuxoJ8FcB+BvX4=,tag:nOub5wsGgbwhaTFxyEA2pQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Xmd5/45HcCLr2gEAMQFIrlBSGrnMYBBoyVyUvZy2dAW70fBhIE56xXt13MEeGL3ii5aChV5et9Nc018f6opzNb7aFcT7k5fQCS1s15H46IG6v68vF/OEBCn4+FcRjTvSATU0h6idPKuPhL1eg+emaXZ5EDUFTDpIFs5Yp6FFr95BDIDHFdV2U6npbNNwT6jW7y/jMVWM2nEupeZsVgHoyuJt9SIeYmFFl96Jc6x5INBVTAUtcOjV5FPz2rt2c6sUtLB+ji0LIjCk8YJk/A==,iv:mdyFcT6OxvpOsjd9gLvktlIeqIzNLDUnoT8hRGfFUQI=,tag:8Agiegh8fF40N2hE4oMjGA==,type:str]
    known_hosts: ENC[AES256_GCM,data:N2xkAjSeVtEYzdzqzCADGo9rlt5ZOCyBX3rm/vDG2ycXp4d1ZXxQiKfCJYig37Xd9ISh48pYfP2vIoVbClK85BYrMwSdWzViCEQrh6W3owomBNmGt4rTokVBkDjDt91KEg43vd3W0KmMbkLb7gmFTIf7Ht7Ff3CKK3N2dvXFOVRFVE6MJu0QJ91spUNNt6rwPjI/jCqjsE298mPqApgnCUGP5kYJcEty2ay8,iv:XSxai8CneS988Yk6UZnIiHirPzem+PYcq1gRrZ/UK4w=,tag:EBn7FXzxb8bQlOYoLuh19A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRFFXZmJRTHhLZmZkMmJ1
            V25PcEpWWEJpNkI2elFTVktFcWRLSWtRY2lJCmNzMmZhRWpEWjVxaExEVDlLemsr
            RTB0WGhEL2tHMjU1ZlEwcytXOGQ3b28KLS0tIEczTlR6RGZCVmtwU3hMVnpkTGVK
            c2NHMkhad2J1cjU2RWZVVGdlRFF1UjQKQMlsl6hcg0IdOqaPHeskBk7/sNVE/JI5
            Alg+X298AyMiJuk6N4cTnb5fNoAla6bNJFrujYH4jSnxG0FxPq+L4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T23:00:23Z"
    mac: ENC[AES256_GCM,data:0IWhyZU7Aw3NVYycPy/3WrokNcvIlxQQ9oOuwKtOb4xxGBbKX0iFQFFV09NeHCB/zvcNLpr2qUP+I6Inufzc8kvkDYNVt9ijMTIK0bhKZBsDG20bLUAGEEcR9FSt0Rt9UYNUO1xKtnMpZiaf5REwegQV9J1PjqxwkxL/6QeN4cQ=,iv:UrHR6a/tAIeAG5dCCMW9cDrPIQ5nGIGxwzUkex8q27s=,tag:4nLNJGU8B9WWYC8tAg8dfg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
