apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:brVcAlxiw1fK0mv+6MtPOSY6cXNd6DIcK/ps5qJUOpu59cAuyx0lcWb5ntFJj5GQohYrqSBFh1Tj20wqApsAr1vEx/HGzx6QAWSFoxr6YmJal+RURsXx6ZLR1+DOj8bI88is7kQEqFQAI2k7dFDdyv4kq/3ZeWQ+z3hfTCbMpuoXYUuK6HAVXj6QP6y7BFTohJ6uOsTk9zYvi8U55Dq6APDaixm+DYhZZCF+izDN/yH0fEdiIAbz9U4dhdAdyy5Sd7OGhE0Qb9US7ztta7uDfS+ExSEDuHZ5NtH1H/+KaMZhSFGDbQ/qXizRDuNeqFaLxyeQemf3wf6yF24IDVHNFcV9o9HxwHBCXlMpLAMHp8gVh37sX9ZIBGL6dgZL1Lvh,iv:OgS9JWyq5LmPFAxt+6kc0hM8FVMUMPpUqVqcNQcxX8o=,tag:dqaevDvEVkatCYPKTTO96w==,type:str]
    identity.pub: ENC[AES256_GCM,data:6vgWkXCoGN8v+HDSOVPD9lbT6xeC+vnN8Goj5zb/ZAjELbEV2pRcUEk9XeLFSjOArP+Y9TZmweuW4k1KaBIe66H13FYG3KC541PF5Po67H9fPmFjn2dsL6DCg42SZ/DRSrZm2MZGieDwMHKy04oxZvk8vo1SZnTlnTEcYmxrdxDDlFWjnOvhEM1z7XuqUQmwe2dGb+GfU8r1ofnBKIqWd4vmCWXsBmGSJE1BkJJzmdMAKbtqT64OSDkMYofh9rj0FsOKvlveX/iU2edYTg==,iv:IuiZQvTj3qg1dBL/OiFO5hh4l6gsrcYsS3YdstSNdVg=,tag:zKuryHtC4A5O3IAogNZ9pA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yg6+M0+bY1Oou/U17h5GwAfelh4YPM/lB9JnVHzvlobPKyMqW2Y/vkrXNGffAwCVXCs9t7NvUolIx5otVU279ReumR6T8TUqFfZFq896Srf8ZVHwO2GoIVju4tj3MCyjS44e8Q8SbAqSmkrlkhqFnpGeH62AhmNHSAVlMRbY1iGH4kxLh90MYyQ90170lWdhG67+5KUlNy+/iC8UaFwJbqLN4VDmmm1w3gMP,iv:Af0jCphqssCuNhUlZlY2NfADbXI9sZgd8Xz4ITelhDQ=,tag:PPYCds3Belx/FAfc/WaQBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRjltYi9YRjEzaStkaDZz
            SEJYdmtGQzhoc0RJVC9HakRFYnROY0pTNEIwClg1M0tQYTFhVnJwV2J1ZVJsaWZS
            Wm5lNUx6SkwxTzdTYVk1bVBsQkJlYlEKLS0tIFpGeGFEZG0zLzlQZjFic1JxQnYz
            clJtdWw3cFAzZlArRVhHOGhYS1JaWncKSywx2mGu/YQh4PYNPM/vvQ6L5UZmiPHi
            Yt8BBQUZHBhkegFRgea5t1bbTEP/KuCQQCOoE+xbZqwLlrP8NBxbRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T22:42:11Z"
    mac: ENC[AES256_GCM,data:Ne7gU8BVnbWcTrZs9Kb749sE7oghkDNXcGoZ5E2ZniSzIGnhSS4zQGBixZBjWlxi/d56NUuncHxqmn1JbyASnxuz4SWErDvtLgbyNqaBngCTRNJDl/9wzZ088Tsqfr/1OufGiHju85NKFzwleMO1H4kq/+7FzHz8HcIysVA6M7w=,iv:nc363WNXKfY4rKa3Uo2g8LKWyZa+NV850RDJofeIh9U=,tag:hom2mgu38gKYD2TDjupt5g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
