apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:U0NUQdbJ1YZ68F6RguaEReQNhMRPBTqCuCS+PczbiGB8fzgl9dBl6Mp+0489xjmjj1jGFVCwznezXxzIQxUWd/ZcDoFp20AveD+B25i/jslCfLEOyZeLPBLqTwuT1VLBcZka9vjhZnUwsffWtz4Evl/lwEhCYcE/WZZR/xfefOsAB1EcqSuBWxnkrzn/y88WM7iBehIek6m9gowupWMSfGlNW0m/oi2toyuZYhGUJt6qxbEvdqv5ZEfv7X6v93KTBU4YVJ3csujMAhSE39WlYm816/Ie0fU5ap+Qyt9Vda5w21fYXgKtHtzrejm00hlgOWAqTjGHGBHihYiuCorAmKsc7+wspBKJw9VHXwB3X3jOfNzltqmJmkeJmv8MobZ2,iv:KodvYRQiy02AOW9ymwi2RNIXoEsIJYh0Hyja8PQSAbo=,tag:qtDXu6IDRVDhhkmVPKyh+A==,type:str]
    identity.pub: ENC[AES256_GCM,data:3NNjfNgFxuIOnfwO+1DC876PTiD5IFiddrAe0Xwtwl/wEkqSZt+48W5J1hcbpgxIpRSw8GPlz7zkzjBbh0HWyMLLr6CDTkUQeXDmCO5ldlFjfEZuuwCD6BDGk5OUBGJvw9qYdRp0jAlIbTsyCCa9h/gqmmfiaXB98oRiIHvvyXrJsqFggiOGDqrs0ctWV/KsVdOHFmJqDz1uOjronW124vRsHiVSdZHuL7DfNfQagqQ14zPwd+ELNoOzSXYE2I1jftHPhvx7hNjNvlY1Bg==,iv:/f9ffkBP9cgWSzgiBXmpnkn2eP8zh8fcULIdYChPUV0=,tag:tReOJXYUm9sZBZEtiDrP5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:zwX3yvR44zPPsSYx3JgL4ow3ajDLSAeAAhE7txmQyvDIdUkRtrq9lNtR19N3v1xa4cjV7wlKm5NwV+tZ8yrS2Gu/GZGGZjIjrGIXJqq+bLPnkh9BHGGNwaptm3mjpCbKNr39M7coWjLS5IBCSth/oyZ9xi0IM0tXP2nAAsW54SjbQ8tv5ImlqxfgedIJtU7yxNlGYlZGVBWFzlVWuRGRkqVHRsNLpIPtH7MI,iv:03aWzquRXdScNqiMgEc5R7JUPQgW+s6fcb0XKJkxhvU=,tag:gypwujseC5c7WuB3sh2RIA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa09GYVplZEFNbXJtaDlV
            WHBBMXFuN3lQRW1RU2Jlb3RRRGJKNlpmVXpzCisrb0ZRdDd0VXRYYkY1UStEdHJF
            Z2tqQjllZ0JpcHBHNDNZR0dVS3lGVEUKLS0tIFczK1pLN1RPam5tTVJDQnFsMVgx
            SzdzQzF1Uk1zT2hzcTdMLzgzbis3SGsKNxfLM67QreMepGDMyymmuLW0M/Aj09DG
            xKeq5wPlem90c2xxI4o8fhoeIvmpDZe6mkTioBDYzWwkcn3ggxUGTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T05:40:47Z"
    mac: ENC[AES256_GCM,data:0W8Ovk9SAtzUkDrZwxwM5TUUT42dMn0WfW2Qm/doXMjDKZ8YLcpa5XMv6+i77XVTGdCMCRnOSnfl9ImQ1Kzs7cWUaKIGEkH9NstY2D7cqjXb8c6hQaLgnYOvh2PDdXm9I3CzUbI/DfigRnOubUqr26TJH5+94iB3HmyBR4KzT8E=,iv:MTlD2NZy4D2iSJ3QJyi2Ju+CxKJgXEfTlbTb0Cs6n1g=,tag:OLmscI6RRF4c0tSSKeqbDg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
