apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MZTdWwsIcSxFW3m2T8f92Q16QjiBvKpizNyHyCodlSJZtqAjr21SuUkctcLqqD9vq+uw+sYkFpXaZPODMtHkSaFuU2hh/YnMWo12t3O3T0syvhGzqJv1zU01MhYYrXp9U9PFk1CItYBUfzDrxB1YatfGPJSxHTii/VywWUTNGO0N3uxSmMUn05bZBbD3P5FE3/jAxqSdMCXybl/TVsSRTosq4hTetI6Gzv+go6fbY/pyZpDObyTdEAkCJhrUaohDT68xd1YRVPQnY2/ezzh84NXvX8btGwP82LnypC4wWJ6TS+mpZhocT2d+fPtKrqRUAM4OHPVfOQc1lWDdjrdIRPjYvS1He6GdcoFwiVw0omDxtPvQGsbs6Z4gih+lhrNa,iv:R+ZS56/5bW9tWVF5GRU7zpCFSg0YC56mrmLGjy+W9NY=,tag:2XUrzJNZHpl7ipCsVtJjyw==,type:str]
    identity.pub: ENC[AES256_GCM,data:sVsBa9ll7VgH/ySjtk9pzmbOgw7ZWOVfSNOXjLsCXwXHH8tM1BlwFZ/oFh7XnX9DDB8uEHKHVbRfa2E1Co4FjSc+wBT+0RmAhNihY2Q3ojbj9DmAHlzA1oBz3RYiz+SMr5YTyM95bBrEztSNg0SnKXeans9eHxrtwP8fpoPtiBEFjR/mJlcVLdqp8el1NTG5imjQ97wSa9rCA8308wmbL3GVjffD8qtlMgAhVN85Q2fvkbBYpgnSfitftLrNVJaLY492reSN+YSYcw9ttg==,iv:ZcH9ui+T0S/strFmH+P8ZWUvmGeliXNLRv57JXsD6ys=,tag:qnSRQs5iRC+r7xMeeUcXgA==,type:str]
    known_hosts: ENC[AES256_GCM,data:thDUUs+je2gG7wUNIhmEyeXkgj6eekYWmpWNkFdXkpIpySddNcrKnKYiDfDq7+t0LaQixVR/zASFRNeo5HdqNZPjkHLaNjyajQdfCCFNuqsi00BK8opCv3Jlby6rMFfRG9ENutuecB1QLiFYWhVuRBmzPHGFem5MMfIJkv1TecJ5Fw/6PqEX4FE8z5rDTZ5157TgvTYIaTxVHPneRyvw3eg3Y6t2VFIhsVA+,iv:1ATdkkUdfpX6l60EYKD9aiDPD1WXSImmG00sQLoQ03o=,tag:PyO55WAz/hEUrkNs7gpQIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdGZnWWpSd20razQ4OThn
            d1NWbmgrYjIrdERNNGhvVVpkVUM4elN1WnhBCjBLdm1XUDVWb2IxRERyK3FiMjNS
            ODBtaHBSYUJjdXd2RzFTSVB6WWhqOEEKLS0tIFFlbzZveERVbGRBSUxseTNaZjRn
            dDFpZFZYQlpVQk5qS29BZ2lvd3JyencK2gPebGNVnuLAo+0nOFPNofkn+NhdOUNC
            NGMnKuXvWY+6k7PHgVWWFxTBtafEXKkljRw+1ko+uoVkA7j5ZesJLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T12:30:24Z"
    mac: ENC[AES256_GCM,data:qJ/Fy+2k6lf7xbEzmxd6C7EbRuh0Qf+Sum82Axn4sZfDNdzcwzkNAtKhPbI4hvwyVdymZ3IknUN9RvYmkqbvAhsrEKlqeJooSqRrX24/H2jDg4hMAK0MaXb5t8BEycFwX1ZvKBIUKVCcTPqdFPQCbFuyD7TCA2SnoU7KIAAAJcU=,iv:0GGY34YWeRZw/xeyobJ1tmux0DWNhaSqNYgUNIAqIT0=,tag:ZjfKuQwiQsxpLlbk/8tiVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
