apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WRqOzBkZhJmK3D+L4QAlQyeIZJSOwVcu8YmOxs35r0E4fKy3X9YSed26B+F78l8QqQQP6TBzrygGkNUyTZys8w0UPpWX6TCjz70Fq0M0ycnWdsXBK5ih9ZeyyyTAAjoWBnck/u8pMr0xJeqLlKhjqSkhgiFYztPoHVfcvkYgja9mTG9c4IiM4hnbg43tKG99o60G0sZBALavCKHjBe/Z55+3Tgy60RrrtMXEEMFZhD+R7OyD5vTx2lcHuBoFu3EuzIYmS0wUfYAbFQOqjq2pLKaSX6AQ26P/Jg7vW+aeGf0+KrcJuAKvkSCpkrc5BefT8Undx/UrMIk+ijPdnWv4cHgQgJkcjAGdM3AazA0RDxziZJFei4wcmGNPvil+CIvv,iv:4ts4lk4Ll6HEQGjsp0yk3Y/VRjyFa6uNV+yog670jhk=,tag:NQiQTLS5OC4p7g3OK96VGQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:342DDbsng1eZZRMM3+/J2SHP0Mu738gZaWb5lqtnXXL9LaWkmOH+aFtxcn3mHBnvTUjx7Qs+JcWOwD8CakRnDa4++ZhTZTHglJc6+0lLQzOSTNWA0puEX6iG7S7/ev5JSxJquJShIub1WSoyGNeh2rkvufE6tZ3OQ7mSXnSL4b2BvwLg7g6Uurz1zt9rJT3K6+CT5+ubfFLHCi8vhK7Qejqj7+SsOkq7QpkQEbbh/gkyg08gIiAqYQCofk7JH4Nb98PS4aU4mZBbEIdu8Q==,iv:p6KEGlJZpxOkf5+bV0XANOJCVJADmOyhrER0TqfB/Qg=,tag:ao/aZrV/emCzJ5uZ65yEXQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Yj32xMtdR3gIV9/f2trSdkdB/BqXbalqEgrJVo6DeoiOL9v+DTlIECiXkCXTDDaI9oW/lmcFe3mMsDk/nURDluZqMeNtRvHYXF89OVNPSKRIFVYvbK66S6NELRz80IvJr0lmxtTL2zMUvoMrZgptHnnlHwDrtA5+lOLODaDOSlTYSHA2gm6Qr2q7fjunc4+qsPDm7E/Cgq4wei+uueao2gVspaMfjmieuRiW,iv:0T3VZ1/mw36Ghj+u0vQ9SiDalA0slqgMgYPTzdJWcJ8=,tag:gekNNd8PH1X/uOeJshMyrQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTU52WDNtVzN5RTNpWERh
            M0ppdVB4OElkVUxoNnZiMkhwcEg3QXMyeVNFCk9Id0pWemZkN2d5WGkrMnVnTnF3
            UnptV2lWUWoxNEpUTGdmWCtiM01ScTgKLS0tIGJxWDFBOWplaS9MMjJBcDRpK1pE
            dk9yVmpTL0RzQ3A0ZmkxOTU0b2tpOVUKaFBccyieHEqOhTQ44ncIAK1zJYS5fXnm
            NEDKVXkLn9Z7si9jfTAGR6j1huJyQVzXVjobGdKC25WYuR74E7i3nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T02:36:30Z"
    mac: ENC[AES256_GCM,data:LtUhlWnmXUnpdcxp1kIeYgz0qbI8Riyn38Br5spw6FBWlcStgjH5rLDrXvRUJqAppl10eYMYMVoNP7tuaZqdAjTKEPXzL3Y4LgwJtfM6+Sv9aqG0aMC8QOE2WwwY1ZD436iqPXFhHBxVeixCVwehJw40ITkqkNKF1eDL5qSz3Qw=,iv:hwP4DsrAVCfxthboWa1W0PLOjrXjrqJgejl7nWvPIng=,tag:mMz2e/Pbw4zO3JdRf/QGAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
