apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:09681ZD1RJa/XqKlYUaQEcwvh9dal8NwjUKggn88XeSAjoLF9AD8Wk6KukVOjFT8nIo5pokpkcsERmpjQBKfT95ibMYDZ6fmvjEEwwTDMQd9tf3SeG3pklmJYnzcNjlsjabm9E0MwWHadZcnp4/m7d6Pj/y3PiY4zeKmDQyees77OZE6jdjGMKD1qbBdkbk6x9PQOBWc91qQcLfZmPeDgdmRYuxchSjjzVZ84HqRf1ouMcNEjKq0kpfouwf8i4NlHBXQlKI70CAatKxhwpZ0IB6DoZxIFZWyGNXdKdkEr3WUpUapntRw1IbrLf67vSNWfWpik85MvFu2jRw68/fbKm56jDhguKSHtcAQMKjIRiegm+NK1QwEVcUwZ0/YOR8k,iv:EuX0MDtMe1oTsZ07IxWMcw6M6fj8Yk9m/GJkrRANpZk=,tag:j66HXVdJUQBgLR/Klm4fpQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UhwCPdEGbhnXfaD1pc91bwhWiXr5x/hjE9KN+XQciLNSGRQsbD459wknjzNu4xtYlWdcCExJcC1l6t5VfFMdnncd0iXcOwb8Bo0kO/oYIoXY0FO9wKjHVX40n2bGbOuN5rp+Gn1T603NDTeHizfc36xXPOWATbO6VjyRvoI5EKLffAmTmucGjbuhrJMTswWOhryni++Pf09Qr1sanlKtvDbeyIXm0ZFYdy/O8BHggGSdAVkwNVPUYEVmjM0gccpXyFqfzL3e0zwqVl4exg==,iv:Df12HLXRF07wLMkidS0b6wRUKBQY6c/5yaDw5XYa/OE=,tag:IMoU4nVrWglhyeb1kT6CVA==,type:str]
    known_hosts: ENC[AES256_GCM,data:+lxmj+CbvGNsksZBDmp4ooMBZQFtiRNDmzSISTuXn7gBe3WRSmBtjc5OzX5JITN3YMCfPE0E/ZGIqPSqnz12sra2wSelZp6IzXOi/DtFG30uZf/Zjos5dGOjGciproFlJKldLP6mhRWRJBLRWG46ztF+t8qv/GJAWPMg2gGS/F/LxYAXxiy0Bm4Mc6/Biq++vKbTZr7oXycCIRXIgZQE/f6zppw9xa14r2rs,iv:+YstSrP0YKXtTY+ov6wPuJEX9PH1nQMdBupi/wlv93Y=,tag:Q51pS5Jz7/ZaqbRq+QTJMw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZzA4RWp0ZFRuSTlYdjVl
            TW9LZ0xINzU2bmxsWU9GYlhYY3hiOGg0WkVFCnVNeTR1azJaODJKbkZkTk9HamtI
            Qno5dE9uL1MydE05OEZ6Rmo4SFhqTE0KLS0tIGhPTlNQSlhtTEUyS1ArS3RGVUFj
            VkNQVlZRa2RKdzRuYmN6a1daOWtPZkUKWwVgcYHfEBNfTB8xCEHDXjqdmQYdvzoc
            RRrY9fJLCCPHL5WO7uv8Rkmgx4UMfIodT5LeK4xrFWGr7BDtY6Q/tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T01:51:14Z"
    mac: ENC[AES256_GCM,data:oWW5DCbWA1KWlhCSyau/WC0/lh+2Eiw6YsrUxd22inH/iPYXgoLfQDm7Un9Ka4oBZDIr/+mf9DFUxFdORpaxR/E26Xe06ujqp/STj3v/xFwkvcVRM3tM9Zf4mSkL47BOdoSsg4DFKtqxEJRJ9uqei8AoYez4roFDd2jIY6ZpDxw=,iv:9fOrk6nADrIj5oVNv7xtiq8wJqMfEeZLHY0iYYVO7Ac=,tag:lbPCyTN5seBR0LVZiqbYKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
