apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5KvmXKmxtc6Iu27bkEDsxu1JV+cs2GFvDHJBQul8/lSnxXhAm0q9ooRIL/ghgk+kM7qU9NmCwC2tbnWiiNIzbKTdPciIuzsP+s7PSiouFFmqGIDeK+eW1u7O3y1yQcxK1uCWogqowWY1aXQ+3G84TsVRC65sEGek7QxGvkC4UXeaArolRE+UErbSCB1W+9fGOZGWihTgD1oEbOHBvl2RP6DjpamUWjg/qg88FA+Z5qC99TZunIYQAj3FYr+JUjX5GsAoQDoWJjM1RdmGf7Eh8dRpEVdW92cikPEFhIJdnUolxLyWxRaz3EtOyDTgMK4cebwAfc1Xo2OeeoDEVln8Xa/uESId/WOxjEwgJu8B1TxmSJtiu47aZxFa+kgBv16g,iv:UQwvV6pCStv9lNwgbPMjR06Czj3+gtgjocAYR84s6S4=,tag:jjuJi5FBYa4d61bBVYsqVw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1gzYOTFRocXIxJF4PYIiYRQOxw7HCKG9AFnBZ47c5KIkMMcjImhfrKqzDgig7iBapvozWpQagXVdhf5E5SEIB3Y+79jsPM8NnninHuW6wgE7XM4byPCdi/E+rsmmajAfpfc64LdRxCW2MXQ/fTNUNfzm/DXxujXXRpj15ElkR7MMvztWbDapUyFrxRl4ICwotC20oHMPc8NUaB+lctGkDa4GBCjnmyQPewFeQbCaMLiXIU/UxswGJ6XNPNSyZQRIDayOCBiIRs6GDYy1uw==,iv:kQelNInR5gyREHE2ZFxOIDG1p0HcLGbOUl/4Fo1NTQk=,tag:V2K3XcAAKKjFtleJyMyS2Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:Fim2KLTA1uFe0hpMAOGAAQ8WTQM7rbyKYV7DAN32DR9nZj7Z+IIfJOGJceb8mk1iui9YciTYB7zhvTdmA4dU0/48P/pNB6mIPrxN4KGsQ7uRAmdyprK/zCGsZWTf188908S5yeNU3gMsb/Qg6YDDTmAdYAsyLBA28hQ7wWvYe/24m9TwtUHj2MeEVlHv+vQR30v8ULMyOMHeh2T8aohKkpKEXsPVIN+E9LNv,iv:dbC5gpYsBhceq6iQI3xwJZ+s8o9agDwDkszhGUVF24c=,tag:ItaNLl0a5i6ofrX1+r81CQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUi9sdVRZUC9kbUtEOXNv
            U0RWcEs1bm0vZzRsNGI5TExuWUs5UDBMWENNCnF6VG54UG1LaUROM0FkbElJVFp0
            N2VCZzh3N0E5SG1FTmJ4U1hmQjBFVlkKLS0tIHMvN01kRS9OaHY2ME5pbElRamg2
            VXY1TDlSUWV0aWcxa1NzTG1pT0hueFEK19jrnhgS8T+yPqBWzc0ntOx8nt3afbBD
            YtnrIpbslqOkyliG/W7NcO3VAmXnmCE0XNvFrWICM3WoURqfcg2y9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T03:59:05Z"
    mac: ENC[AES256_GCM,data:4TUDj6GSghHHBqodEy47YJ9zQhdqmtchBHfYUNfSkrUmTU3VFX2rfdNIFfzQnNwdqua5ZCCsjLlXN1Td9IYkk4omE3Hg9qVCOnexZuik9r3wPJW0IgyB+d5kbPK9MMA2RILL3NFWvvPqvh/eRoqh3hGK1yKkhQk32Iad2bhc0cw=,iv:BdrLcK2oi8xpbnBKIGDl2pDHaxwDk27GKNEGyhyPBrQ=,tag:6DuYnTSJu5ZE+iDBauueRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
