apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uEPFWRvRw0Fgqz3nI9VGwKLGAlHZuTExAigGyFkZAF3PcLCOI9w+z1dAffPlLrqD/N1ukLyT8G6mk+3uLXpCmtAHeNfNTnj615EuWzxT1fdrzzmOpYC95yPKd8O7Cm3pYFU08pWv9UpHncFzw1Yaa4vfZHaK+Se6UjCy1TKQcK5CZxaDPa0Fw9Fi5CIGSSHyU+sLIljtn01VwGwNd+APh7vGHMEE9sl9jgbK0na07nM2JdvczQjDMiMr5m4+xdnMMvGdgu8BZ5v6lqcUAO5hdQ3CGHPm02InDip87lQFzmzboFXLq5FksQ7bR98tW6dBLWmopPOZ8wJaj1+4oimq3mdl9Ga5FFKk//go5MdrH55DorAxoVKPp67dyBB+j2pz,iv:68MbGN055m7LENbiBHs+2c8Hc7zEamQjvXPY2IUhASk=,tag:jpgNaus2Yq/kFCezp7Q29w==,type:str]
    identity.pub: ENC[AES256_GCM,data:7/vTQmRPcgzlXmlVg36GMa5oYr+LfeH7077PKvpbqsp+iANuNSwelqQXv2u3dsq6HLdjB4PDBihPza3uKQRgH4UsxkheArOurkTt/Rbh0JWniXCgHJiNQeTm+CvuvXz/Aol8y9dqQD06YnxQbEDkXKyrK7oiqbvHisMbMPXctaIkW2/ntOcdp8ZXdvAlWnn1Q2T5/F+66vqvOgm5c09ChCKhS42vqAdMyRbAK8GntQluFQXdAeooXtLkaSWEoOYehw8MvQUPQv8GV4SO9g==,iv:lBAXRDlZnu1AsJDtyBX/5c+YKeLT0HRHxsOFGwl72yY=,tag:bTLF9wf3Un65AHq2qqoq+Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:TKh65BdL7Ewn0loLPlrEDX+UhV8aIaft9scy1SjWYVhjzqGM66hy83XC7mszt3zDIXUBMml7sZxRI+72Wlj4ToeiE7gjxFj07Z43ylUW63hGzE1Sd8JQU9w/filjKmzoipmF8aGUNyv+CSC2811TEvy+9adi+A7Wlt9VEsAVfROB7l93LJpVF8HjXwh9Wf22RAgPY1pSzBAY2XRs2gQnYHLYyneYXvtSvHLK,iv:8vGi2lUoquAkY4n2DEMQSvfRc6+SQt/FjNpXednAmYI=,tag:ECpAf60K49+lyDEQjraAaA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ09kb0xvR0JNNkxybDBP
            aGE0NnJsdlpveTNSTGkwU09jQjhyTjZRblNJCkdzWnN1c1AvdkRkWGdia2ZnZXZk
            WU4rQkxkZFo1SVduM0ZndmFVR0F4ZVUKLS0tIDlWSit1c1VYSlVOdzNQN1BpTHdT
            NjlWSGZPR2I0WkpjRW5Yd1RBYmQwTm8KoDDIXT05ysi8bf3NfqdTDkTCMZ4UfYYR
            X7T8WdvF4M7ckPId4ajP2cF1fKqQ+r8oMzqycUgg7c/Wk5OiRkjxRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T05:27:51Z"
    mac: ENC[AES256_GCM,data:y39eNCK4dvYnW8XgUc+Q3jH+E1IUlQDI4RR9Ag9x8GcpyEZaFUIB1Qhr2SUEieR96Znio9yQziLwYiqzPQUq8G31MJ+qbjohTn9xi3hiHYcttwr3TfeqeO3gCQ+ED995HgMIUwoHm2V6S37V2NiZy1H2XSau3y4giSkus/Rqvkk=,iv:F86cjbypzQZnRgr6kFkqOvVgy6IDgQuxxGLtB4ZbmfA=,tag:nSZtU9ZcTWOWK9P0sildYw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
