apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1zSJaWRvlWpZvD77bwDGyFgNp+DUFqifsmVPJh8seB1t9JsOdysR5u8AIrF/BROaVpuytXtLCXu/cJ/ErIrY+bNeEYCfbmNWSxwkjowU05kQighNSjCfWKYITDjO5A6FyDjYDuDBHXcRQoWGvvrVpVHWLiq7HVDhR2FQRujwpU2ZvY1Ppv17GJd46aYYOMggLiz/27EbkueGOgTURWeFbUYCEm1LRrjBnglqovY/MK6aGDJdUltqbUxltcrVn/J980+MNLJzXrqo7AV5hao5YAXF/4SpYPx2hhjSh7/z5zHbmmreF5qK8k9J1TmyyyvaJwF95IvTDhHVW+e3GDXC0aVA3zVQW91qmgaOz/yghqJEkOKWpS50ff3fyJfW7PU6,iv:LH8yfPie8Mot4JIPTotTd5Cb1/y8B5J9akysvRqLPl8=,tag:cAuSmpKwud9k05kJc6DJdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:/j0AanqoFaa41LUYubml2AN+jK4y9w/l0uC2JtCk/jTFpZwtOq7mwx/Tojhld8F2YNtmbtl324wnEk36NVKjNUADvoRUsEVQOTWfJwE0q/J1D1IGFtEih9sh7azEmxnyIVvNMmtAdfsScKWhhnXiF+wBMlNLAphqj9GBgww73WbaV6CXXAOJ3LV+Z/m/9MQg2bLV0aEo8FJO0uJgyQGW+m7RLWJ9N/eVao3aCS+72l8h3FqlJ5FaNLLvX5iy422F8ZBS6P4VWUVgdwdgUg==,iv:zYATpPyJ4ORKcT0MiSTNwX12vHVjH+BKAcHK7qdd60o=,tag:14Wme3WAP+7zIjx+pwF6jw==,type:str]
    known_hosts: ENC[AES256_GCM,data:oh+JeyyFq4/fkcTF78h0srOhibXmqr2q/EsYS56ZbGMfzyE9EM1+YT/I30XcKLJVT6OXWFe7GvNm3QLOGzzCVVNUDMXM6zx1+4/kS/nGZ668UMwYbQb5Lyd7ERflUr5oaZlt5W+/bbPwBcDgJOisOg/0yMFx4He6JY/RNLT020+LfjYqhHn8GuYcMfSt6mqzAIhUMTFKsCtW9JKHYXDlF2m//sk9NIyw1J5l,iv:3nE4g4tLKGkvFVD9JOng5O6ii5OY+euQquEy2KnT1JI=,tag:V6wINugOHGodVko/Xdprdg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSThwR3VIaFFuUWVmclFy
            dldMdXRYMFU4ZTVPWjNHc2J5RWZzWGtTb1gwCk5VemF0cXdrSDRzSjYwUjgvRTZu
            MlpKaUdMUEVOSmFtNUpZZDZ2TXIwKzAKLS0tIHBtUnRpZEE0N3lVcmZCZEs1OTBM
            YUZ4QklGTzVwU2t3d3BlckRmcExKUGcKTEARIAlagBRexWCaLZsgxYKYApEkYTIV
            TJ35gWwpBAuSXD04y7VEOfhNLttRlmz714LDfOwDg8FtMkKGjgk/8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T21:37:01Z"
    mac: ENC[AES256_GCM,data:eHwgLbeevl1BNKd94jcfZe3d+ED1Us2rKixP/I/7zcKSwAD5jxm+ZRs7su6kC6LZSYHSw4AYc7pijim1mSYrTMib/xlKPV8qf16k6NdcOTeag9SCo9TGq43S7A1bwdmvRqjWeSNgUwrJMmPcMHP5ItFyMmKyS3YkTp7wz+wEx3o=,iv:EuRsPZceeAZ54U0w2YD05lW/LLw7ftMuh7sJilxXsjc=,tag:TeKOV80WCz1tVUXhtFvoTQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
