apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AdrmXed2DJ0hFY319QMKhXJGv2xyD7QrbxSSZ+ayEwE2NDGCkff9sgSx5X1DUon8VKOLkFvX0Ym7fHOuDnPtmKrJUJvdXGcKRihGzwKC7+XDWL3ob51li9J1dYpqtcNSlJt0rqBBZu+SawSosDiA1mCwH9VsbSYqj4ZMH/OusjadnBeMn04JabNBjQY/YCxsuwP5fmWOnVcEXiX0My24rQpth1fkKb/uOGNjNZXMaWtWjIW17QbhA6x58G63EvQKaBECnok23VmilRQflDer5xZqQNM6RB+rzFce9u8DS//WV6D/lw9nIXA5lZtUjh7n99c9bcy6VuCsxkKrZdc02FneBwdjm5BkA3ZedlLGitLYyGbGjxmOKM+ZmL0cbGNd,iv:jFTQeeI2lOZZPT7h1wnbH+u2dn0An8vKKPu2qyPzBU0=,tag:j5sS9Jr8jFJPGFBs8TpdfQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UC+nhBBu5faLilwwMge6oei3/W7ZBXC28dVbkqVea8JeVt9uDEjX0SxNQdLG9ZTluxmQinT0Vav2L9ztV6J6ffdU5mRPcViNCOBNdYW59qfd/2t0zMlr26JnWqELeaNM/1znHg1RskbbkWojYv2td8kp8eCGdMv8iSlLZaDl5wnDbUvymiSO/NKna71b4PESAFmbLHBFBuQn3TCIfPdnodpGn+4S+GrN1YDiCkkBGRdPKr1h9/Xvrq9whoCAx4PrYAyXEJv9JZkg5cefMw==,iv:dsN5yCNws/6y1lJDX0ABPUFIOyCCP8oPw7I7RYpkb/Q=,tag:JjHc4vE47xojvvXscSr/pw==,type:str]
    known_hosts: ENC[AES256_GCM,data:TrjBFYDr7nwgAvammuCm9xgmV8Z8+G61dc3EI5EaAjEaSSkrS3oxogmIV9LjP9/1Guz0kGel5wX1etRBoDQDRTqMLoBOOglH4YYFHGn/PRZDDPkl4cWHurFpwGj5EYJgDrtVbCUwjuD+pF2aLTqxPiiwxxM62rgHzOD/qwsJ125vOFjLjcDt6gjikQuVt/3bWXje2ut3afBCTBCDIDM8ogQEpygnzqXpAusS,iv:H6FToHGPmsFsGcObHNgJTVhbftki1DFokGepheETUWg=,tag:J4W+4SwbKwOdpCHmMBF3HQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTjVFR2VwSkVlRUNPY053
            Yy9LaEx2M2dCYmVINXZQMW11emxUUnRma1c4CmgwdjZQdFFVb0JYc2h1TzV3NlFL
            cmk5MVMzb2xVRXhiVkJqZngrSlBoeHcKLS0tIDlQSjRna1dNM0F5RXRZdE5ObjQy
            b0NxT3VQWHQ5aUZselhNaWtMV1lSL2MKAVTwWFSpAM6x71pRWPZSRyB02AUof1nV
            nVhcy80MoTePYqG6W3JqfgRZ/1argVlBARg5N4SXcbuiD9TRvf6DUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T12:27:00Z"
    mac: ENC[AES256_GCM,data:ASjJS3e3y7xn/NC0+d6J0JZgxSJxElC9JGxw3zYlLeL8xtx470r5f86VQAIrYrwT7NEFDgtComR3Byoxl7VntKPWhNJ7tbumQZ9N7UqZJF1cdMs9PGog55H0SS5Zpn5LtgiPQUvng1oFymnQ/YTqS2tiQsfsqKceHyb0icltl8g=,iv:nmoHpnoaLwm5IT9icPgtcgeQXj93RLp0z98wYFV2mJ0=,tag:OBGi2o4N/+qArvW9YV9kWg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
