apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wD6d9iny08hfR+KTrnsYfJbA3/i1rmTbv5+8B5JHgQQbXMHyIUVEPi+6iLNuubOOAtE3+IFrBmM+lbXbJvmbu8j0V16EYgLQoOr4Gqge+SW3s7xG1cMKE0x+0rBOGM/0V2tZdx8AWBmEuaJEFV8wx/QT1oLLiAQQp8GG2W73ZFjrYe896Ky1r9sgSjHCczIa19jBltqbOMT+XZ1a3J4upRZ+ht0n0/sMs3zjXQeVXfQDcQ5BQ85cBRTaSiTmmqtMVocTSY1f3bTvksXoldx1eASZD0xD+juOXMAc5pRsYcmmj1++pqjlaDqbDhl1QRKIRYYoEmtOSkuqqD1qcltbnG/9nbjbIYxcsxqSMP9WfggWP5yyWWq+zQ9IXDAhLM2p,iv:2ykhImRXAqvrSWMGSPN27NWDodJKkV/bZaUCmhhwgHQ=,tag:EDTFAuTUwlZIkBQjym28Gw==,type:str]
    identity.pub: ENC[AES256_GCM,data:pel/476YHhEwwJsb3oUfF4yDSJVVYaDB/TjyamujeZ0bhkbTY6tT2ffr/1aCxrqPNd8eOvzND5zOD4LQoUD7+8qdpWKoSJQnNLkLAJQJ6kcIJ/SioPrRLnS4znKtfLH/UNlS56O57DT8GrHs7h1/IdXkZvVm5TMYu8+KENXQTicKVdXwucZtVBfT6HaQBJjo2g201MDoI7p5WAKWdcKW6GCUWFupg7KcB46fMlJzAaFD/4tAOBPxOnhJOHKn2ANJEjrkncHrlXBCSwwOMA==,iv:yvxU2CBOCuv0rTtp1ttfPgipBY5FRMY/ouMyhaOg7YM=,tag:NV4kMi6zdcrtEa/W9MnOKA==,type:str]
    known_hosts: ENC[AES256_GCM,data:3m7dVBcERO3iBTqhLVyTQhLtAoW9wX6gjALwivV4fcOfXsPRsq42ER7FOpnNaSyFJNG9SaA7ZfJaavRm8V53TsiYJ4P7IpwFZFjssaIxrYgmPO2t0441fSgADJbNlw/S791+V5tiIax7IQjmeU0jymOIAYXzkaLoUEseRcemNNRiMZUKGPAcoYlfljbQk6TR7y9DRaxTKn0YbBYXrzHDTw4H92hUojpe8fw+,iv:zTaVTf6l62+7QQMPH6EhXDPS+6pkwQ0eqQ1cpkUy0aA=,tag:lne3AOnNLYbq6g4NqIR8RQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eEYzMTl1TktqaStiVWxO
            ZkE5aXVqSEJNS2x3YWF4Zys0cHBhRHVtaWtBCjRJc1I3VkxWWUhLcGNtR2RNbk9W
            T1ZpRGJVR0tPZWxjcm5jeXdlVWhJdUkKLS0tIGJFWmduZVlFS0YxUkQwN0JWaE1Z
            a204ZUJGcDQ3NUNieER1ZlVtWEpVRk0KifwH5y9oidNjzpPszB3QPqOVLeFp4Ap3
            wlCnhMTJNWXcBHHcYzT/Zf7V+VvgTOcD0eqI7Fkld4ohvP1XH4kfuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T12:39:53Z"
    mac: ENC[AES256_GCM,data:LF/xZlYN05klbdEqFjnWaWC7Fx/epLF2uWzJb8JbWbCK2fcmtywLr6+yLOSSqBFggrdQfehUhVHjYyWdoAtm+VGXujOfpGNzqHx9e6oCSRgad+kRabWJjzmvreBtKgpLQaya65odW8WjDhWja3TjO8vgBeasM29c3I2266oKyfM=,iv:nXPxtNI3A9lrfBvm9sO8oovp2OUy0D7tVNstFPtzwsg=,tag:Mb7mL1fYlp1fxvaonN4krg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
