apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dlNYsr9A2nXtutYV16Do9Og8GBP2v8mHb4kPaRGIaU68x6sXZauCityTXWbYEyvl1G4qdslXTvwRocUAtuA456WEbqlTZbVn3dJSHRlMjE/eYT8mchuVk0q+jkc/TcsQe1JF2rk4pjXd+ML8eMk/rwcwFLkUmVUlu9rB2l+Xb2RPFL/p8QUYbc+fQ+227iC8IKUWvNX/cMJyjsTtg+Pk/TWXy0L3D7OjV4n3Hb5i6H5CQb0y0MtiEIqA4isBD34F0EfjpVlXBIqarhQzBUQjsYOuUYU7ZRu5wOOyIQWncX3Yn3rQRmDRNJ8PRruxtYsmdCVPfmROFNpxeUnFfS8lEBmvNEcFJFSJb1e8mE7CCJLPlZbGuf3WSBX+dL6VpINn,iv:ptGiQo9/Rrisyu8kGHzAiSq5VPcXqk0eG3tPNO4dI4Y=,tag:n1ZKBe1Ub83jAMZxELLBkA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ATINFNENyPqLcLyfarOYKvrCauq0hJYrejgYDzrJ66gXU5hdY533OUZqrcOalGWhgqhjHmESZWFXgKfB7QYCGBZwNEt4wupKxvAi390BVvNJRtEQbWFK0aSNMuCGqPsbXmfCdNMIysIz72LgJ9CnHvV4pSnqStcDlkOca7ksojcA+VGhOZYhZrI+MwsMr5wOjdx+fhJCXwFlFrKG95lVqvSsR4uzR3niqa12CTeKSXJiydAOC7V9+JQPbSajJ4xyxON0PsZpmJY0TN2KHA==,iv:TFA7ecYBWpprL8znJcksE0PL97jJjccyYgj1OZaAIX8=,tag:GIqgULce1dn5g3koEfqbRg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kBClN8rCPVqWirqYsj8aeJ8YUNcNqAte/EBll9PtzYy5Cimd82k/kml6e3I4d7JYy5H6H5A8l1ICboRmq1EoNb6cyewlYl1ftfgvnsP+kPJC5wCxlhlhhPWcyVOLxg9XP3G8ac1dy9VPTTy0GRryLgs7qr1pEwMddnOEpLfcXwwiRewiOEKcgDdm85g3honcaHlKdKvgkpETLFR8yjSmORunZxJQ9sFKZ8ej,iv:1Ql+YYpnBxdmTHAAjiLSh/3Bx64GJvTe+3v3967CR+g=,tag:TbNkWn5JFtt1aEZ6ipq7xA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVUhvTmlBYzF4Umx6TWFs
            WXBLOVJqYmltZFBmcmlYMUJ2c1FFRGxzUkNVCjhhQlI1MDRXMHZ5RTkwS0RpS0RZ
            Znd6dDY1aDBCemJIcFN5NDNocitSbTQKLS0tIGpDSSs4Mmt6bGloZXAvZkk3VCtS
            OEpmRTF5bGVDcVNBUEsvZ2Z5OXVkZkEK1n8CAznndPVZoZt8Jq4Zr92Dm5epDq7F
            m+RbDPECBW2sAQDKGXlGuzmyNel+KJxIiQQBky6IX4b+PQM+nv9flQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T22:28:46Z"
    mac: ENC[AES256_GCM,data:SChSiZ47tH4nFwNmzPsf9VgjywgPXbQ5QTIilamTSRNwqQyw/cpYcJhQoaIKUQvo3SFcWBSoL+48HdtUneRPVCTz00xqBxPW1IfBLgFzyDaG6/rMIP0jqNFpW1+oFgx4T3Nfp1lcmu43lKPLfzRI/kJYAvIprVwQd2sDpQVpZEk=,iv:XraNRCmJBXhoN56k4wZBE6WKoHbAdtWzd2PTIEzWIxw=,tag:ZO//ZlVVCn/cjAQ5IE1/dQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
