apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Eh27YtDKYLQPHmeUJ/QXf3pJgIbeW02iBgB5znYRxOpfdlktg2g9j7fIWRW0uHAWl7EW/89npYW/S/gu7QSzemjPh0SC0BRklMfQc6x1Hk4aCmfbPzIqJ9G5KxWIKJpYvj1DX80ID4kflBt/EHFayXpSHIbMIYbBWkweJHZeLCdqANxJAJQSSt5ZuS0p+vEAZ6yLTFz/bFMAZkji5PezU+1d2oH4uHa/dnnVjiQMlsWpPBXgfm9Mgo+u14x+a6K4m6P6CaMi/XquCQX43FYHscbnaSiLRF4OdN2NK/fnh33vbDxq5PMY9JIxWZzBXCGRlZPrgfHILfjCREmNcu8Ps+ehMpHF5grcl3D7ZDjZvSaFdfVlpHAh1YkRY5SXTyaz,iv:ce/Yht1DjJzgHdibATnCb3hUWfF3MTgx4g85nwcs5xo=,tag:84NNRMlRdqbM4e31XxUxmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:IzoHCm3bgYnCYUl912DFRkDF6CrWbE7NArHMXkYogpY0yIYT2N4qNAjPUo2yb7PLytck4x9B3vIOU/JbDoAzFgmS6wz/4CjQVIp6DWiGWiOYl7x58UCe3j/DZtOBr497cbsQDEOMnBqyUP4mglXIyo/ftoCNtGfiaZujGHJun0nXnSHaUkX/Y4Bqxo7hMvmY0BWj24CEb2c9NM3SPYDCnbvcCeJEOxxQ0WyUrMYJklhjq4L0VHj/SnusCywXY7bMh8TlSJ35ssXmucu6ig==,iv:GlLJMDOJuSAq3ao4nQLuUbpX0Di4pBpg4fwjCYGVCgc=,tag:pbDofoN6moAPvWWwQ8vWTQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:re5SkDxHuFhfNPaV3vlUUgnLYQwxZBVOV97vPL1fhrv4ZZ6fN75T1vuihE6adPngAHqUCURLQ7kbxSvQb2jWA4+fNhcGXHPVqZUIb/f2nSkYUImoIHDNQG3cMnzQ0aZOo88lWXJ3IHCaAwA3GdkxGeKvJ5AoBSXOFBPhBOv2JdiS0cEvFQ17yXOaq7J94qGyXtmTUUmyWPeiuZ0pj6F+5GYaipK5DQ7svoJ8,iv:UqsAKRPX45llqtGs0OV8U6Oaxl/p7QBOahBU1R0Rp5A=,tag:9vJeIkuO4Aq4Ge3Ntr19Pg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQWpyU2dFelFtZ1VLTmt5
            YzhxdDNhMjhubnEvYjhRM1dXU2NpdnpFMXlRClFERGdGUDl3K1MwTXl0S2NoZ2hT
            QW1GSFVRR0x6Ni9mQnI2VWw3RTErV0kKLS0tIFhubm9HTnc1bGtXTUl0TDFTeXpk
            cFdvVGR3NzZHL3dFbUVmZDg5R1lqcFEKiS7XSOFSAfzRTmxGluj/vHr7TbCCFqJq
            T4T6FYQzYOkhbhrE/j7v5Jl2MMETjztDVJujgb1x03zIG/q3cn9oJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T09:20:43Z"
    mac: ENC[AES256_GCM,data:RDqon8VrO1YlcW2A8y3wRr6Z8X6wiJasDKA9LvjM7GFSGZfWaeTayorkydNARPjTj/jI5HdSfeAlxx6y8d9kghq9bX8Rx3wNZVL0k3tAXDa3D7u6TVfWcDZPTFmGLQWSRJKfn0pblP+Qh+SbPW0NsdI6TGv7pl2S56RBHax6240=,iv:780CGbW6UcFZjiQNAKZ42GWN5rxEoXIY8+6DIuqOl0Q=,tag:PpeLqhjyGadye1FJHDZIWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
