apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dH6nR1YIs5mIAewKqyAShIrAmvm8baDsUAsdrcwLzcCn+TFPS4hxiQQxJIG9RPFf9czyUtfugEe9vPJ0VDJCzdP0z5ZoxOAZITUOipFwIfc/L9SMrwix1IytZKw6KVsxev/FDKifESYIUv8QBrx98MmtFHXU08eCwmJcqbQ3AhFUTXV2I0LcGlzKeMCxYxDSewgIwMJWE7FGGE4bHcBdnCMb/7hyQvkhnKXH2oS/iY2H0blATK4k9l6lClRxoGQIAxNrXnOmSgPHaRpC+OQTREwoBp+4ZPVKclegEKH2yStobghCs1VRU2S1Gw1o1/tQJTww59XMl22i8PnQIe7pP1pYvIoCoZwNGAwiSyZVonTExBts/K8ejTF4iix2toje,iv:zbIZpRLvIi5ME7ZJOH+5MN3WbkHvY/7coI2r0YAs0Bo=,tag:Qh3E/Q1wqXydvEErDPgNaA==,type:str]
    identity.pub: ENC[AES256_GCM,data:rD5X6fjBR5aUNntu/NFCsa3K29NXYQOvye66hGtWsgO8tJOIuvVHX8BCiItHtPAnMCfQtSPXpJUsuNej/s5iPPpyhTx6zsnxMC6qxUgvRPSWfN2c36WuUVs4qcPDP88qq5whYHhvbLF8xC/trAbfEhn6xc2/rxxhzni57cq33Hb0C1Xmj0SKf3w5sEc2YJXVNzl8wYXQ2jVhR0cCeVolLDr91qLzU7luGAnbwPI94bPitzE53oWxjXJdOOsqnU1Q3wiWBvpxjwTzGWfDHg==,iv:KZAdxadUFS93ZF3UAPjCZxqJ7m0B++uNRLiXeOR8hpA=,tag:VFKyMfg85xBnO2NkWjL9Qg==,type:str]
    known_hosts: ENC[AES256_GCM,data:syIs89ptl9aNcRbGb+lXwO31QjlwAhid/orTJUKzqxBfTYQohn2ARVtb8nlVb7fMDgMZuaSZzP6/6iDovxKKbxpX8L3wvj3RzU9sX5A0fq36aXngAD8KJu5mAq3/+aFnLAlZ/N/72HbKfLvMPxLf5cFewVQhm3JnB2Dd74lYNNGa6mfLF082Y2A8L6R2adsDbj2bNMix6MUbJnzGbNzhbWbN/S4ThPe88NlV,iv:JBTyTUpIES/QjvYw4KaMuTl/CSpTku1RQVbrUGWhmbY=,tag:2Y3va5thMGS3jNMho591WQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWXVIc25aT3hyTGsvNCth
            ZzFJSUNwbFU0VFRFc1FQSjRFVmYxMWhKRWpvCndIVUdFalF0TDYxelYzZTllSmts
            KzZDeXlRRWRiaTZ1Wm5USXNRelVmQlUKLS0tIGVmbUpjWVVIRjlZUTFDU3g1M3pX
            WDhlQkJCY2RQN3c0alFDTm8rYklEM2cKNtHM9Sy02C7zmRfgPFINN4Vz4ToY7C6P
            loJvs7yFE4ewGetrpavrmDfrHjohYKypu8Um9AjWmh+17nr46hhLbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T22:54:01Z"
    mac: ENC[AES256_GCM,data:o6N3FpSpzAZGJXl4gHN5etjLvepxCC5yshJ9A7iewQjJB+X6eWboF5FtGM3h681srWTt6mhOC2tGCNY/HrXq8H7OoRSdDg16ymJkUbUqUg5H8g5GpSi2Siz1lsystYe4HchbVwLZIq2FlTwVcDVk95mpHeI2I0Dv+gsUWGfcerc=,iv:FTz1tERzEn7Bs8qG66BSYmbM0YdKzUUF3R3aMur4ap4=,tag:Ub1PFxPecG8GShet+uN9Tg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
