apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ahzxI9PsUxA0K6iPmtzgr9LSM/6pnOoS5jUSuROCbcbbfRfNb/v8lF3xC442Cfy27VS8aXuZth5plzhInwtrZNsjvlYEx5f67njRofY9qF2H1svKwxbHb5q/ZZmnxR7hnaQ+9mnca+Tg0mD4qFrPPHvbUPwmFELRmCn3rum++YHOoa55EAIn7lsQNL9dkPv2Mll3qI+BFP6dJbSV7KtQe3O1yVNPDczKlzFYOJE3Vroj1ZWwnWYTU1mleGxEZBQNPprNXYXWY6z2+RWep40dSFhlUdZZqpSEyLUciSIPlHBrhMP5cJkxTqVXVb9Lc6qiEWpovnFftXp4cXXAnlEgEqxGweaQyRKLy0mtiTFN30lkYyoqajCjwpOW6WGh0E2x,iv:nbI7o2hMKgKQs8dAgkmytrSZwBogGAgqD7N6iomQS2g=,tag:J6zwEutJPkirpcMKpYSxmQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:staTGqYo0iQycHUjMwunSO6Z0mTIxGgxODYySL/nsqlEN/0e/qS257utFr+w5hqeithROuqVe+OxNUO7z8YZ9CqufUlwmwwxTGh2fsP77d8rW2nHC7Y38IzFgI+VRr5PBRHkgHyjhz5KuWTW2gr9v8OS+GiPdroApO4vTUnta0gaeLfUft1F3nTLgjN5gi7kSB2d3x29m0NSSMu+3teMVC/GoZyrefIbyYVsRJEiuWbRx+F+Rp+C7xFIq259XJyjQMbxXf9wAUGo1H+rrQ==,iv:2Ipupl4outI/jBA+nxYlE6EMPY0a9RfT+UwwQdRmkEE=,tag:zApHALXgjYwhN7r1E9Cfqw==,type:str]
    known_hosts: ENC[AES256_GCM,data:bdJVDG1MQqxSHALXhONFLcY2K3/ZFKgvPHJdQpyRE9+Fs2L21PibWJAMZ6OtYBtIZzv5CfiSagaeIuZnE/J9moQqAERTX1d6rok+YSU77UN0thIk3j0R8QqNXiOjck+VIpYg3uDtsbrTmp/jbb5EOMxD/r1LVD4t5LHK6ig15VHA2tv6BbFC7dbXi10wC0iGmtIDOgcPKaMq2swDavzD/DCgzfHVGhLEdU3J,iv:KenO9aGFlUru+k5sj2CXi4g0rLOOYmJH1ZezgJmO0Sw=,tag:9B8yfhJGbPScKcBeMxYKNw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBULy90c1V3YU1Ia0dudFlV
            QkRseS9mZStpQ0pBYy81dHVVb1dkTENlbmlZCkY0ZXlnMHFSckppdXVwdnc4ZENY
            Nnhla2oyUG9tRk53VDI5bi9YZWpTRlUKLS0tIHdDSnpLSUs0c0lYT2pnZjFJRllG
            VStTNkhjQ0FYK3h0L3NKUWtFREJoTXcK9WtElRT6pBBzEYEjyB8ufcSdlTw0YGA1
            QQtTlz06A+EgIx1R/Get1XFmkwPKXYTmEbgKGXd+NR8q/w90GPQsaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T09:49:19Z"
    mac: ENC[AES256_GCM,data:3MQMGJEFtkPS20jEDJzvBWI8j8dC7gQ6mPzH9J4RqU26ghIOIMWsIt2q9oaF6cYr6k4hA1t2Az2Uh9oqs2aBDOACrixF9X4Gwfpthk/SVQv4bSP2T9x1IsMFfTcuh5UXN2KhhmTTRMQE6M7NYAaOLTQZpXmsko0C2Z+s0dKsLMA=,iv:oV61kbtRWWo/HC2rRYgSDUyxzQMAeBMIM0QwbeirY7I=,tag:254HHFPHZB2nUf3DQRA8kw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
