apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tfSRfrUABVJW/WYTwJIZOfVh4hT4O2WItykEbHMAARrHUCt23qV6JQjfv219UQLQtJ1l0O0os7fyrnyh/qCrOKOLrDnCAWC6AYY14wuz5I4A8ejVW7gIJ//bPvF1C7pDsCUN5Q0TDXoqYfs6/PASznfmyXJgu5GeXGEBMD+7tJ1nUFdwbUfYcG4FNTNiQ4t3VvYYXnJtresJMoOw6M/lbIp/xotwmAt2i6m6aklczleajTpXKMPO1VipVIBaNQnAEUy8zu98QS7LjbqhOyNA8EyY0PeUi0SM2i/ICcUUJsNngy+8QWJwVknzGx053YNDOZd3WJKOCWDJoptRPIsfpbOmmh7+JAvafKc7BqVTOBR0E+7iQI7Nxr7/AbTpunj4,iv:PLw3ccmKIfKkZFBRaN2wuWmDkeAju9XMaQQvAk63tyM=,tag:vZoso+AQQWfbJItPxf3dsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:/CioP1WUnptoyXfDbB+iBiQFCa5gvncMjsD6XTH32zMToORMQl2PTUPHqmx4IFhuGJA+B4gpK03RxjMmIsnYQU4I8YxbPQ88Ye6LY7X0SKZ2FuUVzPU2VdmFJUg7BmZUzrtFVdc/vka6y56GNvKwvWdmz61hnQqhCQfNWdfudAUXmcjiIHwl6OM5ZhmTzuImZ4NLbqjcYM+GPWXyVqb27D9LhMOXEhMyqooXwJ7HztHJi2HvqAs18gnEOyJiywzvAwjj6hNKkCTfa10ieQ==,iv:vq9BJi1AOI7pGQPUZzeTnPwnFTbqEPyN8qQEKE+JadY=,tag:XUtJ0uQOcYy5yNCeUcB1ag==,type:str]
    known_hosts: ENC[AES256_GCM,data:TEb9Ljv8cbnlnLQe0ym6qbtKxSQSV0AoEmpTqXXt5E2emcviZkO7E2L/IGT4bRpUkiImhxqQ0BkbPnHuQzTU4xPqEjHIf0YQJuLqZmwCPgSU4jVe7tPi7Tp7nCd55oB2DU8wUc2lkY3Yg0YwsblqCHehzsmxSLzoDmkRUAT02uLmRYInGmt30Cu4VlpbhPNuaISAR9s6LL6lGYwQT/esz/564r4DGuvBn+Ho,iv:OPGTfH90kdwbZO6wHLEuXytJ53Z5sQIjZ6zpiaETMGs=,tag:HBIrlVCmHNi9b3aFyNRSLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYlNrTkliZks3Qi9GdU1N
            RVBZSUFGY1JzVzRiVzlLWHFvVmM0Z25kc25BCjBLZHRHNUd0MnJjWjBLQnp0S01j
            c1kycnVsZkg1OGRJZTMwb1FWeHZ2UXMKLS0tIDc0cGg5cEc0ZGNSS2tIODgyalQr
            VndVR21lL1B0WDZUZE5pbTl6NHFZVjAKLDV4KJDbPW4dJAoAZYrIlkssfc6p3jMa
            9pyrnUSVRkZFGjlcvMMrQiun5pBg0LBHq9NkY8tlysj6c4OnWl3JAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T05:58:04Z"
    mac: ENC[AES256_GCM,data:Tiba2a40M7D5bQiB8sj+nYgFcvtU/rM1SWOays2jFIrTm0qg5nX0/VeLSNu4yxHKoSVSzOIzY834yDV7porwG8DC2WptMLuy1Nb5rnojxJrdAOIiN3xSGAr9INjM8b8zmwyswAuq/8LIgq5XHdPlNCBkd8ak7I515KYqIu51rj8=,iv:KGhOjuE2NBmGyPMHRHIFZdlyTTQqcWDqyZooLj64LiI=,tag:EH2suZ1k98OOMKHu/hDAyw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
