apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Tu6bVRgVOcHwjeDNp2B5Nlb7NbFOWZOH0vNv6dEOtsFbo6UeLWiD8XyBo9tjh2nY7pF2UmoNDjUD/7PB8uF/P8cCtnPkFLjQQnFbWokwUZ1VDCimXAb/a24swdjU7pJTFWJho3KoDhv0ulpRq1oOWTQpmtoMgi6cnJLud4afqOdyz6HZCsNHPszMlr5qr0gXSi/9vifbiLKxnqz78jRvYZeFvoEGmCMPlj/oyuGR/Yr+WACir4Nw8ARW6wwJ+6cNOItkzG6a4AKauVgqWuJASlq92jiZ2NdKptV7IEFL342+4nNAUHeOb6qLvRvbj5t07P89EF1fPmrETL9/RK6whflU6gGq3xoMtfHqkZjTV8DBK23rfssvY5WQRy0ZpUua,iv:vjdIE7FnsiL6SENZJ2vGu0XZCuxusHB6dBiTTcH9pxI=,tag:4GHer8rFggBeIeRLZKAdfA==,type:str]
    identity.pub: ENC[AES256_GCM,data:3Z3HgzMyNzXsrXeGnK28zi8jhWzNMkyTmpzJdphPBAVb0/Gdw0dHR4ZJk7pn6MeH5k58iiPUFECmPOOAGKWG8PZMJdXQSDzwGX3moG0m73BBwCnAGzVzc0yIdccbFZhxMi49kp4TEgpwxNUrj2YcakrEOUZ1Br9vmbFaLX62mTL+ga35MMdE8yxDCMZuVGG1Z3Yi0AgyXWCKy2OZ4v/VgAFt6Q/P9bMRJvVzfpZVATTALBGXy7gOxDO3s+AeVdTxOathZKbZK/p1eP6Ttw==,iv:nVWwmA6/rbSVfS6U2GoEJPfBMeNW+iZ74DMDm0FUf/E=,tag:tIQtlLhsWr+pHuhG2jCyYQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:4nBUzH8V5p2melKc/yZyAMXm09e6roMRWTApEAgRkmSflUEirXnfrlz8uZooLnHdYxNExL1V4q18uxQz04OMni6rDxAVS88hUqxjo+uVQYKZNNHnOPbxhkqHoPM2M9lXtrtfV0XI71B4ABScnv/OQXSXihoxZ1g6JfxTVhdaGeHuij7qETViD8ngNy0L0LpnGrkAhhaOzM3JIUocdNjZBT4byOx3/R/b07cQ,iv:oRijg1epXHb4jo7SR9A7NpgcSc/yP1wnh/uIie1ceJQ=,tag:+dc+yOFrsyoPS5qWh3pXDg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSHZTT1hZMzZ6WS92dlpT
            Q28xK1BQcUlnNExoS0I3eGo1aXVoWDRrRUJzCnFyenVSTE8xZlpxclpHeVNybnRu
            OHpVUFFBQWxZWXN4MHlzcmhyQ3pYamMKLS0tIFhLb3JORFRBTnJUTXpWcXZZVU1M
            VTBKMEExaHhyNG9MQjRheHIyVldYQlUKZXwQJX1sSVxAxhPKOBZR99evnmQGQd0i
            Cf2uG5jjcKUKIzNwTzELSANLfFWK7gOtRkfViFB8c05cu8f0wbw8Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T07:41:55Z"
    mac: ENC[AES256_GCM,data:p7KmNImnUHkpKnsfSW2CB12WwEKpV2ucCYvuH6W0rwIe2Iud52cDDJIPiQRHQiFzFo7Oe8dNGHOEphALaHOg8R+3Jc7Ya2BeCz7sLYH3LedHiHjFc/GAuHT500smmw7VdlNHKL8BXwiA35dlLrCwJEbJSWfDOydzmpSDAxOx4JE=,iv:gdIIfhXbQxBJTNBQospf/jzZsb8H9zBUpWHIHtxI9o8=,tag:OLuSiIzANZ4Vlw1Nc0NMMA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
