apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:T4XM3godSb5/nyL6LFlsqpeo4DUjfaoSUZyIvGkYJTmUPhJSg+pYXCaRItthIyCQj6o2fShFHhLsOOsMQAyDIIk67FZvvUfKM1O11kDeYiuHL587cqyIJz6TBPLjq12jHZnXWwKEx6fJphiONWwI4h4g6OUKApUrwTkZQxgH4ywKXzkZuJ8bNoBP6MXoXUE1n3Q+iC+tpJiPuSg0v1I1ytykAkrzJE2Lm21wUjWeQ58q0s668r+KVJrEnMfgeIFO1+Jl/EF10acNIBL8FlpFzL1BJWs5cMKwxFo6tqa2MwmP0dYJeMHH1kR6AIHCA7Rr5KP2OaKQzrvhkkpl8u/+S1SL7hSzXkDvHartS3D8jrOoTKUwePfpn600ZUJhsBHl,iv:u3FBWOHp/bJRP6SAAowv/jXUWxZaXCdcuo32jOkrVaE=,tag:KKnQ4zfLYd5Wl463Nfinrw==,type:str]
    identity.pub: ENC[AES256_GCM,data:NyP1WGn26mlzMP/S3H2JZF96N5UCDfrl0iWS4HUKgvIuLjhZTTIHTZxERcbzKh5zF7RRyHriwafTjIP0U1NTxprIY2nRxuOmlOCu7dD5HRIKzRUgYGylnenZzVo5swgqhsjukGFoeyuXnQlLtC+gbLccFv+NkKe5KBgbamguOzc/kz32ycoIvdRhtphB5+RS/3jkd5YX69AcUmSm2EiEmS90z1F3hbeX7MV9LqTJSd10nRIe6W0EUiebW5KI+jqCwwxv6kpNiylRCOmFfQ==,iv:h2poc3wq454zANBHLK+aqpNxEjq5OxPE8212TmBm5OE=,tag:79Zp7boij9uNK59M7I5SUQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:MpKhXnmZraj3KA7OC5s2Pq8gcbzf8ng70qjd3Fsu9iFKiXCp1vjx5RAZW5bgTg1C4QLByaJ27F86hpsg4o/ecc1bjHWco88KCqOq2syp0qgnz64AcbossKFS5L7xAOOdrcPB9sQUAMFNpMsDIPS61Z+vfJtpORlUDGFc8G+pDwspTX7DEhdwOKZ4ENPFtU/qxLBrnoMKJcEmkNgWUC0nosgFEPrHIhU04X2o,iv:UWkmPBcQJ+mM1uiRzE9inVgTJglWVM5k63GLg/qADRs=,tag:WM/uY6w5/mpGnEH7TjbyNw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByU0I5dGJKdGFiR0hvY0Fp
            ZHB6eHZiblVDNi9tYnNRMkZ4U2xURHo2NFc4CnNzSTQwcUp1YklJcWc5K2dkNzM4
            ZGhGNzlLWERCU3FYWm40d1FsNkdiWW8KLS0tIEhJeHYxdEo4NXpuUzVHT1hORlBv
            UGRtN0FlYWZvMDQ4YkZPVmJPZTk3cWcKWvM1U9c3gUX0wfwcFLsXoAmuXguTo35B
            GYOZe/5mLiQaovfmoaDfgb8V34ieNHvMgKINw6Tt7iQAqAHr/Z/+PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T04:25:18Z"
    mac: ENC[AES256_GCM,data:lsBDSQ3uJ8Cf/q2qXb301j8crYbdu9dIN+7bYYr/St9IzdOHhb8vH242T5+6JpjNzTfh93KwsILDn8WqpxaMIt58zq6eqBnk0vhBUTuaQS2bYb2GBKvkqg7tPQ63iXmT1aSv2QEmer/AT2cDxSU8lffcuPPRNODAf0eq9Pv/bUI=,iv:kbd18wzvNNX7/DiWzM6eCV380vdj4mJAG5VHp6LuJMY=,tag:KCgcx5JUCOEubkWUNFcaLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
