apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4QLVLASa6OhwYiVez6lnhev6asv3NNjS/POFZZn/xySNJZcpi21Jkjp5ckEqmauoHaOmozOJtds/jTf5ibSvXCaA0lst+gEBLbQmiayk69KkYPKUKL/kikLhDg+wKyo8d6YLJtcmqnr3egq1lS0XDRHONkQZGQBJ/VqbeyBvp4+1T0tAjrpLjurNmgXhTgE0LR00JsYHdSjCgiMmVuO8r6E30C6QG3ZvSgD4kjsn/vG7O01EeOe4fsQFPMSIRLZc30U++bMK78iioWWdjgakKuCbtk5eKWV1NWO/d6aOVM1r82OfvZIOcezyWf3tAKXJYa1j69ZPO0jrRGYSg/SZYn7qFCEIFwiRRYJIemUysKOmBvfcnM9AILaC6S6mcaDR,iv:Og5FgkvzHYa1Actgzt18lsBhTBEM5lHpKMu2RhXnAHc=,tag:XPkVhKkp39BUS3fGrmj9Aw==,type:str]
    identity.pub: ENC[AES256_GCM,data:H8sKTpHHQ3rShFZ4qHBKqpwtMkXM+pUF+QJJCSA9BnEkJgSDlD2QR11rHkNT/hf4/NCUrTW1euWfuHidSeV1H8GP0/DM3F9FeGQUvdMCzD7l/ZtWphx6OkeblnjA/vWCGzj1DRmQYO0XVFwYO7PM3PfHSXq3/TFDZgtAnkxuuWegHdAsFbAhu90+tpVJLPC9AaC+dIilTfTMBI8qVH23MQxPNFAGyAMPVApCiJvLZRflrm1YeT5u1iUapH6GvJpSWHJywym4efqtJ22jeA==,iv:ytiRN4upPKMuduEwtRtdHgOWw7FTwwQP8NFznvPP4cI=,tag:xp6Vt04mZez53xuABIKpDw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BBuhm4nXgA5MKPM4cKt3g0KiFWWBiKNtUpC9BuxMQk/9BjCWdv8mjRbbeUuMRa35QU5QH/HtpP9x3t4T9pTq0Zx1MEIdzOu96k3rgE+QwYAa1pNsepY8S+Fw1itozBsVIQoH8B9ocSiVrTOWxvidJqqSHhpNMgOutK70xyLPRNiKiFnEy7EVjiw7BxlTsNvrkFo+QdhYuyGvn+6vJtp8heh+6GkWboqv03aT,iv:sIw7rEk5/kLiLSAQWSTqlENATDuPWl2UW8PweE6oFRs=,tag:ZVc+qlPFclvkMuJ53mkDkw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL0pmTFlxYkdRdXdLU1l5
            RWlhS2EyWnUrWW5EK25tQlJnOVFkZlhWeFRjCjFGd1ErY2NDdGZHc2lmV0ZIYzQ4
            WittalFGcUUyZXVJWmw4b3pBWWFFNW8KLS0tIHhZWHBPK3c5SXRCbEdxSGhwOEc4
            L05DMEVkOTJ2anRiNUEveXRrRytSeGsKv3/IX1t1mMi7DXo8XJPpYxK3comJHYvd
            9Ww1fa0VqboT/g2+yfT8BvOufKbaAo/yl0Z5T6d7rLTGD9jz1xs3pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T22:38:04Z"
    mac: ENC[AES256_GCM,data:7cllXIBFoACRj6OUOfIsnCEQ+xxgxeOoq/muV8vHqsNHKOqegthOCTp/P4/X/inH092M4RctHTT1H8BC/Hk8Vo5bKF/mZFwHZ6twsv6TGiNPaJoefBqDPRpxgQJ9YXfkpESTur3NfwCFS7dbjxZwv6Iraao4YCPYpD/u9GOEc9Q=,iv:VhsScbCK385eQj6hpd+yadtTtyX6+NvB3yVuGr92oBs=,tag:nc4ZRG7bFxnQHqiyXBxp2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
