apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ycMfpPz0I+IBoZka5AbngqnfTwH4SYqft+VSoQsqFzDMpyw+mTrAwD1G+qH1a2erKg1TjVnBLD16YYhYEM4hYAhZzeRE7aC8z+Uh07m+85RmXuxZmgoy23chgCJoQ6H1tZvQSV6P0AkYLDCJLl0KMWFgNDsJ6WUugxBA9jheQvKV1n9g1XYdcJfMVnW2suktOY68TZQ2KR5ijuVQanT92XKLSefroSVfhV6jmlI6uUdOreSncgaO7iEtItGB5XmEQzQ2FnrJpvx7XTNFbeNT82WzY5o54WzSR2+oMtK18m/vcUIiV/W0SVy+wzD72rZPw7G8xnqISAygViDAQEHQ0+Ll46GTfRhYsd+8IIfJfdOrs+Z24icEP7hQSdNlpM9e,iv:4WvaY6DuYY3ivXT/t9xpGhzz8jMZawJGzWExqKJdZGo=,tag:CtLWp0XAiV368eO5EA8SBw==,type:str]
    identity.pub: ENC[AES256_GCM,data:puWlpk+68BMWgqDyZv6CAa/Ns4g15jZpvTyIk85AlfNJ6/GHzJkuix+oW1QMki94IC5m4101vfg6jcvypEROIgAoFGPnzc0cnJWxoQXEZJ7O67QaAG0fIohaZHd4bgUJ1kqVqvxvwzOaHZ2S4mk6cZQlZXmu3LN7UdNLFhzMCkpZc/oLJXTysd0XIy+aLBZqfOvaOcy0gOhSZUylmf0w4i9MbWVS7qcROh7Zb9p6yEmj11B08w8j3UcLfutNDHdkNsQz0Hdz7avclCMkrA==,iv:WaeIw7yGt3S1v/b9kGemvPC+51bn+mzLE8ElWnYetlE=,tag:E9zOQQDehKwxVzFtjaCVdA==,type:str]
    known_hosts: ENC[AES256_GCM,data:KZoMBdWNEi/H0dhN2BkH4zJd0TThMBDpXAurFXj7io0MCenxktyAdVEtzRPRMzHNSfw/uRM/xu9gVWviFxUlP4ccCRK0W1F1yvDD4u90XQFQSK80R3k2YdMbR+LsBe1xOZNaoGR1gj6GOkuXd9FI1Cv4KSnzMgBmZNvWcxTvVsb67yc53wnAuKh27H+ka7F/sTuPzl8i1w8dt4nRHbs6uKYSWP8qClmCX2KB,iv:G+WZzWO+JKMvZtwcolhRyVg68MyK0JZuMBOsvnAnbGI=,tag:K0pess1Jr6pO+idM4dhOeQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbi8vK2libWZsLzJWS1Nr
            U0xiNGp4MExreFlrcENGMkRidlVTY3R5dzI0CjEzVm96TVdXUm1FVDMwK1IxU1p3
            RDVDaXUvMU9GeGIyS1BodS8xVG14TEEKLS0tIFhTUkRCQzZ0MnFqVTN3WnVnazV6
            cjMzbVRoSTNPbzREVDBlYzFCNU8wNzQKFsJdHAYrkjbycNnBDt+I4T7GeBS3GuoA
            u11lXa2TyMkNu1SydM3vPCCWYS93GnrFB7Aho1Z2OnvBW+K5Uf4byQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T04:47:27Z"
    mac: ENC[AES256_GCM,data:6gcU+va3+3iwTxma8g6HPWhmn5jeQtZriY28MywXXgg8jPBnyHae1lZW6LDJB4jwcYjw2hjSm8a2bqpv9jnbMFeT/I8bXTq3OrilrVG3UjZ6Qj0BiQ8LsjADp0zBwnEkUDQ+TTqX6Q89NtonfVyv/bWTiRa+qOymkTAuOho0jmc=,iv:IdSA1Z9MZCr935rSXNRvCjK60uOwR26lt4Pshk2wRVU=,tag:WlhPfPKNsSTD8wrMQXBmsQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
