apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Nz15vyuyIcCOpMCeLiXUm57FiQMT7GBem3kMJ2qOERrnC3c04YbeeTLGxjJFreh5PXxxw7JZEiyZ7OnIqC/xMmkQIl7w3WylkyIkGc5Dzn0XH5w8HqgRweeV+l/Niz6+Q/aex87rgxSGRwHDkOOw9M0j9LTtwPajGzHqji6YK9Xm7vlmBf7KpoJDqw+d7SD75uwNAw+s45bvqINRmlJCxr87tkxQfHOGIxBqNEK/JRdb/b9jsCUjU9fcoMKcYQGmpBm7TKDsWvDY6HvPI6PBlFRfGHVKPR9YVp5J+oMnhqkiP7IHgWUrCf6SIEl6AJbG+1VtT6uvDnJTomku36caChjblmX2wb4PMApQxehnGem0jXcgqC5V3Fb8Hq6f86Ef,iv:SoqF8IxRdo4X/51J65T6Dz+/YFsQIXZGNKU2GTb3tRM=,tag:SfrebuFJcQPpBP3EMDABjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:9jpPrAmNPSMUW1hkJdzfuw+GQ6dBgFJSEy+koPwfq9gmila2L9re1lFNJ5T8ym20s+9IAJhSHBFGmvwBk4iIrEJxKsP3AOHrDFg8EGIkN2kbaKpItwoOnFltFIaLd+2blHzXYgTpXmF1pfMcW3gGBhi0DT8LSj28BvMix61qarVHF2CwpIQjbHigClkJffW8skYY4jeaV2n5ZjMEpL4hAndIAbMPK9JCJcyNFyOE1v5jSmYoavDXjnTVquXJw+pVf2+DifTMz7h/FSPrrg==,iv:3gPd3LiGF6N9JRP1LF6FrqLJr9wOKBIdUdZu7OdEynU=,tag:6woxM5vREh1oPKukVFRoLg==,type:str]
    known_hosts: ENC[AES256_GCM,data:/mzaMGhG0tC07aLV9T1pi0G00CNpEUehtoQcDikcMhi15mFNnmqNdw/uGTLnXLGSa9bNGbEFbrpOLar0zmgpbNi9+TeiC6yGY2FcRm06e3XUxuO3FZvVpSvYmExcr6HxBzlt+uYe5T4ikazyVZs2mr00LRNjFC9iBhzNGQIOR/pzvxKh2skuHx8E/Jq1BoBfx+QbT8zyNsLgavXDDShBTqSBkyHIb0M93gpD,iv:ROqACrGzb+U5/YZmGZPk/WFmyYpzDans6UbmSy6b4J8=,tag:oE4td4UQvonsryou8usHuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYU9ZR1kxNG9QUmJWbW5z
            MWY3alcrRXA0NC9WVlpKcEYyVytIWHF5VnpvCllpcHVBSzBINXhod2phN2YzVzFx
            R29VS2pMTE5qeEN2L0pQVWw1NDBMRjQKLS0tIFhVbnphYzVHSWR6MDJIRTVHTEpP
            cmZRcVZlMEJSOFBadTBsSzFBL2x1dzAKnTxVz8GFv/Vi02QvXmKOkPE67ZSkU8BM
            Nzvi1pRR/INFi8B/mYvmJZo+zye8Nqi35sal94FXr7AMI60kONskug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T02:03:32Z"
    mac: ENC[AES256_GCM,data:oOpJB78zaWEtCvWm9Qm/+HstXbs1lwZq33HzkD2exbv7cHN+oPGJ1JdagAhcP4ctZjMQ6nP7jAToyZOLeex6WBr+4l4dk+H31Fx5ENTEOF7WM7/GCnGVIdKf59VFnwj8xiWVUFyoJIfH5yueyetE6SeuKxX5p/H7FQnff/uVI10=,iv:9lTaEPZSJ+3y31uLPMDSBZWHthZoINpF1Vo8qKzmPUQ=,tag:dW4PtMglGBbQKW7Gsj0S6g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
