apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UJDUcUmZ4YyUWKBJj0riVqJo+XDpnLVewH8Lu3EBQizwFG4ZyZgaHTCl5zGU6i/U7Wj8ka8/mk4U2JHX23XYvF/n66RQPeS7v7g7CPvG7hVzXw6sLvcZuvd5lmVxb8R8aOxYjkZvBUG4QLTqA5zByEZbkjZxkIUnKCkRBXLbWVTqEeYKL8gcZ8CPiODPJPFYv8M+nNfZ4uX7R7QbVhX5FsHzlKIq2x+HPZx5SZ5MIoDvhsw0OuZUFmr6orG+A7Tes+ag+tl82MfREjsPTe7P4S//odUShppKD4jzDeoKir8SAvWxkmyi3mYgbmGXn7F+kj4fZgrnyi8KEXLK3h3Bvf2VNda7cttFEN5/jeFLcGXU5JyVXt6kf+mjYMMiY7JF,iv:177AD8TDPMGdjAUmMvyxwHkWhXJcfe/6vZDwkBSJTl4=,tag:Ow2KSk+Ji5hwIPUbpkUcxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:8dK1EWId0LvPhtt2zK5pR5Q3QV+oKOMtIYX7HcUSRS4R0/YPr/ZY/vTBiQyXNWcCESPUKFPybIyb2STK7QIJNkpEhYeBmCow6Cb9S4U7KIpDTjeVE9pEaoNNhPqD6TSExp6llGwpFa/nKMH6/Qm0eEy7+L0tEoqqC2Z9cgz4zod8KhkY69B//W/4oRluuwKin+msLhwcpfpvpgm5OrnZRzn7HIMhVzjsxQ5LII1vkUhhVnevRPrj8XYEs1X0oX1Pxl/BtfyGIw3ApcjMwg==,iv:HzmKmjkYmv5JlnrVo5PWIFo4Y+Y4fS8RT+pxuCbJK9Y=,tag:xFALh9cy6cjvuIz6Xebyrg==,type:str]
    known_hosts: ENC[AES256_GCM,data:FVows12kZ2IdJEsEqM6DW0wIHlT0sVyRBVN4PUcPquOxwY4tIoB+jwUbL1yFgpwyHQ3bu/tfIooTgRwA3/peOfRg1lcvlk+sbSs5i9jm1CkTzndwC+RSsTE0UbTawzP+OVoHhM3DsdSJdn1N6/lX5Zv9fxx1KSnRZCNijthElzSZVwZcjKCl4SliAqWf3uv9ROq5UKITfGj6xxNvP2UC+cGNnEyCRo7j0OsK,iv:7h55oo0/WfaWDaYePozu9MBGr4rIowzh59kjNwAb8o0=,tag:TsJTNx3WtOSoRbzKpm+nbA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRTk1cWJMVHpIaFdFMTk3
            ZzZkYnhZamcwZ0RhZ3AxQnRERWJwcERYREFJCklLbDQvU1hJOFZJNXFrdzh0MWlQ
            eFJNLzlFSWJKQjZ3L1NlemlSUW5iNVkKLS0tIDUrZFpWTHpHTTNoRkViRHBzaktQ
            T2ZCRnFHTTFTSXFaYUVOVXllRjUyVmMKZuFwc+YIiOAuv/4OV7bSAGD0FOO7q6yj
            jlsCeSeayYxDrys1feLtC55tjckpBGmh3YyL0QCfc/bfozktrWMINQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T11:22:39Z"
    mac: ENC[AES256_GCM,data:etnbhokN2D+2KVxMfWp+7Kn1rW57gK24LICOEP7CQuEBOe9sD9neC5lq1qAPTgx3Cd4RcPoh5slD3RienR1M9Ohji1IFJD7FXOWXE7nfXKLsyMTlO6U7JYV2VwfMcraNYT5eLc6rzENzYNmfhgcUyUSnen3TFdXCdJybT/RWBLA=,iv:+z9xWRShmYEC74xknCD3U81vJRnd1ftMVSAqVahLobY=,tag:NO0+Mo1fLkl20zZ7MFwMHg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
