apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:op/XN2mw4/+gM0bfXJbijGRRk8itNo7n9EUt7M4YhUlJkKiUMRxCSMRs5R3f1Ez1z5Crv3DMUcPduIAV76nbLzZSdKaj4vB8QqL+sjkib3g/zQgNEbz23p6jdIcN+mF4L5WiC+gfATBfIYQMx/nA+FI8Psx8sFfoPGHCpKExxooL0ek2cmHIENcYXnLTvcCxgy+ySeOpDGbwVtIBDrmGn9ofQgIb+csMUokFr+jGGnIrC64HmnDWOQZwJV5A9+t4wgSwxwR7TsRXlIz6RFdganmHF5MA6IAGf6YjtlAcNgAx18BKZekFAWgNDRa21V7yW4uXdfG9GX8VhC/wqHIWiz8/iqEP4Lwi5tkCpasvRhjgTOcCxvCk8NdzbL5WR1u2,iv:CsgJDIPZ37A3oqyDATjJ/fWcJOqA6sTLzRJ/T5d67NQ=,tag:K/p0otJ4DI5TQNzjGnXa8g==,type:str]
    identity.pub: ENC[AES256_GCM,data:3omE9lJDZ0IuabNnjhfyx8ks0zp0RYCaYbLlE2APr+G6Jl6s8s4vRRy0G8gicpx93A4qfEvO7PPgNcosHrnnAXb7LM3u3EgGe+mdL0Cx09WLDBbV+9SxFl6Ka2G8iYb26m0a01fRhpk442eH6owOkRhc+LHUIRwp12Ao5jbnzSkaOa3vfzXL2L8pLTrgvZIetKKQMKEaZQiBkO/Bi7JiBqBiiXPrjFrvSV/ckc/13ChLVtDKhe2Ct2aMiN8rc6FF++FgOFN55fff+VX03A==,iv:PndDMB4NrHVQJhYGTPo4nT/nUd8c25TDKgfTmCp1zDc=,tag:yMcKNyeV97K5r8uFjgMNeQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:UCoYxm5sxkUEeeu6LOKw4Pvj9twlf7gFCMtErAOXKeRmmjMXfdyMlGg0Rm2I/pfxky04m85iBHjVnHaeWl1jCecgD1tEhKgJU1653P2RKsyZKULvvh45xM2g/j6fZOoFuaqYzduA28pb+H50E9ci939XDDlrUO88kFFIItXyAOtoiDOQQc4cATyXbN4bsGra9ozY+Lt3UkkPtTNmwIxX6wLH4ZLKTNnnZWmI,iv:s52GZ94XtccK5BkGCnhVmc3qdCc4t7UvgDEHKqTuPu0=,tag:A7tbHoyD8DvXbypRLYM+Eg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYzBUY3ozQVdsN1RoYldv
            NVVVQnVLejhnYjBVdEtzeFhkYlBUSXlUdEY0CnJjMWp6YUlNcUMwOTdXWkhqNmU3
            RmJISytGQ3QrMHc1L2FpWXFhbjNiQ00KLS0tIGZhZ1V6OE5wU2tGZHlib0wzT3cz
            cis3SklFTmdjNWRiSFAxQlVKWFZKOHcK1KZ2WHhg6Gg73bbw1ylyQqCqvg/KU7sG
            meb1LXduv+FfK9g7ZOdMCUOUHk+FIit43HjzpDoquU9lqWfesLancg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T03:03:05Z"
    mac: ENC[AES256_GCM,data:suvJzv3OR3vNkHiXNZDmWyo5MCYpHKxrvXzLDN5uYRwYYY3PVP3FxtWz4Zap61uo9zOmnL75zxpGdP4HtisYB5oieT/GFcWoWCXlnojjVHuvOlL+pPrU4zTe+G9zqDBQrOvyE70YlBIH8it+/gy+eipm8TK88jaPc/C5UfcAgUM=,iv:ollXDvDeswWmp3xYtcF2W7ZyioWdHhTZXqn1qKXI3bM=,tag:lj+cnsrHSxuhRj3MRu55Kg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
