apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lhddRR2o430r6uranpCVIaYLkzALnwRnOs5f+wNqVjv+o9hMbaW/EZO7zARmCm6ME3IL6AUQ79FjphmNguLkSEZ5+tdhZ7Nj6sRFrYdxLcbu0W25FzWZEmBACymYl+46Pyxa/3TZeABWdH9NOL7bBMcotYaP1EGDGqoHInMnYFFqeHxq0rFWBY0aDM6rzx45l2UyCbATbk4PEKy2XNSczSwZ1GOCuCxiMOECGSs1ZdsX/BAkNzwne5iKrAZwwdc2XZLhdaQVBf4gVqXhxXjp3WVCreKwotq7uh6wSDtBX4o9WzAOrChrNwBaXbRmwDubs1qrksAsZtzAUWo3ZFcZNauTS2QAUex+Dqs/Ux+frBdv+1APFPAlmy0VwpzjTnwm,iv:19/sO8dVndHPSCqi8GPWNwqZ/l4zxfvh77g2E8ilaxQ=,tag:pOtUWtZ9Cv5ipFEg2VrMwg==,type:str]
    identity.pub: ENC[AES256_GCM,data:u3GW4EvRup76lN3BVI6pcN14OKVfhFGc77mI5Ci4LLloViuREpwVXI8/qDETPy8GnMJwOBq25AL7wiJ/04oc3rhMEn/2Ia9gYNR51/p2vUtnb20pmn8WuqZ8atmycEtNASsrRixAuDYop8BiNi6OMoz1RPPdhXvInwVuYjDw3zftgY3jQT2eOFzjuDgL8dMPIaHxyOANGoBvbyx5esfDxqnAhEyW7v640yvj2gRUOhDnUeob3FjmRTwXNCeEiHwlGmFXqS6cOjlL+X6dhA==,iv:vMBc1oyVfnM93WY76I0WAKYNF9JkSjh6eEwh60ZcOy0=,tag:4bcwgeRpZ4zQUNhyIyYs0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:+bGcdP1ZcHLs7ZxetGqZxVl1ScgCxDBpEQWbKmGG26ncJzki0fWRy7B1U2hQxvUsyPr9px466boAyfugJYxZB1lWGCVIaG+BCF7HEEP87RS/KUIVDqyIqgVc93Teg1Ol8YhTSMrxoVq7LDxSYr/Zc2ptmAET9L97iMVl9ELrZ07IzOCE9rz1jhmofJWz+7UytLc1YzWInInd4A/VPussRq/1/u+xYFKnxvF0,iv:Hq9gk7mDwLwWMVP6ouybC4a/DhG04sG5BodRbe3N564=,tag:nU2tFVLvHxPHLl7C+uBhEA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYXczT2U0QTQ5eS8zZWJh
            NUI2UmhURUhHeXFWUXNFcFdSWEJEc0JsQUZ3CkNvMHBpdkliSXVTcksyYm9Ibnhw
            QXRuL0hVN1lxMGNWakVBVWQzNmdnNFkKLS0tIFhKU3IwVG9yZTI1eFpXcjl0NWVF
            YmFFei9sOTNZZ3JyRk9BRTVPSXlwbXcKJ9Z5FUUuU8jQawTENi/FTY82JeiUhXWv
            i4HF4hejvTBFx4ttaGFhxTpBon1CzhVjgavMeA7vM5jz12MaVk60Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T03:56:05Z"
    mac: ENC[AES256_GCM,data:ounOxcPUOf/Hctr+hRxWlHWdqElrwqyHVp7uz6TVc8GwzQXCdYQfveDQ7/4mUfdbaRuLAaIXOOushLj0VchnlolD6yuEDu2JQnzH9y2tlSTxbEFFUsb7+yaHPsf5CD4bHN2FIS36twU+9zZbq3Fwy3WO/djh0hfWjS/pwuoUP5E=,iv:FlTXbjZOeEEq5g95faDqyAVatN9TMwaRAgi2RA/NFVg=,tag:PW5QW4e26gS3pZD+v5J6IA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
