apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0XlcNvLq0nMb0TIR5XSWEgAM/jfp6+cyqTYcU2Ug6WJv0aeAyqqoqUn4VeXeSgIl5uY6N3nkiv0vJCrULpyAgHrZFuSuQefyeMOO3fUQziWrPPwh+jGs1zg93I7JKiPBL/7Mseo/HIy7j6vuk5b7c5E4GENNUKaGLZi4bnY6mosWb5RNiFTAnjUN2wXV2zh/e7eRhYAKYwkzWa0wBgGTGGuhFaZ4Mxq0RT93zZQYl7fYZf0G0KoWRqoypUiN/F7Sgk/9obktv3KNlnPaUR26iHZhgCvi1OtaxQvfwhSNreOWtMn1Du41JcR3AhaIJ5vgezt5t57ni0uknmM8H0O8s1V/beZmcRiAujbsZhWYG9bUWk4mbRClOpLv+eI7ZZNm,iv:LFGHUKBkPzCl781q8kiNjyTZQaLlze94kM3+ltUkjcw=,tag:c305yfFJePH2apZ07+jjZg==,type:str]
    identity.pub: ENC[AES256_GCM,data:9j9qPAGl+i7YMjIHSOwi+RVXY5RNRJIgUooPKNKQ1pNBfgyy++MBr4PEzFqSAPfFJhGb/YtgRdVPXzrU2Zmbb0mwl2RMYe/yzHR0DIO7fDs3UH5iT9NIOxnspR2RoxVTt3MmoTK6j7E5G3bM1AN31cWScEIEYTFJM6AI2j33RtU0PRoBH2PJ7iSG34Ra/7Qh8vamIDqU/KNNNQYEkp3oM+ujdUEdhJQj5e69R0wUJPb/d7QS+b2FONHczWCFm5jWFY/ew/0UfUwDCMC71Q==,iv:SwyJ/Dxu/N2aGGr/tPDWrU6O/YEb3nzB1+HSPe2qycE=,tag:G6L1lwBft5MfjS4mIPp1EA==,type:str]
    known_hosts: ENC[AES256_GCM,data:UdfA25e97o/uIAfYQuN98c7FXLVn7+Z6nxku86/IER+tXWtBAfzV2rRmUAQjvapo6MCayT+/HF9PSdYypcXCLOa67hYJkKuU7fCstUhOgynA+ii+AWR4dtbzE6VCx9NWOZ0rvnrADyJPKiGhkCVeAWPxMtMMZpRiZEiRJniXlQ/cjk4jNujN6iy29O4f+6sn66yVMbclLD60iQKkvJd2B+E2KZ9z8D7HEEb2,iv:xqmWc1nyJOEn2pnNX2SzngRSNzJ84nVpI0Gy8Ldw1Bc=,tag:umddD6LBlEjmg6VL0V7mEw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNXNEK1g1U1UrckxLczRF
            c2daQm1JamVvblkzZ2pOdENrVVB4WTFsazE4ClJVdzhpYkdrOFN2ZGxvQTV6UDlu
            L09RcGkrM2ppTGtLVWxOVGUxL0ljMEkKLS0tIHh2cWVZTGtYalpqM2ZDVWdqWVRB
            SzRhb2tvWmgxSCt5d2h6azVjUCtKdUEKJCzR37QhhUWgp0W+ZyC5Q+SSE2Dy+OZk
            jFIaHG/YOI7S8ROzjKIvmhczBmWW2xNEkJ1su+G7CF5fkACi9TQhFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T12:41:06Z"
    mac: ENC[AES256_GCM,data:riGwDxYlKN98V4E2s5IuZID5fvXHQH9/K6Gg7YO3A1tPFo2uCUHqAQ+WcHqmaAnT/CuNnn+UOKi8oQKHpfvGUHaV1G9IukCAvUGGMZKwXnNeA8V9bFuB6QzlXHnNX5qSreb7Ti+w2JcghfIsa0b6Te7OqJ0L49czVSUikmH6Qik=,iv:yf/B1VqBUaWldn4r3ZF/oa8KlV+nls9K4vNdY5Dukl0=,tag:BW/Uq58wjITKvon0TzbUBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
