apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yqTXJgimgBemwLCz9U0+tnuG2TP4dSA9gqTP50u7vC+TuFy5ecHNwCjcFbxFkSyf8Pwj/iEI4ZPe9jz+2usItKdEIADEqzx0AJ2MUMIGV0xUwx6uCHdxtbKrSA12+MjVrkfX841RCPGW5JAbOHcnNlv0Ps5Y0WFRmRe2GyTYS9Od3ZMe9ndfzFVXN1Z222SH/E/paLOcaZaM2JLEiTGa9UQgiP81SHao3FgvSQCQq9t+PafArQ62thP/zHgjzrgdw0bjGW+a+2GGLwy+p+JlraVKe5n6W9if5uTYdzANS3WRww371q82yBeLSM0lKt80e1gGZzL2bx5lXFcFLIhWJDf3sDCx4BFULsBtFAcBISnKsWBKiCMRmD8NP2KVUc1U,iv:2mHSzD4Rw3vHAWYM9yxGzvm+dliiLYAYVCO+wOlhUQQ=,tag:PWjKw6RPnoRT58FQD/59dA==,type:str]
    identity.pub: ENC[AES256_GCM,data:wMwH5kVqj9SbHHQ7XAtWAKu9HmO5T+PBo7LVvB4BdaxiV/KrN+bIz9LwBWOl6b5dZpbZrxz4zODoV5V+f3bjF3pc1yX9bAejQDyRQ4mZx4tHtEJ5fYtTnlXbuFbdfes7A0HisOwiGq8IB9vrkdOIASMPijAvS6d+lh25umUMh4vctiNlVvAOostXCQPoRhT9Ib7QBYj8agjM5N54iXHVy6Ns++0GGZS9x7tJpN9bs/dW9S7k6NAEu7KQfmTMafVpAsc6yH9hzAhaSkuosg==,iv:jvD25I0rHjIz03fIU43AxEzJ5T5fBXmccjswQdHbiqA=,tag:VA7LCwqwd17kK+p396L6EA==,type:str]
    known_hosts: ENC[AES256_GCM,data:frf2QhOw73Ojw0OuTsdxSvUZpU+jX+3xcHIVwG7qAj3zS/+5F4l/l+AP0tP37bHROYG3LQLdnk7MIzWPzJgZn1ijAPzwdKoKmHKNR25DrvpA8ghg7OcoGF0uYLFbPOzeYEbnjzUiibjDHlVvSw29ZBRW/ooxGQcqlvrPTWQc3CQSF5ML94JUrCKfPWAfScHxnfc3NoWtxLX8+AT1R1PxLNiJwBkDWt/WaCT0,iv:OqFHRZdd24aGxhIRbIMGlGLoJxJEP+TYijx7rdWvRwQ=,tag:jQfswqUh2XEdzatff0XdXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZFgwbDJLKzBDc1duMmIr
            M1B1cDhYNjQ4T1BiUDBPcWhtbnR2aWdQN2xNCnRITkRnSHpSSkJhOUEyRG5ybk56
            dGVrZjJmNkNyY1ljV2dhYS92bHNleXMKLS0tIDUzQVhTNm0yMm1NYkYxM2QwS25R
            UnlTZ2hOeWlOdE9reUVBcjZyUHYwV1kKXU6760bwnHqUB5oCvLmdYeklxth4585X
            sk9inzzoAvQCVjSNz+qzsgjhXysgIWLdeKKBM8o1kyhL4grDl3Vyeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T03:05:24Z"
    mac: ENC[AES256_GCM,data:JHwAcokY3uo/x4F8yV7/H7k0eQ1FV2qV3h+OpqRWPEVDsrwtQN0KvFbbU6Qv4VLo58Q9+Jyxz3sFJuUnjYpr1eu5VFkRUtnD5hSjdeK4fPw1cNvlGzZ2YCPAFmnU23AJFq3pxxOqcyx8CGKV4Q4EnqpinzPqJ5F2SlUzskB09f8=,iv:NgR1xHGSaGUgfc+cKIQ5sQt81+WkwIxuyb16hsVyXGI=,tag:cmyoVEhcyotl1KQdzwoneA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
