apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:M7ObisTLcxUZgxvl5jSyZo4C3iVmxs/zvz/d4BTvsjlcsLlsGU0cADqkErE/kNcb0o5ZdanDyVeO9fHt74PVsOJIrNS8NiSUHwJhn0KVrNNao4z5huUUA6iE5VgjGn9nhvS4W8OP+XrtRhaPylF6klBSUg6ZWU1oN2ilcMcIbxGsE0XOYPWvEn0JeukKMGL05XV20M5xTr0e5yOogn69TsrWdYhJmwv9TNbOzlPvth1sRmNr2jm3RYgJega5+AKsb7Jk95Wkwr+n7PhahuQgMvHByvB8DNnpa4nnjI3ia9WsMglytyM2oTadb8yuAYvJSOV9gkdLiZOKKJ00jGlg1sGuDkNPmo3ekhIWNE2qIXfHU0kOtH8M3Mg5SvSQwUku,iv:NB60Ln36QuUaQk43v+aH232bbUN9uqX4xJDSp8ymLlw=,tag:kurZFWJ5NMEOAvhXcfgbaQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ehhsGhCVAcuQ9LlRTkA2kXiqX9L2kBeTbyf81aCLfBeo24/yNSYRrt+XJrjaOttD/6/o+GZDAR8aLEhoJDirZD8yieQZ5Lvr0XTz8dVwwm+2nWnWQuJaYi91D3OtHXNB/pAOQL6g2rMtSeuaCJreoxTGQfjkRnXvXErR6eJLegAaP6s+o0GOiOW2zfH+Q1akRb0owYvh+9j0yxm2PkrMhUriDm8pj2xxdO/RUUmgByUbNVHO0/dBxEmMAsuJuZP5oUIcJfiMBh7ZpPWEEw==,iv:uMfkMewZGGzhr8JsTMO0Oz80rNnxzKBNnz6qurn6ZOw=,tag:u/cLj8Mw9QGs2ehWZuAAhA==,type:str]
    known_hosts: ENC[AES256_GCM,data:TIRNCtdFKVsxFZ48a6l0NHmj+bi5UFiKiuAQn0Tj+u+YhImJq5irZVj7WA1wZNJgqmoGD4dwASSKU5PacPHEpB5w/KH0kG8pbuqHXTLgCTu6vxZoqn+9FwJrrAYVF7KK3PfRWEqOBYATIxritXFp+8x5jMQmhSSwPnPqKLeEmKh+hdYezPz5fCtpXv+H06RJhEu7Xjv0j2MLoyp77wRu3fJ/qJ0XAxFpuu5E,iv:ZJHk519YHUyuUNT8k4ajzLTAG153oDzyx/k+gmyiN4c=,tag:eWQsnD7v27aOiPy0/TWYug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WG5NYm5WMWJyMHNna0NM
            ZzR3c0VnU0lscWlGeGFZWnZJUm0vMVdQMlVzCnJQOCtQbWJ3RVg0OEhMdDQwc2hG
            YUVkUGJsN1QwaEVyNEhFSzlRd050NjAKLS0tIGJmYlVwUDVqbkZrVUhBdU91QUxB
            dk9wZjVhazZ2U215ZGJYMmhad1UwZzQKpL7uPwADRA0BjO0/TmYpmvi3+nsf8Ehh
            48/vJNMfnC3hMlycxL33eywSG5spxbONNptVmvp6Wo8KYYg3ffH4DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T04:57:55Z"
    mac: ENC[AES256_GCM,data:ywxKoufMo9mVGORE7IOU/GhdMfaEfC2DdZlD6rPoQHcitep/0hjf+PuJpfXgER3yuMNDXsiN62Ofg4EetoLQ5m+A3+GXZ2pctTQJ+plmmWmYVGrDx2Yx5DZh24TUdk8Y4E2h7wyD00MwJMv65y+P1ghWbI+0nO7VAVbM2i3psc4=,iv:sHo++mXiJ+wdzbVyNTtmiyTl6IGJLLFWB8riFRfpKnc=,tag:rQEefvZ/cYOk+S5BU1/slg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
