apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gnfpKxZ4feSs04zXevMrH2PludS7G2DudaHVlMP1PluYHWCwCqWVPizA6slNet4clWiVrh8mUFs5/G6GFMJSDE/2wdNsvVshvecbqasiEfn+58qvGf3kXpnrr5qKVZIhdZ/gYz0jUPK1EyPnkM5XIH5VDvcVL17sC//DVo8/QNB3iNztQbD84PAkuZTTWxm4ge2vYbk6cCI+9WPVooT2Hs1heE0PtpIsylMltRwRFhlph0XnXrHW60qnt4XMN4BisVYf8gLCACiDsOC5QC113U4BxOgoUj/JcVz/AypEo+Bi9K2r1X7MwNjRCiuDxWtEib+dGm7bDmLA9NKuxLzmpknHvFpq/OvJEzW1evfot5yz7+EH6a5uJZ9fDH+Tbas4,iv:1wJs+TrCc/3L2+7y8x3wNkR+ynf0MGO3MvBYHGCsZc0=,tag:MNyGMO11+C++KrDMzCSMSg==,type:str]
    identity.pub: ENC[AES256_GCM,data:7Bl85Gm8/lXzMoELLgN4Axb2jDIzSeK5oBl/MxiWZxWCV3l130gBcS9SbjYtXqq/RSfd1YU4OQcmv2Vz50qal+lAqw+MZuncEt2WbqlagXZwBnnXhIqk5vd5XNk98ytWn26nztlBcKwR3MVh8+S2/yMqjfXySkgRrnzpXshEq09Gvj4uml1bywFDaci2GuOihbluMGqsagqDHTndAU2ielRQh1fhhaLX2nCzOa8yBfEhSBtME1Hif/djUCTv/1W6Z2kOWe7sB3Tlwuuppw==,iv:3rkfAvZwsVVsBazkvEO0/DnoZnbwcpQEH7gEndOrT0s=,tag:OKIqiYoPo+yCuVt47jsgSA==,type:str]
    known_hosts: ENC[AES256_GCM,data:FQi4DNkqWyThSJHGW51FzQRr0JwipK01SrhdnZLx9mBQ5NRet2LDNH0TPJCcmVkwEpYjcPdRYyQ1CwHvgQoDWUP9lwvJngEGG6yDZQWeL4X7b3Rfl8bIbk0cVk9cEWJm23uejvs3BgzG7jyvQn4O+KRzUA9KLwe7PxlBvY/jmJAcTb1dubeT9mvFrcyeyptt+2HhgjXXiKCrq2DuiKX0i4MlcFTbtJ3HP+9V,iv:zIpWv7y8RVV1eZVrZi6ZdzaZaljdIMQJsLlDGe+I0UY=,tag:rdyXrOt7ndJLUl2lfLAAeg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMmRpU2VrRXBZcXJzVThP
            blpWZzF6d2NGWU01OFk1anRNNVAvR0VMeWpRCitycVQvWVAvbUZTRTh6b0pRbWIv
            a2k2TVA3d2JRM3RzdVBkbjVhVjVmYk0KLS0tIDhXaVdiMFVTOFdsVTZPa2RTcmVl
            SFZDTzdWQmdWbE8wci9ENnBXOGF0MlEKMz+osjhjcOI6EATCWmcuJUewsL8mdOYj
            V2RZyKFA/uUkxFjGe9pGEUusJ/cJdj6NjWhk/EHmODG0gp2X3vR8dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T00:58:57Z"
    mac: ENC[AES256_GCM,data:onLye34/wtK0THGFie5mayO6kQ58jePNI47O97CqOtxpkcHS08AlEXH3Ng6z4MXap9lxMmKNxxUtXPQtnyvigxvf1cLR8v2D8XTqFMDRAhLTpa09GZ7WSK47JvPEdIw6pT+4lAITQOtS5OKmjBdkRas0NEd/RTamWIdJ7dJKh78=,iv:ZbkpOzxIdcWVCtiiTkSvDmkW4fFUY1gCFUyPGv0xk10=,tag:GiUEb2UxkHmfpPbCitC3GQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
