apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:79fPpEAIYxA0+v4m4Tv3rvtBdVS3C0KghxCE5vp/DNpt2peHWzp8a6R4qczLIzQsK1BzdMOMugg9PfZ9NN1M7BytgFssEKWkW/pMw0xyCLoEjztXKMedAjMfp8i63CzvsNnakCoWR01+iP3bBsiGVF0BWeCOxbx772DcTOi7Od4129iutZ7pew+AM0aGY0d9U0WCV8I5mduU937ZZv4Wk5tYx03B9MQDmLD2Vor6JCVSmsFBkt9nIGtVjlt88qTZnGVxUOQC1W0cykex5prbrYd6Vi14K/k0Ryum/7rLv/lq9n1ixEqRp/yzfriNUSmm0D97SEGe3YTxts/2YFi7CDqCKgxAeUUY7MXQtcrF4fBd7mv0287nAGLoBV7Jg5iD,iv:n9qXmIZu85kF9nxwQ/wHQxENKKSmlTR5JPIMHmS/8KE=,tag:/dZrF/A42XgGuDFQ9Jswvw==,type:str]
    identity.pub: ENC[AES256_GCM,data:VmM+mYxPkeddTg02zvuF6nrklfxVInoWkSIad8aFKYwsGK+tc4RYsh8QwQEi/dfAFf1uY94V5svxYRUNn0N565r5bAj3cuezsWZD/IXYzJAOM+FLdv/dCl/25stFHmyEGiN+sbtaSh4WBUlDast10Tzgv365YiFWudgZMkyYUc/FMtApvJ9+7tc5GGLEVAiwxoxozU1bUKqlKNWphiBKTLcF4ISuEvDuy179+tfj12IsDYR/U/f2rEqHHPeTU4ATPZa24hFBbJO0ot2Qug==,iv:srDPCbPbxP4nN6q1JBCaSGffIiTykjXLlAMPrJOIgUs=,tag:hAS0XohbouVL8eiX1t62bA==,type:str]
    known_hosts: ENC[AES256_GCM,data:uh9Mq8Vr08GugwSARcIYXyWj3scAAGytC1vC879Zyba/KM0uvpHjK6PslhYF5Vefc9txXIFXaSllzpZmisv2oLIBp0kbdFmn2tvKGyMS10PXGUnQHBvCPh8FQzZeEdRNy80cxIGqVMOQbuK7O19jgt33exc3jjgLwicU2CXBQiwyDi5XESzt3mXyVxkqaLAshLO79DOGiB9N6TILbu62LsMzVDVWgp9WOROR,iv:CjHxO7ImOTzo8yh+MFWCZsvkjNRsBnm8aG/V0s64gkU=,tag:K5l6RW7Wb0cRBNh93c+htg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuek1kZWxOTTBBRm1NSUMw
            SEU0eFd6K2pJNjRTMWRtTDZmS2YyQjB3aEFJCkVvT2lBclBmdEd0aXlOekxqOVZW
            RkE4c0lSU1ZneTRhVWs0SkMrakR1Q1EKLS0tIFc4cU96Y2IwV0wrdWYvN283c1Fx
            blk0ZTJRdVg0ZmttMmRReEZNYW9FeW8KkLw/6N/52eMHN73JcjyCv86et4TI6zpn
            j4ppYkDnyX8a7MfTOyYgyFvGEJFMegaEWw6xCRmtgVl89a/uyAPruw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T01:44:18Z"
    mac: ENC[AES256_GCM,data:dV3QwjRVqYfhMXxtfzkTEbvRiDctUK/2nOOojfV+05/PticBoYR6J51FDSpoY1jJmfYaa1G/2wGlUA+hLzRLijuEgZVkNNrPQEfpzoXkQL7y6h1hO0LI4HW5QM7xmVR28moKPQcX88nNxe8y7hMcBF9rD1m0VAAIqeeq0iH8DO0=,iv:qdiaIoyr+FmZAgv+RP3pdCdl7LBHP5Wh36jExsL8ckg=,tag:9YXKXWOQA6jwQqOoKRmzPg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
