apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:euQ3tUH4A9KtjPmP4LvFijV/34xsMwiFh3iynGhFUWdhxXeJSkBmd2hIYz5GEVVx6qVQ+OqL3QIAKenLF3J6TAHvuNIoINx/1Okf/Y85U9rRZl73rhYuM3V9l6MPz7nvq5QgJBf02n6B4wRKQZGeBin9Vtn6lpdzNKXQYJYdrpPXUWOn3iYk0rwvBeegZNPuIN0UmMXo0nxfpjixJc/lPA+M6RD9lihcz0mLZP4eBvwM2n44t+eQ/0iCxF2RwVzbDNhN94c/IDz+RbYoC9BV6A0OtB7itvqw73S+v3gqEnZjdFirbrB8Qv7gvmVFBj3YYel4kvNJbvKkWkp/SiXUfmoj6g5L+PQ9UNUYBgeJn9ZQTggnDRreFgqMHIAGK1Mz,iv:dwOSY1wETRAl7blof/wE29ASvfdwaQ/vhCQjClBU2as=,tag:hdY24tAW3SzSHDAFe3FSpg==,type:str]
    identity.pub: ENC[AES256_GCM,data:VvKACAAB3H4NkD9xdJx2rgIVKnThjzPfiNeTMB0hVkACiCAKznXL5xfEQMyledGl46msQRExt6WuCnJiubhlv58abiQ4ZEqsRMYwZvwfwO4TMLYdmyViap6onL9J5CVXQ5x7+njl5wFBpw3D7FKIXyBoNrm8hEqsIftLTyNTaUaejkR30jZd/LA3YK0mnhbcb9btSKgsLARH90PzYJXOhWhGd/8eDPOg0F6Y8Zhaf1N5I/DwOORj2mcg9PONbq+i/Hl0BJlwX5ZSmeaqag==,iv:vKg8qojNODhtOkcN0f1KgEtBLowDRN/3SU/HZLs40MM=,tag:WjiO2cqIY71xp5NS5zRmmg==,type:str]
    known_hosts: ENC[AES256_GCM,data:gcz5lxTmETbXqY5+7KTzwc2lVhdJuqylhwsaz9SmE+J61TM8hXvdz181mjB9J3TDdOGsfOh5KSn8zlWtZOZJwZ96Xl2W+Mbk/0K6ZKX7WH0sFSgMeNvfRLzkmUSi5NmNSxGgzT5YKKpK2oeDY7Jd2BYOh0Oi11LikE6kkINQDe8FMBiW+76lBM/99AAoDjmaKsYhVMbjqNQ+8wbxw1CCHgXSoYmoNibzzwU6,iv:dBu8HD1otDlPeZ5sjkuf+i8mbUO5v2HwCJ0ejPnFX7E=,tag:ZAkaHjWkGX0UQsg1Egio0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTGUrUFZ4RFVvUEtmYVUv
            SWcweEJPM3hpWmtBanJaSVF2WEhHQ3FYS3l3ClJxek9LNm9ZZEJHSXZjd0pFRkxv
            UzNFa2xudy92cDNHTHFvSVhWK3BzN2sKLS0tIGdhVk5INUE2NjBtY2NwdS8wNEVS
            TnBEaDFaRmpHd05TbVN0QzhpdmIxdWsKZBBjSx1t0Smu8eUKObfslKuu7WpaIY9V
            jv8HYML1NMpoHpujCLpTkRAG2OrQF2pf4aicaiwKZlHCWFqexuSELw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T03:33:55Z"
    mac: ENC[AES256_GCM,data:xPgNpDC1Vc3NCyOfs8n/fiG8K+nXaVeVQ2hDk6TvHn5NE53NH/EUhoGtYipdeq9ElDYbw6x0RobaMXLY5WONCUL+boNJfFocXSmQ4LS20OkN0OQ+ebkDc5EvRlpi5XuZQpFMVpkTTgEdI9HpU2qDvREXfcUI+ylcA48nJbGBK+4=,iv:b8TNa8/CmHjzx8aVnaC8zQFzrShM9EusChmTKoi3UHo=,tag:Ju7VyY0u/AHrMjWXCLblrg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
