apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UGfPTkvs+uGJbsLCUIMhkbpOjzyuQykcEbVXo8yu01IEHx6FBeIm1atD0dKyui0JL8PSj9cjkbP3aOiDDzl0XdPiIakOGVOujtWM/hQB6THSjFnddiAJAYpWDDsC+8mm7SHkh2mWc/BKcdsCWpJEJ1npduit6+zr43G8/NPB7LxLEiJTxmpDKjTzh9l9sj1TCRT3tkbqxgXk/C3licf4C1WH7DaI5r+bUGNMgEfPwiXzEFrtbGzMqBbrdqf6xh8lsoghkzh3oGBMlQz6TD73jBt9gyE6oE6uStrJAeZgi5VQ5Gfjj+f9aBS/MqQzoFokeXVxm2vDjwzRmfwa7KS7Fjntrw487E8T49P0JRqDMgMpgFqoZUmqQh83wayWZafW,iv:9VvHGVK25hH+hmcG1e/UlNiBbWG9Mi/IG2b1BDBJi/w=,tag:plTYI07bABqOTv+dUh0lRg==,type:str]
    identity.pub: ENC[AES256_GCM,data:TJo8s4u0X4HJzzxgIhUHKkVBK1DuSDqYxH4TCnaojfqTR3kIxNUSnC9NI88NJ8Mze42R93hUstE9eY6EesUOla/HGQLce3WMhmbQxwv8laPgoCZ/yMYjXhXSamRb5BJ3yPSVPWKXL51NOlNCVLFhuN2x6GCV4EMAA9u+NKvb9TVfxjB0i620Ymq5FhLjWepDyYH1E5pGCC9//xsQLcIAFQrmfLc7jNKs4Pzlo9vykitC2R5BduhPps7S6LZBnnBGWRMWLa27v4aFFRflyA==,iv:NGAQ18gDWe4PVvh0Gz+kWeehq6mXXxcwa6JdaL70ldM=,tag:zF/zxHaFgLxwp7+ete95tA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8FDNnCxXFWa0pBf5wrj/a2tiGewSkB5dDzfAkobpbRikMaDG0o57kve74U0DHxYbeb95M7r2scu9lLpp6yOdctQ3IhAVOHGAXb21dMSPWw4FuVPYXnstIZKmbNT1YvxzQEYknkg5b7E3SWzuA/BdpCvDbUkgpSuS6B0BcbnUodiOuJXyBCdbJSoeUEQcN6AyHvYrofqXK7+iH59K9BGyOYsevRdFEqPiYLvO,iv:3FZ8vJUlLHqVXbpy7+DAekwgYZdc2HjECWcIWZi4+4Y=,tag:eCzVeq8CZxFAbzF1oJ1vPw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTVBybFZIZytzOUczdWkv
            TDVYWmtYclRVSVVFTnVOV1ArVER3VVhjL1I0CmJRRFk5aDhUbUMzS1ptUGhqUmpD
            amp2OFFERlVjenMyamM0M3lJblZYa28KLS0tIGkzckx6dEdYL0RxdndyenVqc1ZE
            ZEgyTFJ6SmIzUGprSk5lS1l5ZUhvSUUKJ/XM3a9lOOxbfw4UtjT/NU65DhI5Ym5s
            6Mv90+OdVkpRHkv/E5hUt1v5Od3bv2OStfUazxxNeC2AVrnhawpz7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T22:49:57Z"
    mac: ENC[AES256_GCM,data:maR3KYRNScmZuuOZjDSQs/ma5TfsSsoWzGBiOVAHXtAdUtPY5VQMuybX7LCJVrfSVxVs5KgiitoLEQD4un+N4T89RE9DVq4nuOJ6MKmhQ/9KNiBvNtoFYYQ5961XOPL1Bcm1/CljVIjDQFtX+T3Yjq2FvmOwnLFAG0n6TVUuus4=,iv:etzGJxFsHT3AVKmvEec0fNpHSd8r+K+SP9talU5rVyM=,tag:2ApMS01HA2XWK2iWwQmqFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
