apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Ec8/k2goNLRWwP3YwL3U8FlFCbEe/4HOkdSGJkdO3mYXst2/JJ38KO6bN9T7b6vUmqk82Gw1LokR4SCoZP4LnQDIKsyHVFW1coErsC/nsfsEsvpKQ+FhTp0i/xj8iv+dtWrlvZOOQU+VxFWe/NJXeeoVOcdhPiU+Z85DZ5ZPkH3qiZwpyV8gcOWUkrGqR7wykXJDr8DrIFKtws/CfmqPr/Ohq16hxP7jUNquysSnmkyfwLHoVMAyRABNXacbxkifqKdi1gBfkhRgN6ZQpCg6wI3rVjaPb14IIjXqoZTkBuK1dQZIBKhf/enMfwXc7296iSa3atoCB7jAhTMd4DQr7WtqjhK1cdXWUEzkgBTacZfHTdiJ5Z6HXPxhoBlvCgy2,iv:1MrdK0h9iWMhu0W00FJ0hyOYvb0dSqAjGYz96JY7a5M=,tag:JkJBOTve5fph0AMnHG6Qwg==,type:str]
    identity.pub: ENC[AES256_GCM,data:jwObc/o9Sa8PA1ur0dq9Fy3qzumReoSYIJe+wahuWIACogKDUDo7E7eEDfQEVcqoYg+4Fy8zgrFHhGLtXKDHBfR8/R61YKZ73wzJGJ0LEi5n19XBvegj4J/ILSB235MxEjWG29hPJbdUz7CQDoJnYEZIUOZu0MsJLOcaiUbJ1wnLSsfWh+LCQNrdOEHD6zRq41AP54Df1Ntjdy8lZN7h5lyEQczLnbU0C9fTGPqL7WD8N5SrxsJr/xTaucXadd6JwSXfgetfdXInYoyjAw==,iv:gjuPf6+f6grfLU09Z4AWlY+braNIlLZ1z5H3xcXrAJw=,tag:1gdswDnuogHMmH1FMPFOiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:73MSvV4jj01B1CiB9xqOh8wL+9L3FIhDEieaJIStsLDu6nKNMHpEcXKlnJYwZjFdg4IW6d0p/VeVd2wlZC3LI4eMFuqAgza8JCifaWrUduQ8BCBRlwWfsMCLKNBqZLdO2vbOOJjEBI0N4+HsUnSPnszVn3wOdpPBJiGBz4j1yhXfaskSh0YfiH0s4+f+UES8k8Ty2oijFBQm7e8Tx756g4AZ+WNSwin9a6sD,iv:02h69ANA+X5qbOBaTccLotSn8JEuPFUEEBh4CyPtSE8=,tag:x0KEVv4dwLMcUZOy5RzXEA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRmZmMVUrNWdhcmpaNFI2
            VElvdytyblhvRUJMWGdBWHA0bHF5RmZTNmlnCnBxMTVSZHNTMFdzc1lKbWRFZ0FZ
            T2hTMVBMYlp5bUZ0V3hqY2Ivd2pmZWcKLS0tIGVmYXo2d3dGSG0xQUhlKzY5SE8w
            aG5wb2hNMG9ZcXFXMW5FbVFHakRYZVkKhvfXQndRw4/qlTYhryJTzp+xdArkN+Ga
            xTk0pIn37ld3NII8QRAP4L4VEFyv7Qhs4DoxbvzOlKBl8qJfMeG55A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T11:38:25Z"
    mac: ENC[AES256_GCM,data:L07BYQEJA7N5VB5Bd/bpagr4zXswz7SjxNZ4YR1dkIFMmBZDAPH21WKwNKL4xo4VrTrZHYlDkpqmzGeFzRsgEDgZVT8ueCKyZLHBTiOyTPSXg4lliLF8bq/qS/2ZfLLXuh5+qSEezPKX0ygvJEVDKQj63VzXCDdG3fYH7Sh3Zfk=,iv:T5pSNiZFFzMalJVo2n9vVnBG3VoxlLscjLKen8w1UXY=,tag:zxzRxOTOmIYnWOOmgR6JIQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
