apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5SkMtm3UizRh4VYF8Ut7GTV6qJkAcygmJMKYk5+p0YF4Y2tVNGT4FzegbOmM5wlu/3Gy76oXLJyGuOnofJy+gRkbXGBsn8HnrCBBRv60pfXMjw+TIADiBRmFWRFwPLaF3SfCXHw79zhy/3t9dR0MBnEzvC91yv5tPWNsf/pCR3QjfDEg17uYxkOM9sYCZ5ot12ZVoFyMcv8mZgo4VUXbWOYFEHhxrkGbCwTWZWkml3Z+6NNNuvM/gd6AKGLQh6ScGvUpwvWOCQ3lmipPRM5Df9zOn2jJZEHhMEJtzqq7FkN+mBYCuxVRFgq/GO5FnZU6v6G4qFH+YOodvQdnnfNFJiChuGZEPgbMuA6jaDRU6cKIa/B/05pmhV0tW0fPWF1o,iv:SGAbvisW7qhBTQnJwNYOFPtvfElMAFql3fnSKdfzioA=,tag:dSFwInpFSt6/O1asetkfJg==,type:str]
    identity.pub: ENC[AES256_GCM,data:fEyr27oJHHG8JQetNrWbo34fe+wJvTRZI5aq26WkwpQeG1DZvS+3lTeRgbgWAwUcbnPe5U+oyOuCpLLz4DaV2t4VG+EqhwivwXFjkPytzmXkRhzPAcuJ4jM33EXe5WNYbti6qkeXwfLP7SV9ZsiZMPYxCJ2FFsBrdKEroBqiMHE5JuaPaWZU8vU8hNg86ghM3WA1JHxDJ5BRAzYJTP6/pOxnqRcxZ//eTNad7J7tcJzxcxfI9M8z/wnA/AYpOqNXLd6jgQ7UG+W9auQ8Ow==,iv:oRWKhvjcZykmkz3fM3dEzD1JkkOV949h//fxPT55U/4=,tag:yDzqhSDfPZVuhpw/R5zmVA==,type:str]
    known_hosts: ENC[AES256_GCM,data:cls5fSHQAwwycvpkbPzPv4SFteizI1NAnWTYu/7RRL6QAdYVXFmwSKzTkbabegXNkT52kyp0QNavxLs1DEhGjkH7sAOHAkmWuisuzYBSddUywNo3qP+6cN4D7Db2vd2y+Kh784ktphlIhjB1gKHAMETXnJw9qQb8WzBqCkggCbi88zqnL0fIlzOPFkMxz4SN9M8plBiwJrqj6RaBjb9GPWLQWcuE7cNN2WXU,iv:zSdFOC9fhfq61OjUClqsm75xlrPybl9gCjb3n10Ecrg=,tag:sDVR0kHznsuWBaaL7IbGVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQczVGR0R2cmRYczNhUVhH
            VXFrTFN5L0I2VDRPR3RYSGZZVXU3Z0F1bVQwCmY4ZXc2R0ZyRXRqeGZoczBoeU1Z
            bkNPelZCWCs0Wmc5MWFXZktYbzZRR2cKLS0tIGc5L1VncmVmaUdEYXdUR2IxdVpC
            bXR4ZG9IeTJYS0FRTHUxZU9BTm9ibmMK5V4Qkebi9MDdFgvV20UusSlNFgQrxTpf
            MLYI4mnD1AVEVPzLb/Vmz/XYTSF8Vext0aGOYUBxFJINepbb4D4oBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T05:03:10Z"
    mac: ENC[AES256_GCM,data:uGnT25hiXyqlff3wrR4ByR6zKjjYO/m3tC2FbyYJmhlDFh4uk7mnZXJv0gU/oOI5t8YfAAsFMYDRl+7aBogjNzAysTGCQ1vVIaWE8QNB69QEo/lk1vJxSkhbhXX5M4N83TnXUnN05aud0ACYm8WkYFUwidWIMVXF/Yg4dgYJ9ew=,iv:aIObTuFD6AAid1oyGfsSWcDD77b5PpgGZKdDcRpFm38=,tag:SkEvF4y6HYf3EiXG4YjxSA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
