apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EW4a4qJQQLPhQrf6IVhDlZqu1vkfPbRdYF7BvemHI4UWn1lbbiajFRho4GrR8Zi//9qBVeXHLIa3t7tcAZ4I4UAXeJzpext+UwhXVBTeZLT1jHWv3yiuDypwpG0Sjf7ZoKSi1TA/OUaIg2Ek6lS3N2nT7ov0gXSq/kktk44hoIGYCuJeabs2PtOewl0ClzrX23J/TPKvHuofPKGvlEpFIvNKl0JDffYXcneArMYQpifFLtV0LUtNTfkI2LAjvwbJ5cCMXTtc+DlmBIkir3pDKokmZLozsHvh7vNF46t1KTWUo1i1+VcnJwc/sv062J+juIyGBYpFaqG1ZhrHOAIf527SppS0aszR2r9QC4zWCAdsk/zx4e/OcESINPRMWEKF,iv:plVQrCa3Ems2pu0ioUCBoz2vBlFJxYrR/9r5lc3FfKg=,tag:SmRqMWv274hbWAFwHfeK2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:HXZ3WtixkG+ka+s9a9ql0htlh4dP9ej3EDz6Jkmz3P8QMhNZGOc7QvTKbSzNdgeTE08W45o1isFSPkQuyC9irT9yclZOUqJ9+fPCwOLPgGxcTQb/SsY3GY+BZTUEcun3rcTlfrWjmgzPYDzcLhYGdhibLmP52Ae6AqZfIBN38Wjt/XrAZ/N/YQ57bzf08qWvPRf73mJUOleAKazELAxeomKMH9ymBYBxklnoW09Vk4T5r+XdI78e59LWBCJ2t/fjs9ov9LYfgJxQ7FZrhg==,iv:ODlW3yTBghjn/lY79QzWosJc20BWaqcAnild3PHYb7Y=,tag:TX1zXqO+22OJ37X896Z34A==,type:str]
    known_hosts: ENC[AES256_GCM,data:f0GROXXdHp7irqDIkdnSxoZl03cxc00R82Gjium6nJjJ+H7LkVx5m0zQbrHSoeRysSAy34ijXncRuAlTirosOdS1jf19P+6xPLYMrkwsJ4JrL7+AuBSWY0P66hzkEnX5UhTtIQtYpeov0VAioDw1O6gix8oelx4akd0/NX3sCxcJ8W1QdzUC5Zw+VSksdxynWO0CFtWWAYImHl/bdc3S6fmyXbZ+Ce1HaXgL,iv:V+jmxI4tOAJiIG05Xy/LVCSmgYaZlagE3vBP5Wotiic=,tag:Qaem95B9xgrKmtB0JFBodQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZHUrUzlJRmNhazA1ZmNR
            a3BsMU1UNXQrQkwxMlBTN3hoZDI0T1hGa3c0CitSSlhyUzdJR1pzd2QxeXpNTE1E
            VVZHaFQ0RG15am5mOUhZb09kRkVhM0EKLS0tIHpwVlZkU29kSW1GYVRuVkE3UGRv
            aUg0b29ralFlUmt6OU9Ka1JqMFcwWFUK5uWx+YeQN7zFpH67h96ymXzXAFDukmto
            5X0sTL1I9wst1ElA6nc3lsB2Nv7CPNHK0qxrw2mQGA6HHgEoB3WFbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T07:10:18Z"
    mac: ENC[AES256_GCM,data:1noo82FSZOB0EeZfNdZmp3Pd4tKDSjReuYFjoPrzltN79rZEbkBOinAkkNOEnbz8f/kWD0Z4qWV/oCjHKqWzjwP+SLTn3w1ZxI8Y2MWf0tzMSjjVjuE+j1nzhaGQzL+sdHRmtek7pAj2O8/vXUQF6e8G/JOF08d0WXTjCbfFZUQ=,iv:3se4YOva+Jyc1RTA96SdtpmnpumkKgXY1udfWzCn1W8=,tag:QaL9rpjgn8KiIQpU0tpL6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
