apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:m2/LJ+mBR88SYVLBjQISBO8da+KmdShwU9kxzIzKiUlHfhyhk3FeO8txELD9JlG+EOYDnI0xJ+EYwF7ZBubjP0q2IAmSXJ3zqmncBgGCpX+xUd1BAISCB0zZ0/V6IkKN/kLqqdiHMSQL+axNqWBUkL09uFYDJwXxjMZkMLmEc5yPjApGdFzDtIBm8zRumfl0HBvMnEhBcRCdrv8SuicobRAtMYvPw4Kk4pd9JIUQ8qIeFZwclul4AphqK2iWTS1R4W11bgkqlQ8b/yRsxhpbSBM7fO5QI4ynXaH8daY5u2Ukb6JFtuIHB8aOHGfRRUPUNDLo83AWN09+BGpnB0oh0Zbs3g7kMXe/T1QkU3Qr64qxxGvDeV2zFl3WaLqKehwr,iv:zQ+PHJB+/7AGBQqxv/24Ejce+XHdOf0Y0DddphPShbs=,tag:hCsOf72AlhxgYaVVViDrjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:CE/qFx1RFDHyljEUTyoLIgOsG1PeIM2cmr/YZhHsX3v5grCqEiWBQf5j9jFn9HzqzmCJW9FdSPBtKCLCiS+/kJadnWB4sLYo5sHXNoxj5vZqwyUEzO5xuQd8xdQ2mcF/HciUgwp3Doee/N+jb8ef7u2n3Zcxhnl/HkkWu4vqMR/IsWQzfaij3WXxMsjDndwgBRdk4p+bIsoaOdE1e3woZ2Qzt65y8q6W/iQGjmksTlYqkKA9lHzG8ABfHrCDyVPGEW7CQDRid3ml02Wuew==,iv:YEQX74gJcVXmv+s6Xe9gWwcp6/zfGOcWMkTS80SWEh4=,tag:RoBdAvO/vR8Ia/FXvnPg4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:NU5a5OF2jTVtTduHSq9NrBBZkD8DfqWjmcluDlOHW4nTZxqwr/7X3l6CpoqftWqJoJPx1kH8W1A9bE8nzJswJMa6KejE0byMSVNfphyZkQsvgK6u94D5tV/J68Db5YNYKDiJ09ipMBN0i6yxLI2Q1xJIIIO8xVrj3nhFikt7n6H3rzaGVhoh3nH+my4kbUbtFqk/gTUiIedhAaCvdEu6f9aSRtaXjSQelEGh,iv:N/TA5KpgWtvzx7VSbHDW9kij4+L57KRhXfQM4yEPLAA=,tag:NIsvzMt3NzDVwhbXsgQ5dw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTngyT1JjdDNFVWk4OHdo
            aTJnaDJCNXJCd1pqSlQvWkRScU9HMWhTUG40CmEzdkxCaVRPNFRNSkQzRVBMVGdl
            b0R4YTNiQlNCcTMvNFZTb25VSVJ6d3cKLS0tIFZUNG9zaTA1N3lJN1FMNHRRbWlk
            Vzg4SDRWY2xMTmJSeGlnVHNCN0V3VTgKQDD2gaBm2yeyRme2zTpfV2xS1r3MVdMG
            M+3dGIzQX9uX1eHa4MFZzXEWulShbDv+cqlttlFZVBlZgBl62Kp/OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T22:54:35Z"
    mac: ENC[AES256_GCM,data:oCxSyAdBBY9aiw3mRMUgBD7OZzj3w6LfsnRcbT3WHt+vRBY8MOAIlhN6I6YrOx6W1EiN0d9SHdzwP/DJmW7LolHxXOezVSCI5LHaJu4UER6Z5noNsFDWjwIzSNGWvN35OO3MjU7elcN9Q4yuSiwlSWoE/uACIS8oDQq7infhnvw=,iv:YYAE0OKB8FJl1EeqN0sjAWYaNaR8XAJA2PFyjnnKapU=,tag:9oYyZtqSj2dAIigvd0Jrrg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
