apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:41gtOaTPpAKsLH+F30JhzJs9yIiJqn0I36QKNzqkrzI13Muwb3102JBWrI9SZMcxjvNcDDuWXukpY14gpfbrTJTkHn3ce6tHdnslcD+N3QEAPoZCONxWqpcI4ZR4jOHkPkw9nIpFyuan3QCWpQCXzB1XlA/F9Y9FcyVqW1pOxJy7K60mRt72xB6sbSXFAFq4meqzwDc13MrKnAXv9UddZUOJw7CQcoSOBpO1zIN12q3qFHEocwNKVLZ/o00EmCYZI0hyVPhgW0Eq8rwGE9bEUOckHLOWRejrojDRWnVht+7EldWweeSDk1e5qv1/QwTONWw4aJP7Pnm1gx0BFHHzvwj6xZuY+e6ko4UpooAlcrFIp3jww8f2WiHiTX6dCVgN,iv:q6nIsV5kLS7zEOA3pxXvKH8uGZfHy4Z21ynPe02WWGA=,tag:AufCNiH7fimVmooMjFTH7w==,type:str]
    identity.pub: ENC[AES256_GCM,data:z7ZmoV+gTYRxL6fQNnB0ynd1DSvSBZ22HuYkfvwqcId6DlQHmhKh6Il+WrlqxNqI6JDDqUJzM3wlriq8vgrDZig9arwbNGy2sTQ3xkF9foTkR06UR9orzvBXEVnZyVeqZwQY3IkR9xR1M3/1qMqfpy1mul0pN7oufVoO4UgkEYqn0zbAaZtM6H0/hgBrT3tRiWi7qucoGF0hkfsObTIf5+PtXbekxcrTQlQTPttO3M2s6Wi9HRVLDORjl59k9ekxj99x47wiwwpSQGCtzw==,iv:LbLc91OZGefVFsGeTEUKtewsFKAjeAhGciRwKNor/VY=,tag:eDyRzpjmSDHimqKL+yQ2fQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Iqz8jcBfMGkQ6vu9tSR5gMOxU+vUx/r+OsqG6uA7ebnlhqS/NnWu96M5Lq8jn4mZTeY+7FnqgDkDCe7O4AKKYdCPuoxz4rcMUEpBPdvhmYsG1guDNzpbIUAUjZUxvh16WfR/a625bjukThfAxRcebF2ZpEV4t03FYSTxCD8l6SRzjvzGqhK1cK5RedQS3FD/vrukHwHVMlyD09R9W4dn+zDQvbjH2thH4gMQ,iv:XAXFzu2kTvcCQC+ay+QaEewnLdSSFbxAqfB+lWRgl60=,tag:Rc1Y2ZbqQakjMRldRwaUvw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWjhVYlNVU3VVS3JJcnZJ
            R01tY1pTTzJkWjJGMXQwWGxLcFpYNFpGOFhJCllNMWF0VUNYZUtUcXZVTjNOV2RO
            VWV3azNlNk5GK3E0eFRzZ2xmR21aRjQKLS0tIDVuVVhTNFovS1M1SGtRQUVmeTNX
            SXhLRFJjK2wzMGhLRG5rZERYUEdvVjgKr1I22QtiMcfFZLFBl3fgv7eR7NeelJHx
            fdrHUSn4iHoDMeI6VC5X4AaM2K6plxn0QUZ8E1uhmwCJEa1jNEz3iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T02:03:12Z"
    mac: ENC[AES256_GCM,data:Ug5OzbGk7FVag7NSTkbU5gM6QwJKjunEBouJlN1vUflJszPkoZj3O2PN76kBjoqocOMZ9/477c/7ICsKrm6YW7sH09GWtd2c3o6EsxT8EPQYvTgMvOtowYUwesOkHs91tQHVsrfWq4/REc2N5RKYpOQvUj/rRrKAFiu5W6HUHAQ=,iv:FFxMazEdAl6ckes3bk0FWiWwaI/QR0n0bbuVS5ltcaM=,tag:NdyGulOIOoE31dxh8OoPcg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
