apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:u93/50wDznXYE8W82KVFyg6BeY0D8Pi85T+peVhN2xCpBeNVBOqeKvbnnICHcLh8FySYJZI5cHflo4a3x3zVvjj5iXI2fWi1RiAmWR/nI/eo6iIDMbRoed6/8DUgzd6WvTKISmUQsrDrZMTIvhnALDiXMGtAFVRywKzcqort2uZ8qx9NHlZMFUCt5tZ2CVfUKK7h3/LSzJn8RlQ8K/aomReKA+xgWfaFIzSEBizEAa1A9CmbJhJsla2nIJnqiEO+W+ZVKHX59BxHyO3HCibg5ZqAYjzahFAUfsLWze5B+uZjN4DHOgWgbKMZTspnXwAJ4MhO07gmgqXVUDn3uNMici236AjNBnSJBMRd/Om9Xrs9OL2ZAbh/KiLQrrQcpfXs,iv:iMSTHaMlMfA9UJlrugIGVZxDtz8lZeNJLAB+UWD++HE=,tag:i9+rN1S3jjmQ/89AkVda1w==,type:str]
    identity.pub: ENC[AES256_GCM,data:YPyTMCRMVa6f7kXdAWa2BQDehbTmopD1IawY/oqeCmz9lkbESyvMiVf1TjWODfYZWHt3jCMhgk9ruDKzWoK4+Ir2mQmcWnghAkPEfR/wP0NW4V97w+6yXIqhH5d2SvAm0kFxtmvsOe8lRUnbgsMSTv1jLePTODWMKrKZurS9W6GX6SOjiX4V59Fi7WDHGTm35jROENMHTZb9F8LiX0umOfIWMzh+USf4uZWKw11AKrlj52HU1h4YVq3XyPUcjfYaJio87Jp/RVBt3iy+Cw==,iv:Go+9aZlhtafeYtNj6S+3YnMK7wBjr0NtFzPP8aZShZA=,tag:JHFxlt0eACqosbxVQt/8bA==,type:str]
    known_hosts: ENC[AES256_GCM,data:dbFVdKdY7EAphkTAHv3nNqdFZuUGqB8mIQ6NkBaYzGEMjYbgHI0Ny2nfpdsHaUrhnzTuwTQc4o+l2DwrV2XgwFlqBDwXDQiJiYM8cHn8Q0HrcLZp1wqM7rIM3AQ0x+PJ2vhQqCKj1c8y752KFlhVUTchXmzy/qFXhJs5W+qjQI0UP+zAw7onBQTc83KfcUplIKZM6nMiFA53OFTqSUbCy5kSgPnSYfbmK4z6,iv:n7p+b4UI6R2NOEQkxAXJXyiXZ+/KfCEscKb7/jozEo8=,tag:XtI5avnsGvoFU3L27Pp+jw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUWhKVk9NUmhBOEF3ckRm
            dDRZUlJ3UXUrZ2IwTHdOcXBLQ24zMjk5b2pjCjd1VGJBMTd5cEJ1cFdXSVdpcTV4
            dksvREt1NStjT3c1bkhoK2tRZUNvZDgKLS0tIHh0SG13eWVXOWgrcjVyZ3BxYjh5
            SzNyVFdpNXJncG5VTUhDZ2doWHhmSVEKwOZTMkn9dhVeWhDAqFkXMiQ29R1ZEZj2
            V3q/egYMehYz289CcI2ovvK8BZdzGcFK7cXuwGGHKjPAfkIkmkrjAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T12:19:33Z"
    mac: ENC[AES256_GCM,data:NXIkmxovGU3xQWJD1CzvKyg6+NRptDIjWXY0jq1O2XMZqXnV8UUnKdwYzVwY0g9jhuKyX4G2HMt3K2dqU740CGu3PAJR4k107z/SCX7aLkH7MdT/2leS2DNPBXWUpIVsVQCJrY1wsvr05JbWe/w+irFV/2cjl3Rw460nV/TeG5Q=,iv:K7egDpdjehBsgubOoSpAYLjCnMhQG7SsYs9L91ydqPU=,tag:6PKSVfIayUS2vVfWzb3VvQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
