apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - sabnzbd/ks.yaml
  - sonarr/ks.yaml
  - sonarr-anime/ks.yaml
  - lidarr/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
