apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lldap-test
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/lldap-test/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

