apiVersion: v1
kind: Secret
metadata:
    name: authelia-oidc-secret
    namespace: authelia
type: Opaque
stringData:
    hmac_secret: ENC[AES256_GCM,data:aurjw1HPTvIqX68LW8Cw1OPXXR/XN8+2vmstQ0Gn1jMEzDIhJgbi1X4mYjkWwi0C9ffA7tmNpFUz5c77EdyFqA==,iv:QWK1rekNjwcT/lreOdHlSu2xkgDyWvxP+a7AZMBC63M=,tag:0/3AGj27D3lCFnPv8dX8wQ==,type:str]
    jwks_key.pem: ENC[AES256_GCM,data:mc/0z8//QhSNpHbIWgpKBRGfsTeKaPscD+IKv3PM0FWrzeMu3cbzTTJ6/3jFBOl6hhICtRmke0ajMePBiSUpwM8B135obRy/kMBM8LXLcOi+ilin64qZ4vRwz4WWhVDIgfA270d8Xp7V8FcjjQIF4jcZTL8DXtjz8/R7hzb37aCjTTAYBypCwYCngR4HC7LdU6R0H1ojamICSPOfS3VG+k03m/Nc5CTqkp7inqtvIoR1s4HB00Ijm+DmypvKtZBgQDpbM/eDzkkRlpl4R4n2hlevzKotoD0HON0AecQ0VrtmcKdonCrg5Q==,iv:NAsyUIYYyzIuIg0NocWEnmAlXUck+2xHUg2GTLVgO3M=,tag:prqRXs7rVD/UPg5Hep/reQ==,type:str]
    clients_romm_client_secret: ENC[AES256_GCM,data:d4IeyF3ufcY9lD2w785lJ7xfRcQt2EcShYyRdQO1D/fsEAyywUoN9HAlSEMVHzh3ivVqjXxsO83JmTtnq6pQZw==,iv:6hgRL3urMEd4p0+fcC36IrmZyvZes1MJuWHXWoXC/9U=,tag:Oft9XahX36m+J2qxUJY2Hg==,type:str]
    clients_grafana_client_secret: ENC[AES256_GCM,data:Y8VLVcUtRIqSJaB8JDHGpukUsofrqgKwdmA8sMzOHvLchS/ri/uUafW0SwOh+g3E3vr5mBclbEv7Xry1Wgxm0Q==,iv:xoezKU7HBppg0/l1hPVFQqczwNBX9j7FTgwUjWdfKUs=,tag:OvlQognDgnzjuMKQkvs/Tg==,type:str]
    clients_paperless_client_secret: ENC[AES256_GCM,data:/d+R3AnT3tkeRdXrHYjfy6Q0ly/r2UnIftv8HTW+mGdHTQJkpSZd/J0WFtiEHUmuIZ3nI99GzI42ufy6akSKuQ==,iv:ih8p9WcUXi6hmalOOn+8EfcTz+FnBrW8VPoQ4QmQYwg=,tag:aBblURu0m7sQAXUfQA45yg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1avfc23anwwceacc4ydw7rsdjtrdm5wn720q0fjfsrjqplykn6p4q5vetdq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVlE5SXVnaGl5bjEzRDNW
            VDQ5c3BySHBJMS9oSDRnQjZHaEphS0tpNGhvClhjaHRUWHBTUEpvNHN4cW9DRDVn
            TUZCWjZPSGRFaTljZ3NwZk42cjJ2U1EKLS0tIFE5VTFmMjVTeUZYam1hdUJhUGNS
            WE01Y3o5UFFJRWhtTVhSUGp1TkJhaUkKShTG0uxARHdcE3qeh8idl1LWCITLi/Fc
            qaNkN8AKJZ/9kloPR6KGzW8OiEoHSgX7m5uZ9WX83hzkXeWwOnfAQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-02T05:13:11Z"
    mac: ENC[AES256_GCM,data:dpQReQBXP+3vfFp/4U126ZjSXfohyDCXUht4Nm76TJpI+tOu8xvR8klxZ4kwZZf3CuZrVipUezktZrasSYf0GgKwE8PgjYokcWzt3XaBfZ76BWzd3wcTMuj2OamZgEeufS6nj5VobEpiZQhgD4DBAvB6UBG0VD830ulHXT7PjGA=,iv:EKbE+CXOtjuV41BRALEtuJiBQ5A71Gr3dR+v9mDOxfA=,tag:OEU/SqbjaT+XLgIPyRIRJQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
