apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Longhorn is a lightweight, reliable, and easy-to-use distributed block storage system for Kubernetes."
    gethomepage.dev/group: Administration
    gethomepage.dev/icon: longhorn.svg
    gethomepage.dev/name: Longhorn
    gethomepage.dev/weight: 10 # optional
    gethomepage.dev/instance: "public" # optional
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: home-ops-mirror
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    defaultSettings:
      # Increase to 3 for a multi-node cluster
      defaultReplicaCount: 1
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: 100000
      # v2DataEngine: true
      # We are using Talos which does not need much space reserved for itself
      storageReservedPercentageForDefaultDisk: 5
    persistence:
      # Set to false to pick another CSI as default
      defaultClass: true
      # Increase to 3 for a multi-node cluster
      defaultClassReplicaCount: 1
    longhornUI:
      replicas: 1
