apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-longhorn
value: 1000000000
globalDefault: false
description: "High priority for cluster storage components (Longhorn) to ensure recovery."