name: Renovate

on:
  # schedule:
  # Runs at 00:00 UTC every day. Adjust the cron schedule as needed.
  # - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Need fetch-depth 0 to allow the bot to create commits/PRs
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v40.0.0 # Check for latest version
        with:
          # Use the default GITHUB_TOKEN for PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
