name: Renovate

on:
  # schedule:
  # Runs at 00:00 UTC every day. Adjust the cron schedule as needed.
  # - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        # Need fetch-depth 0 to allow the bot to create commits/PRs
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@c91a61c730fa166439cd3e2c300c041590002b1d # v44.0.3 # Check for latest version
        with:
          # Use the default GITHUB_TOKEN for PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json5
